// Converted from LANraragi/lib/LANraragi/Plugin/Login/EHentai.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - external Perl module reference has no JS equivalent: Mojo::Cookie::Response
//   - external Perl module reference has no JS equivalent: Mojo::UserAgent
//
// Hand-fixed: the converter originally bound all 4 declared parameters to the same single
// `hostArgs.arg` value (a since-fixed host-side limitation) — now reads the real per-parameter
// values from `hostArgs.customargs`, positionally matching `pluginInfo().parameters`.
//
// NOTE: this plugin makes HTTP calls but declared_permissions.net is still the
// converter's placeholder — fill in the real host(s), verified against the URL
// literals in the original Perl source, before this plugin can actually reach them
// (Deno's --allow-net grant is scoped to exactly this list).

export function pluginInfo() {
  return {
    namespace: "ehlogin",
    type: "login" as const,
    parameters: [
      { name: "param1", description: "ipb_member_id cookie", required: false, type: "int" },
      { name: "param2", description: "ipb_pass_hash cookie", required: false, type: "string" },
      { name: "param3", description: "star cookie (optional, if present you can view fjorded content without exhentai)", required: false, type: "string" },
      { name: "param4", description: "igneous cookie(optional, if present you can view exhentai without Europe and America IP)", required: false, type: "string" },
    ],
    // TODO(perl-convert): source used an HTTP client (Mojo::UserAgent/LWP/etc.) — 
    // fill in the actual host(s) this plugin needs so Deno's --allow-net grant 
    // stays as narrow as possible (constitution Principle IV).
    declared_permissions: { net: [/* TODO: host(s) */], read: false, write: false },
    name: "E-Hentai",
    author: "thelastfantasy",
    description: "Handles login to E-H. If you have an account that can access fjorded content or exhentai, adding the credentials here will make more archives available for parsing.",
    version: "0.1",
  };
}


export async function execLogin(hostArgs: { customargs: string[] }) {
  const [ipb_member_id, ipb_pass_hash, star, igneous] = hostArgs.customargs;
  return get_user_agent(ipb_member_id, ipb_pass_hash, star, igneous);
}

function get_user_agent(...args: any[]) {
  let [ipb_member_id, ipb_pass_hash, star, igneous] = args.slice(0);
  let logger = legacyCompat.getLogger("E-Hentai Login", "plugins");
  let ua = legacyCompat.userAgent();
  if (ipb_member_id !== "" && ipb_pass_hash !== "") {
    logger.info(`Cookies provided (${ipb_member_id} ${ipb_pass_hash} ${star} ${igneous})!`);
    ua.cookie_jar.add({name: 'ipb_member_id', value: ipb_member_id, domain: 'exhentai.org', path: '/'});
    ua.cookie_jar.add({name: 'ipb_member_id', value: ipb_member_id, domain: 'e-hentai.org', path: '/'});
    ua.cookie_jar.add({name: 'ipb_pass_hash', value: ipb_pass_hash, domain: 'exhentai.org', path: '/'});
    ua.cookie_jar.add({name: 'ipb_pass_hash', value: ipb_pass_hash, domain: 'e-hentai.org', path: '/'});
    ua.cookie_jar.add({name: 'star', value: star, domain: 'exhentai.org', path: '/'});
    ua.cookie_jar.add({name: 'igneous', value: igneous, domain: 'exhentai.org', path: '/'});
    ua.cookie_jar.add({name: 'star', value: star, domain: 'e-hentai.org', path: '/'});
    ua.cookie_jar.add({name: 'igneous', value: igneous, domain: 'e-hentai.org', path: '/'});
    ua.cookie_jar.add({name: 'ipb_coppa', value: '0', domain: 'forums.e-hentai.org', path: '/'});
    ua.cookie_jar.add({name: 'nw', value: '1', domain: 'exhentai.org', path: '/'});
    ua.cookie_jar.add({name: 'nw', value: '1', domain: 'e-hentai.org', path: '/'});
  } else {
    logger.info("No cookies provided, returning blank UserAgent.");
  }
  return ua;
}
