// Converted from LANraragi/lib/LANraragi/Plugin/Login/Fakku.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - external Perl module reference has no JS equivalent: Mojo::Cookie::Response
//   - external Perl module reference has no JS equivalent: Mojo::UserAgent
//
// Hand-fixed: the converter originally bound all 2 declared parameters to the same single
// `hostArgs.arg` value (a since-fixed host-side limitation) — now reads the real per-parameter
// values from `hostArgs.customargs`, positionally matching `pluginInfo().parameters`.
//
// NOTE: this plugin makes HTTP calls but declared_permissions.net is still the
// converter's placeholder — fill in the real host(s), verified against the URL
// literals in the original Perl source, before this plugin can actually reach them
// (Deno's --allow-net grant is scoped to exactly this list).

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

export function pluginInfo() {
  return {
    namespace: "fakkulogin",
    type: "login" as const,
    parameters: [
      { name: "param1", description: "fakku_sid cookie value", required: false, type: "string" },
      { name: "param2", description: "Useragent value", required: false, type: "string" },
    ],
    // TODO(perl-convert): source used an HTTP client (Mojo::UserAgent/LWP/etc.) — 
    // fill in the actual host(s) this plugin needs so Deno's --allow-net grant 
    // stays as narrow as possible (constitution Principle IV).
    declared_permissions: { net: [/* TODO: host(s) */], read: false, write: false },
    name: "Fakku",
    author: "thelastfantasy",
    description: "Handles login to FAKKU. If the FAKKU metadata plugin stops working, update your 'fakku_sid' cookie and add your own Useragent.",
    version: "0.1",
  };
}


export async function execLogin(hostArgs: { customargs: string[] }) {
  const [fakku_sid, useragentcustom] = hostArgs.customargs;
  let useragent = undefined;
  let useragentdefault = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36';
  let logger = perlCompat.getLogger("Fakku Login", "plugins");
  let ua = perlCompat.userAgent();
  //    # If the user didn't provide a useragent use the default one

  if (useragentcustom === "") {
    useragent = useragentdefault;
  } else {
    useragent = useragentcustom;
  }
  if (fakku_sid !== "" && useragent !== "") {
    logger.info(`Cookie provided (${fakku_sid})!`);
    ua.cookie_jar.add({name: 'fakku_sid', value: fakku_sid, domain: 'fakku.net', path: '/'});
    logger.debug(`Using Useragent: (${useragent})!`);
    ua.transactor.name(useragent);
  } else {
    logger.info("No cookies provided, returning blank UserAgent.");
  }
  return ua;
}
