// Converted from LANraragi/lib/LANraragi/Plugin/Login/nHentai.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - external Perl module reference has no JS equivalent: Mojo::UserAgent
//
// NOTE: this plugin makes HTTP calls but declared_permissions.net is still the
// converter's placeholder — fill in the real host(s), verified against the URL
// literals in the original Perl source, before this plugin can actually reach them
// (Deno's --allow-net grant is scoped to exactly this list).

export function pluginInfo() {
  return {
    namespace: "nhapiauth",
    type: "login" as const,
    parameters: [
      { name: "param1", description: "API Key", required: false, type: "string" },
    ],
    // TODO(perl-convert): source used an HTTP client (Mojo::UserAgent/LWP/etc.) — 
    // fill in the actual host(s) this plugin needs so Deno's --allow-net grant 
    // stays as narrow as possible (constitution Principle IV).
    declared_permissions: { net: [/* TODO: host(s) */], read: false, write: false },
    name: "nHentai",
    author: "thelastfantasy",
    description: "Authenticates the nHentai API using an API Key. You can generate one in your profile's settings.",
    version: "0.1",
  };
}


export async function execLogin(hostArgs: Record<string, unknown>) {
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let key = hostArgs.arg as string;
  let logger = legacyCompat.getLogger("nHentai API Auth", "plugins");
  let ua = legacyCompat.userAgent();
  let version_info = legacyCompat.getVersion();
  let version = version_info["version"];
  let homepage = version_info["homepage"];
  ua.transactor.name(`LANraragi/${version} (+${homepage})`);
  if (key) {
    logger.info(`API Key provided (${key})!`);
    ua.on("start", (ua: any, tx: any) => {tx.req.headers.header("Authorization", `Key ${key}`);});
  } else {
    logger.info("No API Key provided");
  }
  return ua;
}
