// Converted from LANraragi/lib/LANraragi/Plugin/Login/Pixiv.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - external Perl module reference has no JS equivalent: Mojo::Cookie::Response
//   - external Perl module reference has no JS equivalent: Mojo::UserAgent
//
// Hand-fixed: the converter originally bound all 2 declared parameters to the same single
// `hostArgs.arg` value (a since-fixed host-side limitation) — now reads the real per-parameter
// values from `hostArgs.customargs`, positionally matching `pluginInfo().parameters`.
//
// NOTE: this plugin makes HTTP calls but declared_permissions.net is still the
// converter's placeholder — fill in the real host(s), verified against the URL
// literals in the original Perl source, before this plugin can actually reach them
// (Deno's --allow-net grant is scoped to exactly this list).

export function pluginInfo() {
  return {
    namespace: "pixivlogin",
    type: "login" as const,
    url_pattern: "pixiv\\.net",
    parameters: [
      { name: "param1", description: "Browser UserAgent (Default is 'Mozilla/5.0')", required: false, type: "string" },
      { name: "param2", description: "Cookie (PHP session ID)", required: false, type: "string" },
    ],
    // TODO(perl-convert): source used an HTTP client (Mojo::UserAgent/LWP/etc.) — 
    // fill in the actual host(s) this plugin needs so Deno's --allow-net grant 
    // stays as narrow as possible (constitution Principle IV).
    declared_permissions: { net: [/* TODO: host(s) */], read: false, write: false },
    name: "Pixiv Login",
    author: "thelastfantasy",
    description: "Handles login to Pixiv. See https://github.com/Nandaka/PixivUtil2/wiki for how to obtain the cookie.",
    version: "0.1",
  };
}


export async function execLogin(hostArgs: { customargs: string[] }) {
  const [useragent, php_session_id] = hostArgs.customargs;
  return get_user_agent(useragent, php_session_id);
}

function get_user_agent(...args: any[]) {
  let [useragent, php_session_id] = args.slice(0);
  if (useragent === '') {
    useragent = "Mozilla/5.0";
  }
  let logger = legacyCompat.getLogger("Pixiv Login", "plugins");
  let ua = legacyCompat.userAgent();
  if (useragent !== "" && php_session_id !== "") {
    ua.transactor.name(useragent);
    ua.cookie_jar.add({name: "PHPSESSID", value: php_session_id, domain: 'pixiv.net', path: '/'});
  } else {
    logger.info("No cookies provided, returning blank UserAgent.");
  }
  return ua;
}
