// Converted from LANraragi/lib/LANraragi/Plugin/Login/Pixiv.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - external Perl module reference has no JS equivalent: Mojo::Cookie::Response
//   - external Perl module reference has no JS equivalent: Mojo::UserAgent
//
// Hand-fixed: the converter originally bound all 2 declared parameters to the same single
// `hostArgs.arg` value (a since-fixed host-side limitation) — now reads the real per-parameter
// values from `hostArgs.customargs`, positionally matching `pluginInfo().parameters`.
//
// NOTE: this plugin makes HTTP calls but declared_permissions.net is still the
// converter's placeholder — fill in the real host(s), verified against the URL
// literals in the original Perl source, before this plugin can actually reach them
// (Deno's --allow-net grant is scoped to exactly this list).

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

export function pluginInfo() {
  return {
    namespace: "pixivlogin",
    type: "login" as const,
    parameters: [
      { name: "param1", description: "Browser UserAgent (Default is 'Mozilla/5.0')", required: false },
      { name: "param2", description: "Cookie (PHP session ID)", required: false },
    ],
    // TODO(perl-convert): source used an HTTP client (Mojo::UserAgent/LWP/etc.) — 
    // fill in the actual host(s) this plugin needs so Deno's --allow-net grant 
    // stays as narrow as possible (constitution Principle IV).
    declared_permissions: { net: [/* TODO: host(s) */], read: false, write: false },
    name: "Pixiv Login",
    author: "thelastfantasy",
    description: "Handles login to Pixiv. See https://github.com/Nandaka/PixivUtil2/wiki for how to obtain the cookie.",
    version: "0.1",
  };
}


export async function execLogin(hostArgs: { customargs: string[] }) {
  //    # Login plugins only receive the parameters entered by the user.

  const [useragent, php_session_id] = hostArgs.customargs;
  return get_user_agent(useragent, php_session_id);
}

function get_user_agent(...args: any[]) {
  let [useragent, php_session_id] = args.slice(0);
  //    # assign default user agent.

  if (useragent === '') {
    useragent = "Mozilla/5.0";
  }
  let logger = perlCompat.getLogger("Pixiv Login", "plugins");
  let ua = perlCompat.userAgent();
  if (useragent !== "" && php_session_id !== "") {
    //        # assign user agent.
  
    ua.transactor.name(useragent);
    //        # add cookie
  
    ua.cookie_jar.add({name: "PHPSESSID", value: php_session_id, domain: 'pixiv.net', path: '/'});
  } else {
    logger.info("No cookies provided, returning blank UserAgent.");
  }
  return ua;
}
