// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/ChaikaFile.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Hand-fixed: the converter originally bound all 3 declared parameters to the same single
// `hostArgs.arg` value (a since-fixed host-side limitation) — now reads the real per-parameter
// values from `hostArgs.customargs`, positionally matching `pluginInfo().parameters`.

export function pluginInfo() {
  return {
    namespace: "chaikafileplugin",
    type: "metadata" as const,
    parameters: [
      { name: "param1", description: "Add the following tags if available: download URL, gallery ID, category, timestamp", required: false, type: "bool" },
      { name: "param2", description: "Add tags without a namespace to the 'other:' namespace instead, mirroring E-H's behavior of namespacing everything", required: false, type: "bool" },
      { name: "param3", description: "Add a custom 'source:' tag to your archive. Example: chaika. Will NOT add a tag if blank", required: false, type: "string" },
    ],
    declared_permissions: { net: [], read: false, write: true },
    name: "Chaika.moe api.json",
    author: "thelastfantasy",
    description: "Collects metadata embedded into your archives as Chaika-style api.json files",
    version: "0.1",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA\nB3RJTUUH4wYCFQocjU4r+QAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUH\nAAAEZElEQVQ4y42T3WtTdxzGn/M7J+fk5SRpTk7TxMZkXU84tTbVNrUT3YxO7HA4pdtQZDe7cgx2\ns8vBRvEPsOwFYTDYGJUpbDI2wV04cGXCGFLonIu1L2ptmtrmxeb1JDkvv121ZKVze66f74eH7/f5\nMmjRwMCAwrt4/9KDpflMJpPHvyiR2DPcJklJ3TRDDa0xk36cvrm8vDwHAAwAqKrqjjwXecPG205w\nHBuqa9rk77/d/qJYLD7cCht5deQIIczbgiAEKLVAKXWUiqVV06Tf35q8dYVJJBJem2A7Kwi2nQzD\nZig1CG93+PO5/KN6tf5NKpVqbsBUVVVFUUxwHJc1TXNBoxojS7IbhrnLMMx9pVJlBqFQKBKPxwcB\nkJYgjKIo3QCE1nSKoghbfJuKRqN2RVXexMaQzWaLezyeEUEQDjscjk78PxFFUYRkMsltJgGA3t7e\nyMLCwie6rr8iCILVbDbvMgwzYRjGxe0o4XC4s1AoHPP5fMP5/NNOyzLKAO6Ew+HrDADBbre/Ryk9\nnzx81FXJNlEpVpF+OqtpWu2MpmnXWmH9/f2umZmZi4cOHXnLbILLzOchhz1YerJAs9m1GwRAg2GY\nh7GYah488BJYzYW+2BD61AFBlmX/1nSNRqN9//792ujoaIPVRMjOKHoie3DytVGmp2fXCAEAjuMm\nu7u7Umosho6gjL/u/QHeEgvJZHJ2K/D+/fuL4+PjXyvPd5ldkShy1UXcmb4DnjgQj/fd5gDA6/XS\nYCAwTwh9oT3QzrS1+VDVi+vd3Tsy26yQVoFF3dAXJVmK96p9EJ0iLNOwKKU3CQCk0+lSOpP5WLDz\nF9Q9kZqyO0SloOs6gMfbHSU5NLRiUOuax2/HyZPHEOsLw2SbP83eu/fLxrkNp9P554XxCzVa16MC\n7+BPnTk9cfmH74KJE8nmga7Xy5JkZ8VKifGIHpoBb1VX8hNTd3/t/7lQ3OeXfFPvf/jBRw8ezD/a\n7M/aWq91cGgnJaZ2VcgSdnV1XRNNd3vAoBVVYusmnEQS65hfgSG6c+zy3Kre7nF/KrukcMW0Zg8O\nD08DoJutDxxOEb5IPUymwrq8ft1gLKfkFojkkRxemERCAQUACPFWRazYLJcrFGwQhyufbQQ7rFpy\nLMkCwGZC34qPIuwp+XPOjBFwazQ/txrdFS2GGS/Xuj+pUKLGk1Kjvlded3s72lyGW+PLbGVcmrAA\ngN0wTk1NWYODg9XOKltGtpazi5GigzroUnHN5nUHG1ylRsG7rDXHmnEpu4CeEtEKkqNc6QqlLc/M\n8uT5lLH5eq0aGxsju1O7GQB498a5s/0x9dRALPaQEDZnYwnhWJtMCCNrjeb0UP34Z6e/PW22zjPP\n+vwXBwfPvbw38XnXjk7GsiwKAIQQhjAMMrlsam45d+zLH6/8o6vkWcBcrXbVKQhf6bpucCwLjmUB\nSmmhXC419eblrbD/TAgAkUjE987xE0c7ZDmk66ajUCnq+cL63fErl25s5/8baQPaWLhx6goAAAAA\nSUVORK5CYII=",
    sidecar_files: ["api.json"],
  };
}


export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = legacyCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  interface ExecMetadataInfo extends Required<Pick<MetadataHostArgs, "file_path" | "customargs">> {
    user_agent: LegacyUserAgent;
    user_agent_cookies?: LegacyCookie[];
  }
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as unknown as ExecMetadataInfo;
  const [addextra, addother, addsource] = lrr_info.customargs as [boolean, boolean, string];
  let logger = legacyCompat.getLogger("Chaika.moe api.json", "plugins");
  let newtags = "";
  let newtitle = "";
  let path_in_archive = (hostArgs.sidecar_files as Record<string, string> | undefined)?.["api.json"];
  if (path_in_archive) {
    let filepath = path_in_archive;
    [newtags, newtitle] = tags_from_file(filepath, addextra, addother, addsource);
  }
  if (newtags === "") {
    let message = "No Chaika File Found!";
    logger.info(message);
    throw new PluginErrorException(message);
  } else {
    logger.info(`Sending the following tags to LRR: ${newtags}`);
    return { tags: newtags, title: newtitle };
  }
}

function tags_from_file(...args: any[]) {
  let [filepath, addextra, addother, addsource] = args.slice(0);
  let logger = legacyCompat.getLogger("Chaika.moe api.json", "plugins");
  let stringjson = "";
  let fh = filepath;
  if (fh === undefined) { throw new PluginErrorException("Could not open file", { filepath }); }
  for (let row of (fh ?? "").split(/\r?\n/)) {
    row = legacyCompat.chomp(row);
    stringjson += row;
  }
  ;
  let hashjson = JSON.parse(stringjson);
  return parse_chaika_json(hashjson, addextra, addother, addsource);
}

function parse_chaika_json(...args: any[]) {
  let [json, addextra, addother, addsource] = args.slice(0);
  let tags = json["tags"] || [];
  for (let tag of tags) {
    (tag = tag.replace(/_/g, " "));
    if (addother && tag.indexOf(":") == -1) {
      tag = "other:" + tag;
    }
  }
  let category = json["category"].toLowerCase();
  let download = json["download"] ? json["download"] : json["archives"][0]["link"];
  let gallery = json["gallery"] ? json["gallery"] : json["id"];
  let timestamp = json["posted"];
  if (tags && addextra) {
    if (category !== "") {
      tags.push("category:" + category);
    }
    if (download !== "") {
      tags.push("download:" + download);
    }
    if (gallery !== "") {
      tags.push("gallery:" + gallery);
    }
    if (timestamp !== "") {
      tags.push("timestamp:" + timestamp);
    }
  }
  if (gallery && gallery !== "") {
    if (addsource && addsource !== "") {
      tags.push("source:" + addsource);
    }
    return [tags.join(', '), json["title"]];
  } else {
    return "";
  }
}
