// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/Chaika.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - =~ with /g in list context 
//     (/https?:\/\/panda\.chaika\.moe\/(gallery|archive)\/([0-9]*)\/?.*/) — Perl returns every 
//     captured group across all matches; JS .match() with /g returns only full-match strings, not 
//     captures. Verify this call site by hand.
//   - =~ with /g in list context (/.*language:\s?english,*.*/gi) — Perl returns every captured 
//     group across all matches; JS .match() with /g returns only full-match strings, not captures. 
//     Verify this call site by hand.
//   - external Perl module reference has no JS equivalent: Mojo::UserAgent
//
// Hand-fixed: the converter originally bound all 4 declared parameters to the same single
// `hostArgs.arg` value (a since-fixed host-side limitation) — now reads the real per-parameter
// values from `hostArgs.customargs`, positionally matching `pluginInfo().parameters`.
//
// NOTE: this plugin makes HTTP calls but declared_permissions.net is still the
// converter's placeholder — fill in the real host(s), verified against the URL
// literals in the original Perl source, before this plugin can actually reach them
// (Deno's --allow-net grant is scoped to exactly this list).

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    /** Mojo::Message's real `is_error` — true for any 4xx/5xx HTTP status
     * (`~/LANraragi/lib/LANraragi/Plugin/Metadata/Chaika.pm:161`'s `$res->is_error`). */
    is_error: boolean;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

export function pluginInfo() {
  return {
    namespace: "trabant",
    type: "metadata" as const,
    parameters: [
      { name: "param1", description: "Add the following tags if available: download URL, gallery ID, category, timestamp", required: false },
      { name: "param2", description: "Add tags without a namespace to the 'other:' namespace instead, mirroring E-H's behavior of namespacing everything", required: false },
      { name: "param3", description: "Add a custom 'source:' tag to your archive. Example: chaika. Will NOT add a tag if blank", required: false },
      { name: "param4", description: "Save the original title when available instead of the English or romanised title", required: false },
    ],
    // Verified against every URL literal this plugin's own execMetadata actually calls — all
    // three real API calls (`get_json_from_chaika`/`search_for_archive`) hit `panda.chaika.moe`
    // (see `chaika_url` below), no other host.
    declared_permissions: { net: ["panda.chaika.moe"], read: false, write: false },
    name: "Chaika.moe",
    author: "thelastfantasy",
    description: "Searches chaika.moe for tags matching your archive. This will try to use the thumbnail first, and fallback to a default text search.",
    version: "2.4",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA\nB3RJTUUH4wYCFQocjU4r+QAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUH\nAAAEZElEQVQ4y42T3WtTdxzGn/M7J+fk5SRpTk7TxMZkXU84tTbVNrUT3YxO7HA4pdtQZDe7cgx2\ns8vBRvEPsOwFYTDYGJUpbDI2wV04cGXCGFLonIu1L2ptmtrmxeb1JDkvv121ZKVze66f74eH7/f5\nMmjRwMCAwrt4/9KDpflMJpPHvyiR2DPcJklJ3TRDDa0xk36cvrm8vDwHAAwAqKrqjjwXecPG205w\nHBuqa9rk77/d/qJYLD7cCht5deQIIczbgiAEKLVAKXWUiqVV06Tf35q8dYVJJBJem2A7Kwi2nQzD\nZig1CG93+PO5/KN6tf5NKpVqbsBUVVVFUUxwHJc1TXNBoxojS7IbhrnLMMx9pVJlBqFQKBKPxwcB\nkJYgjKIo3QCE1nSKoghbfJuKRqN2RVXexMaQzWaLezyeEUEQDjscjk78PxFFUYRkMsltJgGA3t7e\nyMLCwie6rr8iCILVbDbvMgwzYRjGxe0o4XC4s1AoHPP5fMP5/NNOyzLKAO6Ew+HrDADBbre/Ryk9\nnzx81FXJNlEpVpF+OqtpWu2MpmnXWmH9/f2umZmZi4cOHXnLbILLzOchhz1YerJAs9m1GwRAg2GY\nh7GYah488BJYzYW+2BD61AFBlmX/1nSNRqN9//792ujoaIPVRMjOKHoie3DytVGmp2fXCAEAjuMm\nu7u7Umosho6gjL/u/QHeEgvJZHJ2K/D+/fuL4+PjXyvPd5ldkShy1UXcmb4DnjgQj/fd5gDA6/XS\nYCAwTwh9oT3QzrS1+VDVi+vd3Tsy26yQVoFF3dAXJVmK96p9EJ0iLNOwKKU3CQCk0+lSOpP5WLDz\nF9Q9kZqyO0SloOs6gMfbHSU5NLRiUOuax2/HyZPHEOsLw2SbP83eu/fLxrkNp9P554XxCzVa16MC\n7+BPnTk9cfmH74KJE8nmga7Xy5JkZ8VKifGIHpoBb1VX8hNTd3/t/7lQ3OeXfFPvf/jBRw8ezD/a\n7M/aWq91cGgnJaZ2VcgSdnV1XRNNd3vAoBVVYusmnEQS65hfgSG6c+zy3Kre7nF/KrukcMW0Zg8O\nD08DoJutDxxOEb5IPUymwrq8ft1gLKfkFojkkRxemERCAQUACPFWRazYLJcrFGwQhyufbQQ7rFpy\nLMkCwGZC34qPIuwp+XPOjBFwazQ/txrdFS2GGS/Xuj+pUKLGk1Kjvlded3s72lyGW+PLbGVcmrAA\ngN0wTk1NWYODg9XOKltGtpazi5GigzroUnHN5nUHG1ylRsG7rDXHmnEpu4CeEtEKkqNc6QqlLc/M\n8uT5lLH5eq0aGxsju1O7GQB498a5s/0x9dRALPaQEDZnYwnhWJtMCCNrjeb0UP34Z6e/PW22zjPP\n+vwXBwfPvbw38XnXjk7GsiwKAIQQhjAMMrlsam45d+zLH6/8o6vkWcBcrXbVKQhf6bpucCwLjmUB\nSmmhXC419eblrbD/TAgAkUjE987xE0c7ZDmk66ajUCnq+cL63fErl25s5/8baQPaWLhx6goAAAAA\nSUVORK5CYII=",
    oneshot_arg: "Chaika Gallery or Archive URL (Will attach matching tags to your archive)",
    url_pattern: "chaika\\.moe",
  };
}

const chaika_url = "https://panda.chaika.moe";

/** The shape of one Chaika API "galleries" entry actually read by `parse_chaika_json` — every
 * other field the real API returns is ignored, so this is deliberately narrow rather than a full
 * schema. */
interface ChaikaGallery {
  tags?: string[];
  category: string;
  download?: string;
  archives?: { link: string }[];
  gallery?: string | number;
  id?: string | number;
  posted?: string | number;
  title: string;
  title_jpn?: string;
}

export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = perlCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  interface ExecMetadataInfo {
    user_agent: PerlUserAgent;
    user_agent_cookies?: { name: string; value: string; domain: string; path: string }[];
    arg?: string;
    thumbnail_hash: string;
    archive_title: string;
    existing_tags: string;
    customargs: string[];
  }
  let match: RegExpMatchArray | null;
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as unknown as ExecMetadataInfo;
  //# Global info hash
  let [addextra, addother, addsource, jpntitle] = lrr_info.customargs;
  //# Plugin parameters
  let logger = perlCompat.getLogger("Chaika.moe", "plugins");
  let newtags = "";
  let newtitle = "";
  //    # Parse the given link to see if we can extract type and ID

  // Each of these three lookup functions returns `""` (nothing usable found) or a real
  // `[tags, title]` pair — never applying array destructuring directly to a bare `""` result,
  // which would silently produce `undefined`/`undefined` rather than the empty string
  // `newtags`/`newtitle` start as (and the `newtags === ""` checks below rely on).
  function apply_result(result: [string, string] | "") {
    if (result !== "") {
      [newtags, newtitle] = result;
    }
  }

  let oneshotarg = lrr_info["arg"] ?? "";
  if ((match = oneshotarg.match(/https?:\/\/panda\.chaika\.moe\/(gallery|archive)\/([0-9]*)\/?.*/))) {
    apply_result(await tags_from_chaika_id(match[1], match[2], addextra, addother, addsource, jpntitle));
  } else {
    //        # Try SHA-1 reverse search first

    logger.info("Using thumbnail hash " + lrr_info["thumbnail_hash"]);
    apply_result(await tags_from_sha1(lrr_info["thumbnail_hash"], addextra, addother, addsource, jpntitle));
    //        # Try text search if it fails

    if (newtags === "") {
      logger.info("No results, falling back to text search.");
      apply_result(await search_for_archive(lrr_info["archive_title"], lrr_info["existing_tags"], addextra, addother, addsource, jpntitle));
    }
  }
  if (newtags === "") {
    let message = "No matching Chaika Archive Found!";
    logger.info(message);
    throw new Error(`${message}\n`);
  } else {
    logger.info(`Sending the following tags to LRR: ${newtags}`);
    //        #Return a hash containing the new metadata
  
    return { tags: newtags, title: newtitle };
  }
}

/** Uses Chaika's HTML search to find a matching archive by title/tags. */
async function search_for_archive(
  title: string,
  tags: string,
  addextra: string,
  addother: string,
  addsource: string,
  jpntitle: string,
): Promise<[string, string] | ""> {
  let logger = perlCompat.getLogger("Chaika.moe", "plugins");
  // Auto-lowercase the title for better results, and strip hyphens/apostrophes (they apparently
  // break search).
  title = title.toLowerCase().replace(/-|'/g, " ");
  let URL = `${chaika_url}/jsearch/?gsp&title=` + encodeURIComponent(title) + "&tags=";
  // Append language:english tag, if it exists — Chaika only has english or japanese so this
  // doesn't bother detecting anything more granular.
  if (tags.match(/language:\s?english/i)) {
    URL = URL + encodeURIComponent("language:english") + "+";
  }
  logger.debug(`Calling ${URL}`);
  let ua = perlCompat.userAgent();
  let res = (await ua.get(URL)).result;
  logger.debug(`Chaika API returned this JSON: ${res.body}`);
  const galleries = (res.json as { galleries: ChaikaGallery[] }).galleries;
  return parse_chaika_json(galleries[0], addextra, addother, addsource, jpntitle);
}

/** Uses the jsearch API to get the best JSON match for a gallery/archive URL's type+ID. */
async function tags_from_chaika_id(
  type: string,
  ID: string,
  addextra: string,
  addother: string,
  addsource: string,
  jpntitle: string,
): Promise<[string, string] | ""> {
  let json = await get_json_from_chaika(type, ID);
  return parse_chaika_json(json as ChaikaGallery, addextra, addother, addsource, jpntitle);
}

/** Uses Chaika's SHA-1 search with the first page hash we have — the jsearch API immediately
 * returns a JSON array containing multiple archive objects; only the first one is used. */
async function tags_from_sha1(
  sha1: string,
  addextra: string,
  addother: string,
  addsource: string,
  jpntitle: string,
): Promise<[string, string] | ""> {
  let json_by_sha1 = await get_json_from_chaika('sha1', sha1);
  return parse_chaika_json((json_by_sha1 as ChaikaGallery[])[0], addextra, addother, addsource, jpntitle);
}

/** Calls Chaika's own jsearch API — `undefined` on an HTTP error response (mirrors legacy's own
 * bare `return;`; every caller passes this straight to `parse_chaika_json` without checking, same
 * as legacy, which would itself just die trying to dereference an undef there). */
async function get_json_from_chaika(type: string, value: string): Promise<unknown> {
  let logger = perlCompat.getLogger("Chaika.moe", "plugins");
  let URL = `${chaika_url}/jsearch/?${type}=${value}`;
  let ua = perlCompat.userAgent();
  let res = (await ua.get(URL)).result;
  if (res.is_error) {
    return undefined;
  }
  logger.debug(`Chaika API returned this JSON: ${res.body}`);
  return res.json;
}

/** Parses one Chaika gallery JSON object into `(tags, title)` — `""` if no `gallery`/`id` was
 * present (nothing usable to attach to the archive). */
function parse_chaika_json(
  json: ChaikaGallery,
  addextra: string,
  addother: string,
  addsource: string,
  jpntitle: string,
): [string, string] | "" {
  let tags = json.tags ?? [];
  tags = tags.map((tag) => {
    // Replace underscores with spaces, and add the 'other' namespace if none is present.
    tag = tag.replace(/_/g, " ");
    if (addother && tag.indexOf(":") === -1) {
      tag = "other:" + tag;
    }
    return tag;
  });
  let category = json.category.toLowerCase();
  let download = json.download ? json.download : json.archives?.[0]?.link;
  let gallery = json.gallery ?? json.id;
  let timestamp = json.posted;
  if (tags.length > 0 && addextra) {
    if (category !== "") {
      tags.push("category:" + category);
    }
    if (download) {
      tags.push("download:" + download);
    }
    if (gallery) {
      tags.push("gallery:" + gallery);
    }
    if (timestamp) {
      tags.push("timestamp:" + timestamp);
    }
  }
  if (gallery) {
    // Add custom source, but only if having found gallery.
    if (addsource && addsource !== "") {
      tags.push("source:" + addsource);
    }
    let title = jpntitle ? json.title_jpn : json.title;
    if (title === "" && jpntitle) {
      title = json.title;
    }
    return [tags.join(', '), title ?? ""];
  } else {
    return "";
  }
}
