// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/ComicInfo.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - external Perl module reference has no JS equivalent: Mojo::DOM

export function pluginInfo() {
  return {
    namespace: "comicinfo",
    type: "metadata" as const,
    parameters: [
    ],
    declared_permissions: { net: [], read: false, write: true },
    name: "ComicInfo",
    author: "thelastfantasy",
    description: "Parses metadata from ComicInfo.xml embedded in the archive",
    version: "0.1",
    sidecar_files: ["ComicInfo.xml"],
  };
}


export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = legacyCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  interface ExecMetadataInfo extends Required<Pick<MetadataHostArgs, "file_path">> {
    user_agent: LegacyUserAgent;
    user_agent_cookies?: LegacyCookie[];
  }
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as unknown as ExecMetadataInfo;
  let logger = legacyCompat.getLogger("ComicInfo", "plugins");
  let file = lrr_info["file_path"];
  let path_in_archive = (hostArgs.sidecar_files as Record<string, string> | undefined)?.["ComicInfo.xml"];
  if ((! path_in_archive)) { throw new PluginErrorException("No ComicInfo.xml file found in the archive"); }
  let filepath = path_in_archive;
  let stringxml = "";
  let fh = filepath;
  if (fh === undefined) { throw new PluginErrorException("Could not open file", { filepath }); }
  for (let line of (fh ?? "").split(/\r?\n/)) {
    line = legacyCompat.chomp(line);
    stringxml += line;
  }
  let genre = undefined;
  let calibretags = undefined;
  let group = undefined;
  let url = undefined;
  let artist = undefined;
  let lang = undefined;
  let title = undefined;
  let series = undefined;
  let character = undefined;
  let publisher = undefined;
  let result = legacyCompat.parseHtml(stringxml, true).at('Genre');
  if ((result !== undefined && result !== null)) {
    genre = result.text;
  }
  result = legacyCompat.parseHtml(stringxml, true).at('Tags');
  if ((result !== undefined && result !== null)) {
    calibretags = result.text;
  }
  result = legacyCompat.parseHtml(stringxml, true).at('Characters');
  if ((result !== undefined && result !== null)) {
    character = result.text;
  }
  result = legacyCompat.parseHtml(stringxml, true).at('Web');
  if ((result !== undefined && result !== null)) {
    url = result.text;
  }
  result = legacyCompat.parseHtml(stringxml, true).at('Writer');
  if ((result !== undefined && result !== null)) {
    group = result.text;
  }
  result = legacyCompat.parseHtml(stringxml, true).at('Penciller');
  if ((result !== undefined && result !== null)) {
    artist = result.text;
  }
  result = legacyCompat.parseHtml(stringxml, true).at('LanguageISO');
  if ((result !== undefined && result !== null)) {
    lang = result.text;
  }
  result = legacyCompat.parseHtml(stringxml, true).at('Title');
  if ((result !== undefined && result !== null)) {
    title = result.text;
  }
  result = legacyCompat.parseHtml(stringxml, true).at('Series');
  if ((result !== undefined && result !== null)) {
    series = result.text;
  }
  result = legacyCompat.parseHtml(stringxml, true).at('Publisher');
  if ((result !== undefined && result !== null)) {
    publisher = result.text;
  }
  ;
  let found_tags = [] as any[];
  found_tags = try_add_tags(found_tags, "group:", group);
  found_tags = try_add_tags(found_tags, "artist:", artist);
  found_tags = try_add_tags(found_tags, "source:", url);
  found_tags = try_add_tags(found_tags, "series:", series);
  found_tags = try_add_tags(found_tags, "character:", character);
  found_tags = try_add_tags(found_tags, "publisher:", publisher);
  if (!(! lang)) { found_tags.push("language:" + lang); }
  let genres = (genre ?? "").split(',');
  if (calibretags) {
    genres.push(calibretags.split(','));
  }
  for (let genre_tag of genres) {
    found_tags.push(legacyCompat.trim(genre_tag));
  }
  let tags = found_tags.join(", ");
  logger.info(`Sending the following tags to LRR: ${tags}`);
  return { tags: tags, title: title };
}

function try_add_tags(...args: any[]) {
  let found_tags = args[0];
  let prefix = args[1];
  let tags = args[2] ?? "";
  let tags_array = tags.split(',');
  for (let tag of tags_array) {
    found_tags.push(prefix + legacyCompat.trim(tag));
  }
  return found_tags;
}
