// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/CopyArchiveTags.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Hand-fixed since regeneration:
//   - `LANraragi::Utils::Database::get_tags` (another archive's stored tags, looked up by ID) has
//     no JS equivalent from inside the Deno sandbox — the host now resolves it and passes it
//     through as `hostArgs.other_archive_tags` (`crates/lanrurugi-api/src/plugins.rs::
//     get_other_archive_tags`), the same pattern already used for `file_path`/`settings`.
//   - `split_tags_to_array`/`join_tags_to_string` (`LANraragi::Utils::Tags`) are trivial
//     string<->array helpers — reimplemented directly below rather than needing host support.
//   - legacy's `$params->{oneshot}` reflects a `to_named_params`-specific host convention this SDK
//     doesn't replicate — the oneshot value is just this call's own `arg`.
//   - `$params->{'copy_date_added'}` is this plugin's one declared parameter, positionally bound
//     to `customargs[0]`.

/** LRR's own archive ID format (a SHA-1 hex digest) — matches
 * `~/LANraragi/lib/LANraragi/Plugin/Metadata/CopyArchiveTags.pm::extract_archive_id`. */
const ARCHIVE_ID_PATTERN = /([0-9a-f]{40,})/;
const ARCHIVE_ID_LEN = 40;
const DATE_ADDED_NAMESPACE_PATTERN = /date_added/;

export function pluginInfo() {
  return {
    namespace: "copy-archive-tags",
    type: "metadata" as const,
    parameters: [
      { name: "copy_date_added", description: "Enable to also copy the date (but it's up to you to remove the old one)", required: false, type: "bool" },
    ],
    declared_permissions: { net: [], read: false, write: false },
    name: "Copy Archive Tags",
    author: "thelastfantasy",
    description: "Copy tags from another LRR archive given either the URI or the ID.",
    version: "0.1",
    oneshot_arg: "LRR Gallery URL or ID:",
  };
}

interface ExecMetadataInfo extends Required<Pick<MetadataHostArgs, "archive_id" | "arg" | "customargs" | "other_archive_tags">> {
  user_agent: LegacyUserAgent;
  user_agent_cookies?: LegacyCookie[];
}

export async function execMetadata(hostArgs: Record<string, unknown>) {
  const lrr_info = hostArgs as unknown as ExecMetadataInfo;
  const logger = legacyCompat.getLogger("Copy Archive Tags", "plugins");

  const lrr_gid = extract_archive_id(lrr_info.arg);
  if (!lrr_gid) {
    throw new PluginErrorException("oneshot_param doesn't contain a valid archive ID");
  }
  if (lrr_gid === lrr_info.archive_id) {
    throw new PluginErrorException("You are using the current archive ID");
  }

  logger.info(`Copying tags from archive "${lrr_gid}"`);
  let tags = lrr_info.other_archive_tags ?? "";

  const copy_date_added = lrr_info.customargs?.[0];
  if (!copy_date_added) {
    const tagArray = split_tags_to_array(tags);
    tags = join_tags_to_string(tagArray.filter((tag) => !DATE_ADDED_NAMESPACE_PATTERN.test(tag)));
  }

  logger.info("Sending the following tags to LRR: " + (tags || "-"));
  return { tags: tags || "" };
}

function extract_archive_id(oneshot: string | undefined): string | undefined {
  if (!oneshot || oneshot.length < ARCHIVE_ID_LEN) return undefined;
  const match = oneshot.toLowerCase().match(ARCHIVE_ID_PATTERN);
  if (match && match[1].length === ARCHIVE_ID_LEN) {
    return match[1];
  }
  return undefined;
}

function split_tags_to_array(tagsString: string): string[] {
  return tagsString.split(",").map((tag) => tag.trim());
}

function join_tags_to_string(tags: string[]): string {
  return tags.join(",");
}
