// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/CopyArchiveTags.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-09.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - external Perl module reference has no JS equivalent: LANraragi::Utils::Database::get_tags

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

export function pluginInfo() {
  return {
    namespace: "copy-archive-tags",
    type: "metadata" as const,
    parameters: [
      { name: "copy_date_added", description: "Enable to also copy the date (but it's up to you to remove the old one)", required: false },
    ],
    declared_permissions: { net: [], read: false, write: false },
    name: "Copy Archive Tags",
    author: "IceBreeze (ported)",
    description: "Copy tags from another LRR archive given either the URI or the ID.",
    version: "1.2",
    oneshot_arg: "LRR Gallery URL or ID:",
  };
}


export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = perlCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as Record<string, any>;
  let params = hostArgs.arg as string;
  let logger = perlCompat.getLogger("Copy Archive Tags", "plugins");
  let lrr_gid = extract_archive_id(params["oneshot"]);
  if (! lrr_gid) {
    throw new Error("oneshot_param doesn't contain a valid archive ID\n");
  }
  if (lrr_gid === lrr_info['archive_id']) {
    throw new Error("You are using the current archive ID\n");
  }
  logger.info(`Copying tags from archive \"${lrr_gid}\"`);
  let tags = LANraragi_Utils_Database_get_tags(lrr_gid) || '';
  if (! params['copy_date_added']) {
    let tags = split_tags_to_array(tags);
    tags = join_tags_to_string(tags.filter((it) => (! /date_added/.test(it))));
  }
  logger.info("Sending the following tags to LRR: " + (tags || '-'));
  return { tags: tags || '' };
}

function extract_archive_id(...args: any[]) {
  let match: RegExpMatchArray | null;
  let [oneshot] = args.slice(0);
  if ((! oneshot || oneshot.length < 40)) { return; }
  if ((match = (oneshot.toLowerCase()).match(/([0-9a-f]{40,})/))) {
    if (match[1].length == 40) { return match[1]; }
  }
  return;
}
