// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/CopyArchiveTags.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Hand-fixed since regeneration:
//   - `LANraragi::Utils::Database::get_tags` (another archive's stored tags, looked up by ID) has
//     no JS equivalent from inside the Deno sandbox — the host now resolves it and passes it
//     through as `hostArgs.other_archive_tags` (`crates/lanrurugi-api/src/plugins.rs::
//     get_other_archive_tags`), the same pattern already used for `file_path`/`settings`.
//   - `split_tags_to_array`/`join_tags_to_string` (`LANraragi::Utils::Tags`) are trivial
//     string<->array helpers — reimplemented directly below rather than needing host support.
//   - legacy's `$params->{oneshot}` reflects a `to_named_params`-specific host convention this SDK
//     doesn't replicate — the oneshot value is just this call's own `arg`.
//   - `$params->{'copy_date_added'}` is this plugin's one declared parameter, positionally bound
//     to `customargs[0]`.

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

// Mirrors `crates/lanrurugi-plugin/dispatcher/plugin-sdk.ts`'s `PluginErrorException` — defined
// locally (not imported) since a plugin file is loaded via a standalone `import()` with no
// relative-path relationship to the SDK file, and the dispatcher's catch block detects this by
// property shape (`error_code`/`data` on a thrown `Error`), not `instanceof`, for exactly that
// reason (see `dispatcher.ts`'s own comment on this). `error_code` is an i18n lookup key — write
// it as a natural, stable phrase that does not embed any dynamic value (that goes in `data`
// instead), so the same `error_code` translates regardless of which specific value triggered it.
class PluginErrorException extends Error {
  constructor(
    public error_code: string,
    public data?: Record<string, string | number>,
  ) {
    super(error_code);
  }
}

/** LRR's own archive ID format (a SHA-1 hex digest) — matches
 * `~/LANraragi/lib/LANraragi/Plugin/Metadata/CopyArchiveTags.pm::extract_archive_id`. */
const ARCHIVE_ID_PATTERN = /([0-9a-f]{40,})/;
const ARCHIVE_ID_LEN = 40;
const DATE_ADDED_NAMESPACE_PATTERN = /date_added/;

export function pluginInfo() {
  return {
    namespace: "copy-archive-tags",
    type: "metadata" as const,
    parameters: [
      { name: "copy_date_added", description: "Enable to also copy the date (but it's up to you to remove the old one)", required: false, type: "bool" },
    ],
    declared_permissions: { net: [], read: false, write: false },
    name: "Copy Archive Tags",
    author: "thelastfantasy",
    description: "Copy tags from another LRR archive given either the URI or the ID.",
    version: "0.1",
    oneshot_arg: "LRR Gallery URL or ID:",
  };
}

interface ExecMetadataInfo {
  archive_id?: string;
  arg?: string;
  customargs: string[];
  other_archive_tags?: string | null;
}

export async function execMetadata(hostArgs: Record<string, unknown>) {
  const lrr_info = hostArgs as unknown as ExecMetadataInfo;
  const logger = perlCompat.getLogger("Copy Archive Tags", "plugins");

  const lrr_gid = extract_archive_id(lrr_info.arg);
  if (!lrr_gid) {
    throw new PluginErrorException("oneshot_param doesn't contain a valid archive ID");
  }
  if (lrr_gid === lrr_info.archive_id) {
    throw new PluginErrorException("You are using the current archive ID");
  }

  logger.info(`Copying tags from archive "${lrr_gid}"`);
  let tags = lrr_info.other_archive_tags ?? "";

  const copy_date_added = lrr_info.customargs?.[0];
  if (!copy_date_added) {
    const tagArray = split_tags_to_array(tags);
    tags = join_tags_to_string(tagArray.filter((tag) => !DATE_ADDED_NAMESPACE_PATTERN.test(tag)));
  }

  logger.info("Sending the following tags to LRR: " + (tags || "-"));
  return { tags: tags || "" };
}

function extract_archive_id(oneshot: string | undefined): string | undefined {
  if (!oneshot || oneshot.length < ARCHIVE_ID_LEN) return undefined;
  const match = oneshot.toLowerCase().match(ARCHIVE_ID_PATTERN);
  if (match && match[1].length === ARCHIVE_ID_LEN) {
    return match[1];
  }
  return undefined;
}

function split_tags_to_array(tagsString: string): string[] {
  return tagsString.split(",").map((tag) => tag.trim());
}

function join_tags_to_string(tags: string[]): string {
  return tags.join(",");
}
