// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/DateAdded.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Hand-fixed since regeneration:
//   - `LANraragi::Model::Config->use_lastmodified` (the global "Use 'Last modified' Time"
//     setting) has no JS equivalent in scope — the host now resolves this (and its sibling
//     `usedateadded`) itself and passes both through as `hostArgs.settings`
//     (`crates/lanrurugi-api/src/plugins.rs::get_plugin_relevant_settings`), rather than this
//     plugin needing its own round trip back into the settings API.
//   - `date_modified($file)` (a plain `stat` for the archive's on-disk mtime) similarly has no JS
//     equivalent that doesn't require this plugin its own filesystem read permission — the host
//     resolves it as `hostArgs.file_modified_time` alongside `file_path` itself.
//   - `time()` (Perl's current-Unix-timestamp builtin) is just `Date.now() / 1000` in JS.

export function pluginInfo() {
  return {
    namespace: "DateAddedPlugin",
    type: "metadata" as const,
    parameters: [],
    declared_permissions: { net: [], read: false, write: false },
    name: "Add Timestamp Tag",
    author: "thelastfantasy",
    description: "Adds a timestamp tag to your archive. <br> This plugin follows the server settings for the timestamp tag and will use file modification time if the server setting is set to 'Use Last modified Time'.",
    version: "0.1",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA\nB3RJTUUH4wYCFQY4HfiAJAAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUH\nAAADKUlEQVQ4y6WVsUtrVxzHP+fmkkiqJr2CQWKkvCTwJgkJDpmyVAR1cVOhdq04tHNB7BD8A97S\nXYkO3dRRsMSlFoIOLYFEohiDiiTNNeaGpLn5dRDv06ev75V+4SyH8/2c3/n+zuEoEeFTqtfrb5RS\nJZ/P98m1iMirI5fLMT8/L+FwWEKhkIRCIXn79q2srKxIpVL5qE/7cINms8ny8rIkEgkpl8skk0lm\nZ2eZmZkhHo+TzWYJBoOyvr4u7Xb7RYHq6ZEvLi6Ynp6WVqvFwsIC4+PjRCIRDMNAKcXNzQ2lUols\nNsvOzg6xWIxMJqOeRuEAq9UqqVRKhoaGmJubY2pqCl3XiUajXF5e0t/fz+DgIIVCAbfbzdbWFtvb\n24yMjLC/v6+eZWjbNqurq5JIJGRtbU0syxLbtsU0TXmqXq8njUZDRERubm4knU6LYRiSyWScDBER\nGo0G4XBYFhcX5fz8XP4yTbGLf0hnd0s+plqtJru7u7K0tCSRSEQ6nc77ppycnFCv10kmk4yOjoII\n2kiIv3//lfbGu1dvh1KKVCrF2NgYmqaRy2UAHoCHh4f4fD4mJiZwuVz4fT74YhDvTz/TPv2TX378\ngWKx+Azo9/sZGBhAKYVhGBSLxa8doGmaABiGQT6fp9VqPbg0jcr897w7+I3FxUVs23aAlmVxe3tL\nPB7n/v6eWq22D6A/lq+UotlsEo1G8Xg8jvFNOMzCN99iGF/icrmc+b6+PrxeL2enp7hcLpR6aLT+\nuEDTNEqlErFYDMuy8Hq9AHg8HpaXv3uRYbfbRdM0TNNE096/Dweo6zoHBwfE43F0XXeAjyf4UJVK\nhUql8iwGJ8NHeb1e9vb2CAaDADQajRcgy7IACAQCHB0d/TtQ0zQuLi7Y3Nzk+vqacrkMwNXVFXd3\nd7Tbbc7Ozuh0OmxsbHB1dfViQ/21+3V8fIxpmkxOTmKaJrZt0263sW0b27ZJp9M0m010XX8RhwN8\nNPV6PQCKxSL5fB7DMAgEAnS7XarVKtVqFbfbjVIK27ZRSjkeB9jtdikUChQKBf6vlIg4Gb3Wzc/V\n8PDwV36//1x9zhfwX/QPryPQMvGWTdEAAAAASUVORK5CYII=",
    oneshot_arg: "Use file modified time (yes/true), or use current time (no/false). <br/>Leaving blank uses the server setting (default: current time)",
  };
}

export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = legacyCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  interface ExecMetadataInfo extends Required<Pick<MetadataHostArgs, "file_path" | "file_modified_time" | "settings" | "arg">> {
    user_agent: LegacyUserAgent;
    user_agent_cookies?: LegacyCookie[];
  }
  let lrr_info = hostArgs as unknown as ExecMetadataInfo;
  // Server setting — same field this plugin's `oneshot_arg` lets a one-off run override, per
  // legacy's own `$oneshotarg =~ /^(yes|true)$/i` / `/^(no|false)$/i` checks below.
  let use_filetime = lrr_info.settings?.usedatemodified ?? false;

  let logger = legacyCompat.getLogger("Date Added Plugin", "plugins");
  logger.debug("Processing file: " + lrr_info["file_path"]);
  let newtags = "";
  let oneshotarg = lrr_info["arg"] ?? "";
  let oneshot_file_time = /^(yes|true)$/i.test(oneshotarg);
  let oneshot_current_time = /^(no|false)$/i.test(oneshotarg);
  if (oneshot_file_time || (use_filetime && !oneshot_current_time)) {
    logger.info("Using file date");
    const fileTime = lrr_info.file_modified_time ?? Math.floor(Date.now() / 1000);
    newtags = "date_added:" + fileTime;
  } else {
    logger.info("Using current date");
    newtags = "date_added:" + Math.floor(Date.now() / 1000);
  }
  return { tags: newtags };
}
