// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/EHDLInfo.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-09.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - =~ with /g in list context (/^> ([a-z]*):(.*)/gi) — Perl returns every captured group across 
//     all matches; JS .match() with /g returns only full-match strings, not captures. Verify this 
//     call site by hand.
//   - =~ with /g in list context (/^([a-z]*):(.*)/g) — Perl returns every captured group across all 
//     matches; JS .match() with /g returns only full-match strings, not captures. Verify this call 
//     site by hand.
//   - =~ with /g in list context (/^Category: (.*)/) — Perl returns every captured group across all 
//     matches; JS .match() with /g returns only full-match strings, not captures. Verify this call 
//     site by hand.
//   - =~ with /g in list context (/^(description|title)\:(.*)/g) — Perl returns every captured 
//     group across all matches; JS .match() with /g returns only full-match strings, not captures. 
//     Verify this call site by hand.
//   - =~ with /g in list context (/^https\:\/\/(e.hentai\.org\/g\/[0-9]*\/[0-z]*)\/*.*/gi) — Perl 
//     returns every captured group across all matches; JS .match() with /g returns only full-match 
//     strings, not captures. Verify this call site by hand.
//   - =~ with /g in list context (/^Language: ([a-z]*)/i) — Perl returns every captured group 
//     across all matches; JS .match() with /g returns only full-match strings, not captures. Verify 
//     this call site by hand.
//   - =~ with /g in list context (/^Tags:/) — Perl returns every captured group across all matches; 
//     JS .match() with /g returns only full-match strings, not captures. Verify this call site by 
//     hand.
//   - external Perl module reference has no JS equivalent: Time::Piece
//   - this plugin declares 3 custom parameters, but the host currently passes only one generic 
//     `arg` value per call — only `replace_title` was mapped to it; the rest were also bound to 
//     that same value and need manual attention before this plugin can work correctly

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

export function pluginInfo() {
  return {
    namespace: "ehd-info",
    type: "metadata" as const,
    parameters: [
      { name: "replace_title", description: "Replace the title with the one in the metadata file", required: false },
      { name: "japanese_title", description: "Use Japanese title if available", required: false },
      { name: "save_summary", description: "Save \"description\" as summary", required: false },
    ],
    declared_permissions: { net: [], read: false, write: false },
    name: "EHDL info.txt",
    author: "IceBreeze (ported)",
    description: "EHDL info.txt metadata parser",
    version: "1.0",
    sidecar_files: ["info.txt"],
  };
}

let metadata_file = "info.txt";
let S_INFO = 1;
let S_TAGS = 2;
let S_FLAT = 3;

export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = perlCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  let lrr_info = hostArgs as Record<string, any>;
  let params = hostArgs.arg as string;
  let logger = perlCompat.getLogger("EHDL info.txt", "plugins");
  let archive = lrr_info["file_path"];
  let hashdata = {} as Record<string, any>;
  if ((hostArgs.sidecar_files as Record<string, string> | undefined)?.[metadata_file]) {
    hashdata = read_file(metadata_file, params);
    if (! params['replace_title']) {
      delete hashdata['title'];
    }
    if (! params['save_summary']) {
      delete hashdata['summary'];
    }
    logger.info("Sending the following tags to LRR: " + hashdata["tags"]);
  }
  return hashdata;
}

function read_file(...args: any[]) {
  let match: RegExpMatchArray | null;
  let [metafile, params] = args.slice(0);
  let fh = metafile;
  if (fh === undefined) { throw new Error(`Could not open ${metafile}!\n`); }
  let hashdata = {} as Record<string, any>;
  let tags = {} as Record<string, any>;
  let count = 0;
  let reading_section = S_INFO;
  for (let line of (fh ?? "").split(/\r?\n/)) {
    line = perlCompat.trim(line);
    if (! line) {
      count ++;
      continue;
    } else if (count == 0) {
      //            # try guessing the file format
    
      if ((match = line.match(/^(description|title)\:(.*)/g))) {
        let ns = (match[1] === 'title') ? 'title' : 'summary';
        hashdata[ns] = perlCompat.trim(match[2]);
        reading_section = S_FLAT;
      } else {
        hashdata['title'] = line;
      }
    } else if (reading_section == S_INFO && count == 1 && params['japanese_title']) {
      hashdata['title'] = line;
      //# expecting the original title
    } else if (reading_section == S_INFO && count == 2) {
      //            # if this isn't the gallery URL, then the file format is unknown
    
      if ((match = line.match(/^https\:\/\/(e.hentai\.org\/g\/[0-9]*\/[0-z]*)\/*.*/gi))) {
        tags['source'] = match[1];
      } else {
        ;
        ;
        throw new Error("Unknown file format");
      }
    } else if (reading_section == S_INFO) {
      if ((match = line.match(/^Category: (.*)/))) {
        tags['category'] = perlCompat.trim(match[1]);
      } else if ((match = line.match(/^Posted: (.*)/))) {
        tags['timestamp'] = convert_to_epoch(perlCompat.trim(match[1]));
      } else if ((match = line.match(/^Language: ([a-z]*)/i))) {
        tags['language'] = match[1].toLowerCase();
      } else if ((match = line.match(/^Tags:/))) {
        reading_section = S_TAGS;
      }
    } else if (reading_section == S_TAGS) {
      if ((match = line.match(/^> ([a-z]*):(.*)/gi))) {
        tags[match[1]] = [split_tags_to_array(match[2])];
      } else {
        break;
        //# nothing useful anymore
      }
    } else if (reading_section == S_FLAT) {
      if ((match = line.match(/^([a-z]*):(.*)/g))) {
        let ns = match[1];
        let value = perlCompat.trim(match[2]);
        if ((tags[ns] !== undefined)) {
          tags[ns].push(value);
        } else if (match[1] === 'title') {
          hashdata['title'] = perlCompat.trim(match[2]);
        } else if (match[1] === 'description') {
          hashdata['summary'] = perlCompat.trim(match[2]);
        } else {
          tags[ns] = [value];
        }
      }
    }
    count ++;
  }
  ;
  ;
  hashdata['tags'] = hash_to_array(tags).join(',');
  return hashdata;
}

function hash_to_array(...args: any[]) {
  let [hash_tags] = args.slice(0);
  let array = [] as any[];
  for (const [ns, value] of Object.entries(hash_tags ?? {})) {
    if (! value) {
      array.push(ns);
    } else if (ns === 'tag') {
      array.push(value.join(','));
    } else if (perlCompat.refType(value) === 'ARRAY') {
      for (const it of value) { array.push(`${ns}:${_}`); }
    } else {
      array.push(`${ns}:${value}`);
    }
  }
  array = [...array].sort();
  return array;
}

function convert_to_epoch(...args: any[]) {
  let [datetime] = args.slice(0);
  return Time_Piece.strptime(datetime, "%Y-%m-%d %H:%M").epoch;
}
