// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/EHDLInfo.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Hand-fixed since regeneration:
//   - the converter's `/g`-flag warnings were false alarms for every site but one: `.match()`
//     without the `g` flag already returns `[fullMatch, group1, group2, ...]` in JS, matching
//     Perl's own `=~ /.../ ` list-context captures exactly — so the fix was to drop the stray `g`
//     flag the converter carried over from the Perl source (which Perl needs for iteration but JS
//     doesn't), not to add extra verification.
//   - `split_tags_to_array` (`LANraragi::Utils::Tags`) is a trivial helper — reimplemented below.
//   - `Time::Piece->strptime(...)->epoch` — reimplemented via a small `YYYY-MM-DD HH:MM` parser
//     (the one format this plugin ever produces, per `Posted: ` lines from EH-Downloader's own
//     `info.txt` output) using `Date.UTC`.
//   - this plugin declares 3 real parameters (`replace_title`, `japanese_title`, `save_summary`),
//     positionally bound to `customargs[0..2]` — the converter had only wired one generic `arg`
//     value.

const METADATA_FILE = "info.txt";

/** `read_file`'s little state machine over `info.txt`'s lines — mirrors the real EH-Downloader
 * output format: a free-text header block (`S_INFO`), then a `Tags:` section listing
 * `> namespace:value` lines (`S_TAGS`), OR (for a differently-shaped info.txt) a flat
 * `namespace:value` line format (`S_FLAT`) detected from the very first line. */
const enum ReadingSection {
  Info = 1,
  Tags = 2,
  Flat = 3,
}

const TITLE_OR_DESCRIPTION_LINE = /^(description|title):(.*)/;
const GALLERY_URL_LINE = /^https:\/\/(e.hentai\.org\/g\/[0-9]*\/[0-z]*)\/*.*/i;
const CATEGORY_LINE = /^Category: (.*)/;
const POSTED_LINE = /^Posted: (.*)/;
const LANGUAGE_LINE = /^Language: ([a-z]*)/i;
const TAGS_HEADER_LINE = /^Tags:/;
const TAG_ENTRY_LINE = /^> ([a-z]*):(.*)/i;
const FLAT_NAMESPACE_LINE = /^([a-z]*):(.*)/;

interface ParsedInfoTxt {
  title?: string;
  summary?: string;
  tags: string;
}

type TagValue = string | string[];

export function pluginInfo() {
  return {
    namespace: "ehd-info",
    type: "metadata" as const,
    parameters: [
      { name: "replace_title", description: "Replace the title with the one in the metadata file", required: false, type: "bool" },
      { name: "japanese_title", description: "Use Japanese title if available", required: false, type: "bool" },
      { name: "save_summary", description: "Save \"description\" as summary", required: false, type: "bool" },
    ],
    declared_permissions: { net: [], read: false, write: true },
    name: "EHDL info.txt",
    author: "thelastfantasy",
    description: "EHDL info.txt metadata parser",
    version: "0.1",
    sidecar_files: ["info.txt"],
  };
}

interface EhdInfoParams {
  replace_title: boolean;
  japanese_title: boolean;
  save_summary: boolean;
}

export async function execMetadata(hostArgs: Record<string, unknown>) {
  const logger = legacyCompat.getLogger("EHDL info.txt", "plugins");
  const customargs = (hostArgs.customargs as string[] | undefined) ?? [];
  const params: EhdInfoParams = {
    replace_title: !!customargs[0],
    japanese_title: !!customargs[1],
    save_summary: !!customargs[2],
  };

  const sidecarFiles = hostArgs.sidecar_files as Record<string, string> | undefined;
  const fileContents = sidecarFiles?.[METADATA_FILE];
  if (!fileContents) {
    return {};
  }

  const hashdata = read_file(fileContents, params);
  if (!params.replace_title) delete hashdata.title;
  if (!params.save_summary) delete hashdata.summary;

  logger.info("Sending the following tags to LRR: " + hashdata.tags);
  return hashdata;
}

function read_file(fileContents: string, params: EhdInfoParams): ParsedInfoTxt {
  const hashdata: { title?: string; summary?: string } = {};
  const tags: Record<string, TagValue> = {};
  let count = 0;
  let reading_section: ReadingSection = ReadingSection.Info;

  for (const rawLine of fileContents.split(/\r?\n/)) {
    const line = legacyCompat.trim(rawLine);
    let match: RegExpMatchArray | null;

    if (!line) {
      count++;
      continue;
    } else if (count === 0) {
      // try guessing the file format
      if ((match = line.match(TITLE_OR_DESCRIPTION_LINE))) {
        const ns = match[1] === "title" ? "title" : "summary";
        hashdata[ns] = legacyCompat.trim(match[2]);
        reading_section = ReadingSection.Flat;
      } else {
        hashdata.title = line;
      }
    } else if (reading_section === ReadingSection.Info && count === 1 && params.japanese_title) {
      hashdata.title = line; // expecting the original title
    } else if (reading_section === ReadingSection.Info && count === 2) {
      // if this isn't the gallery URL, then the file format is unknown
      if ((match = line.match(GALLERY_URL_LINE))) {
        tags.source = match[1];
      } else {
        throw new PluginErrorException("Unknown file format");
      }
    } else if (reading_section === ReadingSection.Info) {
      if ((match = line.match(CATEGORY_LINE))) {
        tags.category = legacyCompat.trim(match[1]);
      } else if ((match = line.match(POSTED_LINE))) {
        tags.timestamp = String(convert_to_epoch(legacyCompat.trim(match[1])));
      } else if ((match = line.match(LANGUAGE_LINE))) {
        tags.language = match[1].toLowerCase();
      } else if (TAGS_HEADER_LINE.test(line)) {
        reading_section = ReadingSection.Tags;
      }
    } else if (reading_section === ReadingSection.Tags) {
      if ((match = line.match(TAG_ENTRY_LINE))) {
        tags[match[1]] = split_tags_to_array(match[2]);
      } else {
        break; // nothing useful anymore
      }
    } else if (reading_section === ReadingSection.Flat) {
      if ((match = line.match(FLAT_NAMESPACE_LINE))) {
        const ns = match[1];
        const value = legacyCompat.trim(match[2]);
        const existing = tags[ns];
        if (existing !== undefined) {
          (existing as string[]).push(value);
        } else if (ns === "title") {
          hashdata.title = value;
        } else if (ns === "description") {
          hashdata.summary = value;
        } else {
          tags[ns] = [value];
        }
      }
    }
    count++;
  }

  return { ...hashdata, tags: hash_to_array(tags).join(",") };
}

function hash_to_array(hash_tags: Record<string, TagValue>): string[] {
  const array: string[] = [];
  for (const [ns, value] of Object.entries(hash_tags)) {
    if (!value) {
      array.push(ns);
    } else if (ns === "tag") {
      array.push((value as string[]).join(","));
    } else if (Array.isArray(value)) {
      for (const it of value) array.push(`${ns}:${it}`);
    } else {
      array.push(`${ns}:${value}`);
    }
  }
  return array.sort();
}

function convert_to_epoch(datetime: string): number {
  const match = datetime.match(/^(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2})$/);
  if (!match) return 0;
  const [, year, month, day, hour, minute] = match;
  return Date.UTC(Number(year), Number(month) - 1, Number(day), Number(hour), Number(minute)) / 1000;
}

function split_tags_to_array(tagsString: string): string[] {
  return tagsString.split(",").map((tag) => legacyCompat.trim(tag));
}
