// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/EHentai.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - =~ with /g in list context (/\[([0-9]+)\]/g) — Perl returns every captured group across all 
//     matches; JS .match() with /g returns only full-match strings, not captures. Verify this call 
//     site by hand.
//   - =~ with /g in list context (/.*artist:\s?([^,]*),*.*/gi) — Perl returns every captured group 
//     across all matches; JS .match() with /g returns only full-match strings, not captures. Verify 
//     this call site by hand.
//   - =~ with /g in list context (/.*\/g\/([0-9]*)\/([0-z]*)\/*.*/) — Perl returns every captured 
//     group across all matches; JS .match() with /g returns only full-match strings, not captures. 
//     Verify this call site by hand.
//   - =~ with /g in list context 
//     (/.*source:\s*(?:https?:\/\/)?e(?:x|-)hentai\.org\/g\/([0-9]*)\/([0-z]*)\/*.*/gi) — Perl 
//     returns every captured group across all matches; JS .match() with /g returns only full-match 
//     strings, not captures. Verify this call site by hand.
//
// Hand-fixed: the converter originally bound all 7 declared parameters to the same single
// `hostArgs.arg` value (a since-fixed host-side limitation) — now reads the real per-parameter
// values from `hostArgs.customargs`, positionally matching `pluginInfo().parameters`.
//
// NOTE: this plugin makes HTTP calls but declared_permissions.net is still the
// converter's placeholder — fill in the real host(s), verified against the URL
// literals in the original Perl source, before this plugin can actually reach them
// (Deno's --allow-net grant is scoped to exactly this list).

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

export function pluginInfo() {
  return {
    namespace: "ehplugin",
    type: "metadata" as const,
    parameters: [
      { name: "param1", description: "Forced language to use in searches (Japanese won't work due to EH limitations)", required: false },
      { name: "param2", description: "Fetch using thumbnail first (falls back to title)", required: false },
      { name: "param3", description: "Search using gID from title (falls back to title)", required: false },
      { name: "param4", description: "Use ExHentai (enable to search for fjorded content without star cookie)", required: false },
      { name: "param5", description: "Save the original title when available instead of the English or romanised title", required: false },
      { name: "param6", description: "Fetch additional timestamp (time posted) and uploader metadata", required: false },
      { name: "param7", description: "Search only expunged galleries", required: false },
    ],
    // Verified against every URL literal this plugin's own execMetadata actually calls: the
    // gallery page itself (e-hentai.org, or exhentai.org when the "Use ExHentai" parameter is
    // enabled) plus the JSON API (api.e-hentai.org, used by the timestamp/uploader-metadata
    // lookup and the tag-fetch fallback).
    declared_permissions: { net: ["e-hentai.org", "exhentai.org", "api.e-hentai.org"], read: false, write: false },
    name: "E-Hentai",
    author: "thelastfantasy",
    description: "Searches g.e-hentai for tags matching your archive. <br/><i class='fa fa-exclamation-circle'></i> This plugin will use the source: tag of the archive if it exists.",
    version: "2.6",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABmJLR0QA/wD/AP+gvaeTAAAACXBI\nWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4wYBFg0JvyFIYgAAAB1pVFh0Q29tbWVudAAAAAAAQ3Jl\nYXRlZCB3aXRoIEdJTVBkLmUHAAAEo0lEQVQ4y02UPWhT7RvGf8/5yMkxMU2NKaYIFtKAHxWloYNU\ncRDeQTsUFPwAFwUHByu4ODq4Oghdiri8UIrooCC0Lx01ONSKfYOioi1WpWmaxtTm5PTkfNzv0H/D\n/9oeePjdPNd13Y8aHR2VR48eEUURpmmiaRqmaXbOAK7r4vs+IsLk5CSTk5P4vo9hGIgIsViMra0t\nCoUCRi6XY8+ePVSrVTRN61yybZuXL1/y7t078vk8mUyGvXv3cuLECWZnZ1lbW6PdbpNIJHAcB8uy\nePr0KYZlWTSbTRKJBLquo5TCMAwmJia4f/8+Sini8Ti1Wo0oikin09i2TbPZJJPJUK/XefDgAefO\nnWNlZQVD0zSUUvi+TxAE6LqOrut8/fqVTCaDbdvkcjk0TSOdTrOysoLrujiOw+bmJmEYMjAwQLVa\nJZVKYXR1ddFut/F9H9M0MU0T3/dZXV3FdV36+/vp7u7m6NGj7Nq1i0qlwuLiIqVSib6+Pubn5wGw\nbZtYLIaxMymVSuH7PpZlEUURSina7TZBEOD7Pp8/fyYMQ3zfZ25ujv3795NOp3n48CE9PT3ouk4Q\nBBi/fv3Ctm0cx6Grq4utrS26u7sREQzDIIoifv78SU9PD5VKhTAMGRoaYnV1leHhYa5evUoQBIRh\niIigiQhRFKHrOs1mE9u2iaKIkydPYhgGAKZp8v79e+LxOPl8Htd1uXbtGrdv3yYMQ3ZyAODFixeb\nrVZLvn//Lq7rSqVSkfX1dREROXz4sBw/flyUUjI6OipXrlyRQ4cOSbPZlCiKxHVdCcNQHMcRz/PE\ndV0BGL53756sra1JrVaT9fV1cRxHRESGhoakr69PUqmUvHr1SsrlsuzI931ptVriuq78+fNHPM+T\nVqslhoikjh075p09e9ba6aKu6/T39zM4OMjS0hIzMzM0Gg12794N0LEIwPd9YrEYrusShiEK4Nmz\nZ41yudyVy+XI5/MMDAyQzWap1+tks1lEhIWFBQqFArZto5QiCAJc1+14t7m5STweRwOo1WoSBAEj\nIyMUi0WSySQiQiqV6lRoYWGhY3673e7sfRAEiAjZbBbHcbaBb9++5cCBA2SzWZLJJLZt43kesViM\nHX379g1d1wnDsNNVEQEgCAIajQZ3797dBi4tLWGaJq7rYpompVKJmZkZ2u12B3j58mWUUmiahoiw\nsbFBEASdD2VsbIwnT55gACil+PHjB7Ozs0xPT/P7929u3ryJZVmEYUgYhhQKBZRSiAie52EYBkop\nLMvi8ePHTE1NUSwWt0OZn5/3hoeHzRs3bqhcLseXL1+YmJjowGzbRtO07RT/F8jO09+8ecP58+dJ\nJBKcPn0abW5uThWLRevOnTv/Li4u8vr1a3p7e9E0jXg8zsePHymVSnz69Kmzr7quY9s2U1NTXLp0\nCc/zOHLkCPv27UPxf6rX63+NjIz8IyKMj48zPT3NwYMHGRwcpLe3FwARodVqcf36dS5evMj4+DhB\nEHDmzBkymQz6DqxSqZDNZr8tLy//DYzdunWL5eVlqtUqHz58IJVKkUwmaTQalMtlLly4gIjw/Plz\nTp06RT6fZ2Njg/8AqMV7tO07rnsAAAAASUVORK5CYII=",
    oneshot_arg: "E-H Gallery URL (Will attach tags matching this exact gallery to your archive)",
    login_from: "ehlogin",
    url_pattern: "e-?hentai\\.org|exhentai\\.org",
  };
}


export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = perlCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  interface ExecMetadataInfo {
    user_agent: PerlUserAgent;
    user_agent_cookies?: { name: string; value: string; domain: string; path: string }[];
    arg?: string;
    existing_tags: string;
    archive_title: string;
    thumbnail_hash: string;
    customargs: string[];
  }
  let match: RegExpMatchArray | null;
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as unknown as ExecMetadataInfo;
  //# Global info hash
  let ua = lrr_info["user_agent"];
  let [lang, usethumbs, search_gid, enablepanda, jpntitle, additionaltags, expunged] =
    lrr_info.customargs;
  //# Plugin parameters
  //    # Use the logger to output status - they'll be passed to a specialized logfile and written to STDOUT.

  let logger = perlCompat.getLogger("E-Hentai", "plugins");
  //    # Work your magic here - You can create subroutines below to organize the code better

  let gID = "";
  let gToken = "";
  let domain = (enablepanda ? 'https://exhentai.org' : 'https://e-hentai.org');
  let hasSrc = 0;
  //    # Quick regex to get the E-H archive ids from the provided url or source tag

  if ((match = (lrr_info["arg"] ?? "").match(/.*\/g\/([0-9]*)\/([0-z]*)\/*.*/))) {
    gID = match[1];
    gToken = match[2];
    logger.debug(`Skipping search and using gallery ${gID} / ${gToken} from oneshot args`);
  } else if ((match = lrr_info["existing_tags"].match(/.*source:\s*(?:https?:\/\/)?e(?:x|-)hentai\.org\/g\/([0-9]*)\/([0-z]*)\/*.*/gi))) {
    gID = match[1];
    gToken = match[2];
    hasSrc = 1;
    logger.debug(`Skipping search and using gallery ${gID} / ${gToken} from source tag`);
  } else {
    //        # Craft URL for Text Search on EH if there's no user argument
  
    try {
      [gID, gToken] = await lookup_gallery(lrr_info["archive_title"], lrr_info["existing_tags"], lrr_info["thumbnail_hash"], ua, domain, lang, usethumbs, search_gid, expunged);
    } catch (e: any) {
      logger.error(e);
      throw new Error(e);
    }
  }
  if (gID === "") {
    let message = "No matching EH Gallery Found!";
    logger.info(message);
    throw new Error(`${message}\n`);
  } else {
    logger.debug(`EH API Tokens are ${gID} / ${gToken}`);
  }
  let [ehtags, ehtitle] = await get_tags_from_EH(ua, gID, gToken, jpntitle, additionaltags);
  let hashdata: Record<string, any> = { tags: ehtags };
  //    # Add source URL and title if possible/applicable

  if (hashdata["tags"] !== "") {
    if (! hasSrc) {
      hashdata["tags"] += ", source:" + (domain.split('://')) [1] + `/g/${gID}/${gToken}`;
    }
    hashdata["title"] = ehtitle;
  }
  //    #Return a hash containing the new metadata - it will be integrated in LRR.

  return hashdata;
}

async function lookup_gallery(title: any, tags: any, thumbhash: any, ua: any, domain: any, defaultlanguage: any, usethumbs: any, search_gid: any, expunged: any) {
  let match: RegExpMatchArray | null;
  let logger = perlCompat.getLogger("E-Hentai", "plugins");
  let URL = "";
  //    #Thumbnail reverse image search

  if (thumbhash !== "" && usethumbs) {
    logger.info("Reverse Image Search Enabled, trying now.");
    //        #search with image SHA hash
  
    URL = domain + "?f_shash=" + thumbhash + "&fs_similar=on&fs_covers=on";
    logger.debug(`Using URL ${URL} (archive thumbnail hash)`);
    let [gId, gToken] = await ehentai_parse(URL, ua);
    if (gId !== "" && gToken !== "") {
      return [gId, gToken];
    }
  }
  //    # Search using gID if present in title name

  let [title_gid] = (match = title.match(/\[([0-9]+)\]/g));
  if (search_gid && title_gid) {
    URL = domain + "?f_search=" + encodeURIComponent(`gid:${title_gid}`);
    logger.debug(`Found gID: ${title_gid}, Using URL ${URL} (gID from archive title)`);
    let [gId, gToken] = await ehentai_parse(URL, ua);
    if (gId !== "" && gToken !== "") {
      return [gId, gToken];
    }
  }
  //    # Regular text search (advanced options: Disable default filters for: Language, Uploader, Tags)

  URL = domain + "?advsearch=1&f_sfu=on&f_sft=on&f_sfl=on" + "&f_search=" + encodeURIComponent("\"" + title + "\"");
  let has_artist = 0;
  //    # Add artist tag from the OG tags if it exists (and only contains ASCII characters)

  if ((match = tags.match(/.*artist:\s?([^,]*),*.*/gi))) {
    let artist = match[1];
    if ((match = artist.match(/^[\x00-\x7F]*$/))) {
      URL = URL + "+" + encodeURIComponent(`artist:${artist}`);
      has_artist = 1;
    }
  }
  //    # Add the language override, if it's defined.

  if (defaultlanguage !== "") {
    URL = URL + "+" + encodeURIComponent(`language:${defaultlanguage}`);
  }
  //    # Search expunged galleries if the option is enabled.

  if (expunged) {
    URL = URL + "&f_sh=on";
  }
  logger.debug(`Using URL ${URL} (archive title)`);
  return await ehentai_parse(URL, ua);
}

async function ehentai_parse(url: any, ua: any) {
  let logger = perlCompat.getLogger("E-Hentai", "plugins");
  let dom = await search_gallery(url, ua);
  //    # Get the first row of the search results

  //    # The "glink" class is parented by a <a> tag containing the gallery link in href.

  //    # This works in Minimal, Minimal+ and Compact modes, which should be enough.

  let glink_element = dom.at(".glink");
  if (! glink_element) {
    logger.debug("No gallery found in search results");
    return ["", ""];
  }
  let firstgal = glink_element.parent.attr('href');
  //    # A EH link looks like xhentai.org/g/{gallery id}/{gallery token}

  url = (firstgal.split('hentai.org/g/')) [1];
  let [gID, gToken] = (url.split('/'));
  if (dom.toString().indexOf("You are opening") != -1) {
    let rand = 15 + Math.trunc((Math.random() * 51 - 15));
    logger.info(`Sleeping for ${rand} seconds due to EH excessive requests warning`);
    await perlCompat.sleep(rand);
  }
  //    #Returning shit yo

  return [gID, gToken];
}

async function search_gallery(url: any, ua: any) {
  let logger = perlCompat.getLogger("E-Hentai", "plugins");
  let res = (await ua.max_redirects(5).get(url)).result;
  if (res.body.indexOf("Your IP address has been") != -1) {
    throw new Error("Temporarily banned from EH for excessive pageloads.\n");
  }
  return res.dom;
}

async function get_tags_from_EH(ua: any, gID: any, gToken: any, jpntitle: any, additionaltags: any) {
  let uri = 'https://api.e-hentai.org/api.php';
  let logger = perlCompat.getLogger("E-Hentai", "plugins");
  let jsonresponse = await get_json_from_EH(ua, gID, gToken);
  let data = jsonresponse["gmetadata"];
  let tags = data[0]["tags"];
  let ehtitle = data[0][(jpntitle ? "title_jpn" : "title")];
  if (ehtitle === "" && jpntitle) {
    ehtitle = data[0]["title"];
  }
  let ehcat = data[0]["category"].toLowerCase();
  tags.push(`category:${ehcat}`);
  if (additionaltags) {
    let ehuploader = data[0]["uploader"];
    let ehtimestamp = data[0]["posted"];
    tags.push(`uploader:${ehuploader}`);
    tags.push(`timestamp:${ehtimestamp}`);
  }
  //    # Unescape title received from the API as it might contain some HTML characters

  ehtitle = perlCompat.htmlUnescape(ehtitle);
  let ehtags = tags.join(', ');
  logger.info(`Sending the following tags to LRR: ${ehtags}`);
  return [ehtags, ehtitle];
}

async function get_json_from_EH(ua: any, gID: any, gToken: any) {
  let uri = 'https://api.e-hentai.org/api.php';
  let logger = perlCompat.getLogger("E-Hentai", "plugins");
  //    #Execute the request

  let rep = (await ua.post(uri, "json", {method: "gdata", gidlist: [[gID, gToken]], namespace: 1})).result;
  let textrep = rep.body;
  logger.debug(`E-H API returned this JSON: ${textrep}`);
  let jsonresponse = rep.json;
  if ((jsonresponse["error"] !== undefined)) {
    logger.error(jsonresponse["error"]);
    throw new Error("E-H API returned an error.\n");
  }
  return jsonresponse;
}
