// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/Eze.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-09.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - file-test operator -e always evaluates to false — this host never gives plugins real 
//     filesystem access outside the current archive
//   - this plugin declares 2 custom parameters, but the host currently passes only one generic 
//     `arg` value per call — only `param1` was mapped to it; the rest were also bound to that same 
//     value and need manual attention before this plugin can work correctly

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

export function pluginInfo() {
  return {
    namespace: "ezeplugin",
    type: "metadata" as const,
    parameters: [
      { name: "param1", description: "Save the original title when available instead of the English or romanised title", required: false },
      { name: "param2", description: "Fetch additional timestamp (time posted) and uploader metadata", required: false },
    ],
    declared_permissions: { net: [], read: false, write: false },
    name: "eze",
    author: "Difegue (ported)",
    description: "Collects metadata from eze-style info.json files ({'gallery_info': {xxx} } syntax), either embedded in your archive or in the same folder with the same name. ({archive_name}.json)",
    version: "2.4",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA\nB3RJTUUH4wYCFDYBnHlU6AAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUH\nAAAETUlEQVQ4y22UTWhTWRTHf/d9JHmNJLFpShMcKoRIqxXE4sKpjgthYLCLggU/wI1CUWRUxlmU\nWblw20WZMlJc1yKKKCjCdDdYuqgRiygq2mL8aJpmQot5uabv3XdnUftG0bu593AOv3M45/yvGBgY\n4OrVqwRBgG3bGIaBbduhDSClxPM8tNZMTEwwMTGB53lYloXWmkgkwqdPnygUCljZbJbW1lYqlQqG\nYYRBjuNw9+5dHj16RD6fJ51O09bWxt69e5mammJ5eZm1tTXi8Tiu6xKNRrlx4wZWNBqlXq8Tj8cx\nTRMhBJZlMT4+zuXLlxFCEIvFqFarBEFAKpXCcRzq9TrpdJparcbIyAiHDh1icXERyzAMhBB4nofv\n+5imiWmavHr1inQ6jeM4ZLNZDMMglUqxuLiIlBLXdfn48SNKKXp6eqhUKiQSCaxkMsna2hqe52Hb\nNsMdec3n8+Pn2+vpETt37qSlpYVyucz8/DzT09Ns3bqVYrEIgOM4RCIRrI1MiUQCz/P43vE8jxcv\nXqCUwvM8Zmdn2bJlC6lUitHRUdrb2zFNE9/3sd6/f4/jOLiuSzKZDCH1wV/EzMwM3d3dNN69o729\nnXK5jFKKPXv2sLS0RF9fHydOnMD3fZRSaK0xtNYEQYBpmtTr9RC4b98+LMsCwLZtHj9+TCwWI5/P\nI6Xk5MmTXLhwAaUUG3MA4M6dOzQaDd68eYOUkqHIZj0U2ay11mzfvp1du3YhhGBgYIDjx4/T3d1N\nvV4nCAKklCilcF2XZrOJlBIBcOnSJc6ePYsQgj9yBf1l//7OJcXPH1Y1wK/Ff8SfvT995R9d/SA8\nzyMaja5Xq7Xm1q1bLCwssLS09M1Atm3bFr67urq+8W8oRUqJlBJLCMHNmze5d+8e2Ww2DPyrsSxq\ntRqZTAattZibm6PZbHJFVoUQgtOxtAbwfR8A13WJxWIYANVqFd/36e/v/ypzIpEgCAKEEMzNzYXN\n34CN/FsSvu+jtSaTyeC67jrw4cOHdHZ2kslkQmCz2SQSiYT269evMU0zhF2RVaH1ejt932dlZYXh\n4eF14MLCArZtI6UMAb+1/qBPx9L6jNOmAY4dO/b/agBnnDb9e1un3vhQzp8/z/Xr19eBQgjevn3L\n1NTUd5WilKJQKGAYxje+lpYWrl27xuTk5PqKARSLRfr6+hgaGiKbzfLy5UvGx8dRSqGUwnEcDMNA\nKYUQIlRGNBplZmaGw4cPE4/HOXDgAMbs7Cy9vb1cvHiR+fl5Hjx4QC6XwzAMYrEYz549Y3p6mufP\nn4d6NU0Tx3GYnJzk6NGjNJtNduzYQUdHB+LL8mu1Gv39/WitGRsb4/79+3R1dbF7925yuVw4/Uaj\nwalTpzhy5AhjY2P4vs/BgwdJp9OYG7ByuUwmk6FUKgFw7tw5SqUSlUqFp0+fkkgk2LRpEysrKzx5\n8oTBwUG01ty+fZv9+/eTz+dZXV3lP31rAEu+yXjEAAAAAElFTkSuQmCC",
    sidecar_files: ["info.json"],
  };
}


export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = perlCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as Record<string, any>;
  //# Global info hash
  let origin_title = hostArgs.arg as string;
  let additional_tags = hostArgs.arg as string;
  //# Plugin parameters
  let logger = perlCompat.getLogger("eze", "plugins");
  let path_in_archive = (hostArgs.sidecar_files as Record<string, string> | undefined)?.["info.json"];
  let [name, path, suffix] = perlCompat.fileparse(lrr_info["file_path"]);
  let path_nearby_json = create_path(path + name + '.json');
  let filepath = undefined;
  let delete_after_parse = undefined;
  //    #Extract info.json

  if (path_in_archive) {
    filepath = path_in_archive;
    logger.debug(`Found file in archive at ${filepath}`);
    delete_after_parse = 1;
  } else if (false) {
    filepath = path_nearby_json;
    logger.debug(`Found file nearby at ${filepath}`);
    delete_after_parse = 0;
  } else {
    throw new Error("No in-archive info.json or {archive_name}.json file found!\n");
  }
  //    #Open it

  let stringjson = "";
  let fh = filepath;
  if (fh === undefined) { throw new Error("Could not open the requested file."); }
  for (let row of (fh ?? "").split(/\r?\n/)) {
    row = perlCompat.chomp(row);
    stringjson += row;
  }
  //    #Use Mojo::JSON to decode the string into a hash

  let hashjson = JSON.parse(stringjson);
  logger.debug(`Loaded the following JSON: ${stringjson}`);
  if (hashjson["gallery_info"] == undefined) {
    return { error: "The info.json file could not be parsed as an eze file!" };
  }
  //    #Parse it

  let [tags, title] = tags_from_eze_json(origin_title, additional_tags, hashjson);
  if (delete_after_parse) {
    //        #Delete it
  
    ;
  }
  //    #Return tags

  logger.info(`Sending the following tags to LRR: ${tags}`);
  if (title) {
    logger.info(`Parsed title is ${title}`);
    return { tags: tags, title: title };
  } else {
    return { tags: tags };
  }
}

function tags_from_eze_json(...args: any[]) {
  let [origin_title, additional_tags, hash] = args.slice(0);
  let return_ = "";
  //    #Tags are in gallery_info -> tags -> one array per namespace

  let tags = hash["gallery_info"]["tags"];
  //    # Titles returned by eze are in complete E-H notation.

  let title = hash["gallery_info"]["title"];
  if (origin_title && hash["gallery_info"]["title_original"]) {
    title = hash["gallery_info"]["title_original"];
  }
  title = perlCompat.trim(title);
  for (let namespace of Object.keys(tags).sort()) {
    //        # Get the array for this namespace and iterate on it
  
    let members = tags[namespace];
    for (let tag of members) {
      if (!(return_ === "")) { return_ += ", "; }
      return_ += namespace + ":" + tag;
    }
  }
  //    # Add source tag if possible

  let site = hash["gallery_info"]["source"]["site"];
  let gid = hash["gallery_info"]["source"]["gid"];
  let gtoken = hash["gallery_info"]["source"]["token"];
  let category = hash["gallery_info"]["category"];
  let uploader = hash["gallery_info_full"]["uploader"];
  let timestamp = hash["gallery_info_full"]["date_uploaded"];
  if (timestamp) {
    //        # convert microsecond to second
  
    timestamp = timestamp / 1000;
  } else {
    let upload_date = hash["gallery_info"]["upload_date"];
    if (upload_date) {
      let time = timegm_modern(upload_date[5], upload_date[4], upload_date[3], upload_date[2], upload_date[1] - 1, upload_date[0]);
      timestamp = time;
    }
  }
  if (category) {
    return_ += `, category:${category}`;
  }
  if (additional_tags && uploader) {
    return_ += `, uploader:${uploader}`;
  }
  if (additional_tags && timestamp) {
    return_ += `, timestamp:${timestamp}`;
  }
  if (site && gid && gtoken) {
    return_ += `, source:${site}.org/g/${gid}/${gtoken}`;
  }
  //    #Done-o

  return [return_, title];
}
