// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/Fakku.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-09.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - =~ with /g in list context (/.*error code: (\d*).*/gim) — Perl returns every captured group 
//     across all matches; JS .match() with /g returns only full-match strings, not captures. Verify 
//     this call site by hand.
//   - this plugin declares 2 custom parameters, but the host currently passes only one generic 
//     `arg` value per call — only `param1` was mapped to it; the rest were also bound to that same 
//     value and need manual attention before this plugin can work correctly
//   - unsupported regex substitution (recursive subpattern or /x flag): s/\[([^\[\]]|(?0))*]//g
//

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

export function pluginInfo() {
  return {
    namespace: "fakkumetadata",
    type: "metadata" as const,
    parameters: [
      { name: "param1", description: "Add 'Source' tag", required: false },
      { name: "param2", description: "Only use current title for exact matches", required: false },
    ],
    // TODO(perl-convert): source used an HTTP client (Mojo::UserAgent/LWP/etc.) — 
    // fill in the actual host(s) this plugin needs so Deno's --allow-net grant 
    // stays as narrow as possible (constitution Principle IV).
    // Host verified against the only URL literal in the original Perl source
    // (~/LANraragi/lib/LANraragi/Plugin/Metadata/Fakku.pm): `$fakku_host = "https://www.fakku.net"`.
    declared_permissions: { net: ["www.fakku.net"], read: false, write: false },
    name: "FAKKU",
    author: "Difegue, Nodja, Nixis198 (ported)",
    description: "Searches FAKKU for tags matching your archive. If you have an account, don't forget to enter the matching cookie in the login plugin to be able to access controversial content. <br/><br/>\n           <i class='fa fa-exclamation-circle'></i> <b>This plugin can and will return invalid results depending on what you're searching for!</b> <br/>The FAKKU search API isn't very precise and I recommend you either enable 'Only use current title for exact matches', or use the Chaika.moe plugin when possible.",
    version: "1.0.2",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAFiUAABYlAUlSJPAAAACZSURBVDhPlY+xDYQwDEWvZgRGYA22Y4frqJDSZhFugiuuo4cqPGT0iTjAYL3C+fGzktc3hEcsQvJq6HtjE2Jdv4viH4a4pWnL8q4A6g+ET9P8YhS2/kqwIZXWnwqChDxPfCFfD76wOzJ2IOR/0DSwnuRKYAKUW3gq2OsJTYM0jr7QVRVwlabJEaw3ARYBcmFXeomxphIeEMIMmh3lOLQR+QQAAAAASUVORK5CYII=",
    oneshot_arg: "FAKKU Gallery URL (Will attach tags matching this exact gallery to your archive)",
    login_from: "fakkulogin",
  };
}

let fakku_host = "https://www.fakku.net";

export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = perlCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as Record<string, any>;
  //# Global info hash
  let ua = lrr_info["user_agent"];
  let add_source = hostArgs.arg as string;
  let safe_mode = hostArgs.arg as string;
  let logger = perlCompat.getLogger("FAKKU", "plugins");
  //    # Work your magic here - You can create subs below to organize the code better

  if (! fakku_cookie_exists(ua.cookie_jar)) {
    throw new Error("Not logged in to FAKKU! Set your FAKKU SID in the plugin settings page!\n");
  }
  //    # If the user specified a oneshot argument, use it as-is.

  //    # We could stand to pre-check it to see if it really is a FAKKU URL but meh

  let fakku_URL = lrr_info["oneshot_param"];
  //    # No URL? Looks for the "source:" in the existing tags.

  if ((! fakku_URL)) { fakku_URL = get_url_from_tags(lrr_info["existing_tags"]); }
  //    # Assume URLs coming from the one-shot parameter or tags are reliable.

  let URL_safe = ! ! fakku_URL;
  //    # Still nothing? Search for a FAKKU URL using the title

  if ((! fakku_URL)) { fakku_URL = await search_for_fakku_url(lrr_info["archive_title"], ua); }
  //    # Do we have a URL to grab data from?

  if (! fakku_URL) {
    let message = "No matching FAKKU Gallery Found!";
    logger.info(message);
    throw new Error(`${message}\n`);
  }
  logger.debug(`Detected FAKKU URL: ${fakku_URL}`);
  let [newtags, newtitle, newSummary] = await get_tags_from_fakku(fakku_URL, ua, add_source);
  let current_title = lrr_info["archive_title"];
  if (safe_mode && ! URL_safe && newtitle !== current_title) {
    logger.info(`Found FAKKU Gallery '${newtitle}', but it does not match current title '${current_title}' exactly`);
    throw new Error("Exact title match not found\n");
  }
  logger.info(`Sending the following tags to LRR: ${newtags}`);
  //    #Return a hash containing the new metadata - it will be integrated in LRR.

  return { tags: newtags, title: newtitle, summary: newSummary };
}

async function search_for_fakku_url(...args: any[]) {
  let [title, ua] = args.slice(0);
  let dom = await get_search_result_dom(title, ua);
  //    # Get the first link on the page that starts with '/hentai/'

  let path = dom.at('[href^="/hentai/"]').attr('href');
  if (path !== "") {
    return fakku_host + path;
  } else {
    return "";
  }
}

async function get_search_result_dom(...args: any[]) {
  let [title, ua] = args.slice(0);
  let logger = perlCompat.getLogger("FAKKU", "plugins");
  //# Strip away (some) characters that break search

  //# Note: The F! search backend sometimes fails to match you anyway. :/ The autosuggest API would work better but then again, CF issues

  //# * Changed the ' filter to '\w*, meaning instead of just stripping the apostrophe, we also strip whatever is after it ("we're" > "we" instead of "we're" > "were").

  //#      This is because just removing the apostrophe will return wrong (or no) results (to give an example "Were in love" would not return anything, whereas "we in love" would)

  //# * Added @ to the filters, because it's not supported by F*'s search engine either

  //# * Added a space ahead of the - (hyphen) filter, to only remove hyphens directly prepended to something else (those are the only ones that break searches, probably because the search engine treats them as exclusions as most engines would).

  (title = title.replace(/ -|'\w*|~|!|@/g, ""));
  //    # Removes everything inside [ ] as well as the brackets themselves

  title /* TODO(perl-convert): =~ regex match — verify against original */.match (undefined /* TODO(perl-convert): s/\[([^\[\]]|(?0))*]//g */);
  //    # Removes everything inside () as well as the parentheses themselves

  (title = title.replace(/\(.*$/g, ""));
  //    # Visit the base host once to set cloudflare cookies and jank

  ua.max_redirects(5).get(fakku_host);
  //# Use the regular search page.

  //# The autosuggest API (fakku.net/suggest/blahblah) yields better results but is blocked unless you make it through cloudflare or are logged in?

  let URL = `${fakku_host}/search/` + encodeURIComponent(title);
  logger.debug(`Using URL ${URL} to search on FAKKU.`);
  let res = (await ua.max_redirects(5).get(URL)).result;
  //    # $logger->debug( "Got this HTML: " . $res->body );

  return res.dom;
}

async function get_dom_from_fakku(...args: any[]) {
  let match: RegExpMatchArray | null;
  let [url, ua] = args.slice(0);
  let logger = perlCompat.getLogger("FAKKU", "plugins");
  let res = (await ua.max_redirects(5).get(url)).result;
  let html = res.body;
  //    # $logger->debug( "Got this HTML: " . $html );

  if ((match = html.match(/.*error code: (\d*).*/gim))) {
    logger.debug(`Blocked by Cloudflare, aborting for now. (Error code ${1})`);
    throw new Error(`The plugin has been blocked by Cloudflare. (Error code ${1}) Try opening FAKKU in your browser to bypass this.`);
  }
  return res.dom;
}

async function get_tags_from_fakku(...args: any[]) {
  let match: RegExpMatchArray | null;
  let [url, ua, add_url] = args.slice(0);
  let logger = perlCompat.getLogger("FAKKU", "plugins");
  let dom = await get_dom_from_fakku(url, ua);
  //    # find the "suggest more tags" link and use parent div

  //    # this is not ideal, but the divs don't have named classes anymore

  let tags_parent = dom.at('[data-tippy-content="Suggest More Tags"]').parent;
  //    # div that contains other divs with title, namespaced tags (artist, magazine, etc.) and misc tags

  let metadata_parent = tags_parent.parent.parent;
  let title = metadata_parent.at('h1').text;
  title = perlCompat.trim(title);
  logger.debug(`Parsed title: ${title}`);
  let tags = [];
  //    # Finds the DIV for the Summary.

  let summ_selector = 'meta[name="description"]';
  let summ_div = dom.at(summ_selector);
  let summary = undefined;
  //    # # If the Summary DIV doesn't exist, return a blank string.

  if (summ_div) {
    summary = perlCompat.htmlUnescape(summ_div["content"]);
    //        # Sometime if the description has unwanted text.
  
    if ((match = summary.match(/Free sample available now!/))) {
      summary = "";
    }
  } else {
    summary = "";
  }
  //    # If no FAKKU description exists, just keep it blank.

  if (summary === "No description has been written.") {
    summary = "";
  }
  //    # We can grab some namespaced tags from the first few div.

  let namespaces = metadata_parent.children('div').each;
  for (let div of namespaces) {
    let row = div.children.each;
    if ((row.length != 2)) { continue; }
    let namespace = row[0].text;
    logger.debug(`Evaluating row: ${row}[1]`);
    let value = (row[1].at('a')) ? row[1].at('a').text : row[1].text;
    value = perlCompat.trim(value);
    value = trim_CRLF(value);
    //        # for the edgecase if the gallery is in the top 10 of 2 categories
  
    if (value === "in  this month." || value === " in  this month.") {
      continue;
    }
    logger.debug(`Parsed row: ${namespace}`);
    logger.debug(`Matching tag: ${value}`);
    if (!(namespace === "Tags" || namespace === "Pages" || namespace === "Description" || namespace === "Direction" || namespace === "Favorites" || value === "")) {
      tags.push(`${namespace}:${value}`);
    }
  }
  //    # might be worth filtering by links starting with '/tags/*' but that filters out the special "unlimited" tag

  let tag_links = tags_parent.find('a').each;
  for (let link of tag_links) {
    let tag = link.text;
    tag = perlCompat.trim(tag);
    tag = trim_CRLF(tag);
    if (!(tag === "+" || tag === "")) {
      tags.push(tag.toLowerCase());
    }
  }
  //    # Adds the source tag is enabled.

  if (add_url) {
    (url = url.replace(/^https:\/\/www\./i, ""));
    tags.push("source:" + url);
  }
  return [tags.join(', '), title, summary];
}

function fakku_cookie_exists(...args: any[]) {
  let [cookie_jar] = args.slice(0);
  let logger = perlCompat.getLogger("FAKKU", "plugins");
  logger.debug("Checking Cookies");
  let cookies = cookie_jar.all;
  if (cookies) {
    for (let cookie of cookies) {
      if (cookie.name === "fakku_sid") {
        logger.debug("The needed cookie was found.");
        return 1;
      }
    }
    logger.debug("The needed cookie was not found.");
  } else {
    logger.debug("No Cookies were found!");
  }
  return;
}

function get_url_from_tags(...args: any[]) {
  let match: RegExpMatchArray | null;
  let [actual_tags] = args.slice(0);
  if (actual_tags) {
    let tags = actual_tags.split(',');
    let pattern = /^source:(.+)$/;
    for (let tag of tags) {
      if (pattern.test(tag)) {
        let foundURL = match[1];
        if ((match = foundURL.match(/fakku\.net/))) {
          //#Makes sure the found url is a fakku.net url.
          return foundURL;
        }
      }
    }
  }
  return;
}
