// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/Fakku.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Hand-fixed since regeneration:
//   - `.*error code: (\d*).*` needs no `/g`/list-context handling at all — it's only ever tested
//     for a truthy match (Cloudflare block detection), so the stray `/gim` flags were just dropped.
//   - `s/\[([^\[\]]|(?0))*]//g` (a PCRE recursive subpattern — strips one level of nested `[...]`
//     brackets) has no JS regex equivalent (JS regex can't recurse) — reimplemented as
//     `strip_bracketed_runs`, a small explicit bracket-depth scanner.
//   - `get_url_from_tags`: the converter dropped the regex capture entirely (`match[1]` referenced
//     before `match` was ever assigned) — fixed to actually capture and test group 1 of the
//     `^source:(.+)$` pattern, per the real Perl (`$foundURL = $1`).
//   - `trim_CRLF` (`LANraragi::Utils::String`) reimplemented directly (strips all newlines).
//   - `declared_permissions.net`: this plugin only ever calls `fakku_host` (`www.fakku.net`),
//     verified against every URL literal in `execMetadata`'s call graph.

export function pluginInfo() {
  return {
    namespace: "fakkumetadata",
    type: "metadata" as const,
    parameters: [
      { name: "param1", description: "Add 'Source' tag", required: false, type: "bool" },
      { name: "param2", description: "Only use current title for exact matches", required: false, type: "bool" },
    ],
    declared_permissions: { net: ["www.fakku.net"], read: false, write: false },
    name: "FAKKU",
    author: "thelastfantasy",
    description: "Searches FAKKU for tags matching your archive. If you have an account, don't forget to enter the matching cookie in the login plugin to be able to access controversial content. <br/><br/>\n           <i class='fa fa-exclamation-circle'></i> <b>This plugin can and will return invalid results depending on what you're searching for!</b> <br/>The FAKKU search API isn't very precise and I recommend you either enable 'Only use current title for exact matches', or use the Chaika.moe plugin when possible.",
    version: "0.1",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAFiUAABYlAUlSJPAAAACZSURBVDhPlY+xDYQwDEWvZgRGYA22Y4frqJDSZhFugiuuo4cqPGT0iTjAYL3C+fGzktc3hEcsQvJq6HtjE2Jdv4viH4a4pWnL8q4A6g+ET9P8YhS2/kqwIZXWnwqChDxPfCFfD76wOzJ2IOR/0DSwnuRKYAKUW3gq2OsJTYM0jr7QVRVwlabJEaw3ARYBcmFXeomxphIeEMIMmh3lOLQR+QQAAAAASUVORK5CYII=",
    oneshot_arg: "FAKKU Gallery URL (Will attach tags matching this exact gallery to your archive)",
    login_from: "fakkulogin",
  };
}

const FAKKU_HOST = "https://www.fakku.net";
// Strips characters that break FAKKU's search backend (apostrophe-and-following-word, tildes,
// bangs, at-signs, and a hyphen only when directly prepended to something else).
const SEARCH_BREAKING_CHARS_PATTERN = / -|'\w*|~|!|@/g;
const PARENTHETICAL_SUFFIX_PATTERN = /\(.*$/;
const CLOUDFLARE_ERROR_PATTERN = /error code: (\d*)/i;
const FREE_SAMPLE_BLURB_PATTERN = /Free sample available now!/;
const SOURCE_TAG_PATTERN = /^source:(.+)$/;
const FAKKU_URL_PATTERN = /fakku\.net/;
const NO_DESCRIPTION_TEXT = "No description has been written.";
const DUPLICATE_TOP_TEN_TEXT = ["in  this month.", " in  this month."];
const SKIPPED_NAMESPACES = ["Tags", "Pages", "Description", "Direction", "Favorites"];

export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = legacyCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  interface ExecMetadataInfo extends Required<Pick<MetadataHostArgs, "arg" | "existing_tags" | "archive_title" | "customargs">> {
    user_agent: LegacyUserAgent;
    user_agent_cookies?: LegacyCookie[];
  }
  const lrr_info = hostArgs as unknown as ExecMetadataInfo;
  const ua = lrr_info.user_agent;
  const [add_source, safe_mode] = lrr_info.customargs;
  const logger = legacyCompat.getLogger("FAKKU", "plugins");

  if (!fakku_cookie_exists(ua)) {
    throw new PluginErrorException("Not logged in to FAKKU! Set your FAKKU SID in the plugin settings page!");
  }

  // If the user specified a oneshot argument, use it as-is (we could stand to pre-check it to see
  // if it really is a FAKKU URL but meh). No URL? Look for a "source:" tag in the existing tags.
  // Explicit `string | undefined` annotation: `lrr_info.arg`'s own type is a non-optional
  // `string` (this file's local `ExecMetadataInfo` picks it required from `MetadataHostArgs`),
  // but this variable itself must still admit `undefined` for the two reassignments below
  // (`get_url_from_tags`/`search_for_fakku_url`, both of which can genuinely return none) — a bare
  // `let` here would infer the narrower non-optional type from this first assignment alone.
  let fakku_URL: string | undefined = lrr_info.arg;
  if (!fakku_URL) fakku_URL = get_url_from_tags(lrr_info.existing_tags);
  // Assume URLs coming from the one-shot parameter or tags are reliable.
  const URL_safe = !!fakku_URL;
  // Still nothing? Search for a FAKKU URL using the title.
  if (!fakku_URL) fakku_URL = await search_for_fakku_url(lrr_info.archive_title, ua);

  if (!fakku_URL) {
    const message = "No matching FAKKU Gallery Found!";
    logger.info(message);
    throw new PluginErrorException(message);
  }
  logger.debug(`Detected FAKKU URL: ${fakku_URL}`);
  const [newtags, newtitle, newSummary] = await get_tags_from_fakku(fakku_URL, ua, !!add_source);
  const current_title = lrr_info.archive_title;
  if (safe_mode && !URL_safe && newtitle !== current_title) {
    logger.info(`Found FAKKU Gallery '${newtitle}', but it does not match current title '${current_title}' exactly`);
    throw new PluginErrorException("Exact title match not found");
  }
  logger.info(`Sending the following tags to LRR: ${newtags}`);
  return { tags: newtags, title: newtitle, summary: newSummary };
}

async function search_for_fakku_url(title: string, ua: LegacyUserAgent): Promise<string> {
  const dom = await get_search_result_dom(title, ua);
  // Get the first link on the page that starts with '/hentai/'
  const path = dom.at('[href^="/hentai/"]')?.attr("href");
  return path ? FAKKU_HOST + path : "";
}

/** Strips characters/constructs that break FAKKU's search backend before submitting the query —
 * see `SEARCH_BREAKING_CHARS_PATTERN`'s own doc comment for the character-class rationale, and
 * `strip_bracketed_runs` for why bracket-stripping needs actual bracket-depth scanning rather than
 * a JS regex (the original Perl uses a recursive subpattern `(?0)` JS's regex engine can't do). */
async function get_search_result_dom(title: string, ua: LegacyUserAgent): Promise<LegacyDomNode> {
  const logger = legacyCompat.getLogger("FAKKU", "plugins");

  title = title.replace(SEARCH_BREAKING_CHARS_PATTERN, "");
  // Removes everything inside [ ] as well as the brackets themselves
  title = strip_bracketed_runs(title);
  // Removes everything inside () as well as the parentheses themselves, from the first ( onward
  title = title.replace(PARENTHETICAL_SUFFIX_PATTERN, "");

  // Visit the base host once to set cloudflare cookies and jank
  await ua.max_redirects(5).get(FAKKU_HOST);

  // Use the regular search page. The autosuggest API (fakku.net/suggest/blahblah) yields better
  // results but is blocked unless you make it through cloudflare or are logged in.
  const url = `${FAKKU_HOST}/search/` + encodeURIComponent(title);
  logger.debug(`Using URL ${url} to search on FAKKU.`);
  const res = (await ua.max_redirects(5).get(url)).result;
  return res.dom;
}

/** Removes every top-level `[...]` run (and its brackets) from `title` — a plain non-recursive
 * equivalent of the Perl source's `s/\[([^\[\]]|(?0))*]//g` (which itself only ever needs to
 * handle one level of nesting in real FAKKU titles). */
function strip_bracketed_runs(title: string): string {
  let result = "";
  let depth = 0;
  for (const ch of title) {
    if (ch === "[") {
      depth++;
    } else if (ch === "]") {
      if (depth > 0) depth--;
    } else if (depth === 0) {
      result += ch;
    }
  }
  return result;
}

async function get_dom_from_fakku(url: string, ua: LegacyUserAgent): Promise<LegacyDomNode> {
  const logger = legacyCompat.getLogger("FAKKU", "plugins");
  const res = (await ua.max_redirects(5).get(url)).result;
  const html = res.body;

  const match = html.match(CLOUDFLARE_ERROR_PATTERN);
  if (match) {
    logger.debug(`Blocked by Cloudflare, aborting for now. (Error code ${match[1]})`);
    throw new PluginErrorException("The plugin has been blocked by Cloudflare. Try opening FAKKU in your browser to bypass this.", { code: match[1] });
  }
  return res.dom;
}

async function get_tags_from_fakku(
  url: string,
  ua: LegacyUserAgent,
  add_url: boolean,
): Promise<[string, string, string]> {
  const logger = legacyCompat.getLogger("FAKKU", "plugins");
  const dom = await get_dom_from_fakku(url, ua);
  // find the "suggest more tags" link and use parent div — not ideal, but the divs don't have
  // named classes anymore
  const tags_parent = dom.at('[data-tippy-content="Suggest More Tags"]')?.parent;
  // div that contains other divs with title, namespaced tags (artist, magazine, etc.) and misc tags
  const metadata_parent = tags_parent?.parent?.parent;
  const title = legacyCompat.trim(metadata_parent?.at("h1")?.text);
  logger.debug(`Parsed title: ${title}`);
  const tags: string[] = [];

  // Finds the DIV for the Summary. If it doesn't exist, or FAKKU has no real description, keep it blank.
  const summ_div = dom.at('meta[name="description"]');
  let summary = summ_div ? legacyCompat.htmlUnescape(summ_div.attr("content") ?? "") : "";
  if (FREE_SAMPLE_BLURB_PATTERN.test(summary) || summary === NO_DESCRIPTION_TEXT) {
    summary = "";
  }

  // We can grab some namespaced tags from the first few div.
  const namespaces = metadata_parent?.children("div").each((div) => div) ?? [];
  for (const div of namespaces) {
    const row = div.children().each((child) => child);
    if (row.length !== 2) continue;
    const namespace = row[0].text;
    const value = trim_CRLF(legacyCompat.trim(row[1].at("a")?.text ?? row[1].text));
    // edge case: the gallery is in the top 10 of 2 categories
    if (DUPLICATE_TOP_TEN_TEXT.includes(value)) continue;
    logger.debug(`Parsed row: ${namespace}`);
    logger.debug(`Matching tag: ${value}`);
    if (!SKIPPED_NAMESPACES.includes(namespace) && value !== "") {
      tags.push(`${namespace}:${value}`);
    }
  }

  // might be worth filtering by links starting with '/tags/*' but that filters out the special "unlimited" tag
  const tag_links = tags_parent?.find("a").each((link) => link) ?? [];
  for (const link of tag_links) {
    const tag = trim_CRLF(legacyCompat.trim(link.text));
    if (tag !== "+" && tag !== "") {
      tags.push(tag.toLowerCase());
    }
  }

  if (add_url) {
    url = url.replace(/^https:\/\/www\./i, "");
    tags.push("source:" + url);
  }
  return [tags.join(", "), title, summary];
}

/** `trim_CRLF` (`LANraragi::Utils::String`) — strips every newline from a string. */
function trim_CRLF(s: string): string {
  return s.replace(/\r?\n/g, "");
}

function fakku_cookie_exists(ua: LegacyUserAgent): boolean {
  const logger = legacyCompat.getLogger("FAKKU", "plugins");
  logger.debug("Checking Cookies");
  const cookies = ua.cookies;
  if (cookies && cookies.length > 0) {
    for (const cookie of cookies) {
      if (cookie.name === "fakku_sid") {
        logger.debug("The needed cookie was found.");
        return true;
      }
    }
    logger.debug("The needed cookie was not found.");
  } else {
    logger.debug("No Cookies were found!");
  }
  return false;
}

function get_url_from_tags(actual_tags: string | undefined): string | undefined {
  if (!actual_tags) return undefined;
  const tags = actual_tags.split(",");
  for (const tag of tags) {
    const match = tag.match(SOURCE_TAG_PATTERN);
    if (match) {
      const foundURL = match[1];
      // Makes sure the found url is a fakku.net url.
      if (FAKKU_URL_PATTERN.test(foundURL)) {
        return foundURL;
      }
    }
  }
  return undefined;
}
