// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/GalleryDL.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - file-test operator -e always evaluates to false — this host never gives plugins real 
//     filesystem access outside the current archive

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

// Mirrors `crates/lanrurugi-plugin/dispatcher/plugin-sdk.ts`'s `PluginErrorException` — defined
// locally (not imported) since a plugin file is loaded via a standalone `import()` with no
// relative-path relationship to the SDK file, and the dispatcher's catch block detects this by
// property shape (`error_code`/`data` on a thrown `Error`), not `instanceof`, for exactly that
// reason (see `dispatcher.ts`'s own comment on this). `error_code` is an i18n lookup key — write
// it as a natural, stable phrase that does not embed any dynamic value (that goes in `data`
// instead), so the same `error_code` translates regardless of which specific value triggered it.
class PluginErrorException extends Error {
  constructor(
    public error_code: string,
    public data?: Record<string, string | number>,
  ) {
    super(error_code);
  }
}

export function pluginInfo() {
  return {
    namespace: "gallerydlplugin",
    type: "metadata" as const,
    parameters: [
    ],
    declared_permissions: { net: [], read: false, write: true },
    name: "GalleryDL",
    author: "thelastfantasy",
    description: "Collects metadata from gallery-dl-created info.json files, either embedded in your archive or in the same folder with the same name. ({archive_name}.json)",
    version: "0.1",
    sidecar_files: ["info.json"],
  };
}


export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = perlCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  interface ExecMetadataInfo {
    user_agent: PerlUserAgent;
    user_agent_cookies?: { name: string; value: string; domain: string; path: string }[];
    file_path: string;
  }
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as unknown as ExecMetadataInfo;
  //# Global info hash
  let logger = perlCompat.getLogger("GalleryDL", "plugins");
  let path_in_archive = (hostArgs.sidecar_files as Record<string, string> | undefined)?.["info.json"];
  let [name, path, suffix] = perlCompat.fileparse(lrr_info["file_path"]);
  let path_nearby_json = path + name + '.json';
  let filepath = undefined;
  let delete_after_parse = undefined;
  //    #Extract info.json

  if (path_in_archive) {
    filepath = path_in_archive;
    logger.debug(`Found file in archive at ${filepath}`);
    delete_after_parse = 1;
  } else if (false) {
    filepath = path_nearby_json;
    logger.debug(`Found file nearby at ${filepath}`);
    delete_after_parse = 0;
  } else {
    throw new PluginErrorException("No in-archive info.json or {archive_name}.json file found!");
  }
  //    #Open it

  let stringjson = "";
  let fh = filepath;
  if (fh === undefined) { throw new PluginErrorException("Could not open file", { filepath }); }
  for (let row of (fh ?? "").split(/\r?\n/)) {
    row = perlCompat.chomp(row);
    stringjson += row;
  }
  //    #Use Mojo::JSON to decode the string into a hash

  let hashjson = JSON.parse(stringjson);
  logger.debug(`Loaded the following JSON: ${stringjson}`);
  if (hashjson["tags"] == undefined) {
    return { error: { error_code: "The info.json file could not be parsed as a gallery-dl file!" } };
  }
  //    #Parse it

  let [tags, title] = tags_from_gdl_json(hashjson);
  if (delete_after_parse) {
    //        #Delete it
  
    ;
  }
  //    #Return tags

  logger.info(`Sending the following tags to LRR: ${tags}`);
  if (title) {
    logger.info(`Parsed title is ${title}`);
    return { tags: tags, title: title };
  } else {
    return { tags: tags };
  }
}

function tags_from_gdl_json(...args: any[]) {
  let [hash] = args.slice(0);
  let logger = perlCompat.getLogger("GalleryDL", "plugins");
  let parsed_tags = [] as any[];
  let seen_tags = {} as Record<string, any>;
  //    #Tags are in tags -> one array per namespace

  let tags = hash["tags"];
  let title = hash["title"];
  title = perlCompat.trim(title);
  let tagstype = perlCompat.refType(hash["tags"]);
  if (tagstype === perlCompat.refType({})) {
    //        #If tags is a hash, we need to convert it before chopping it up
  
    logger.info("Parsing hash-style tags");
    for (let namespace of Object.keys(tags).sort()) {
      //            # Get the array for this namespace and iterate on it
    
      let members = tags[namespace];
      for (let tag of members) {
        push_tag(parsed_tags, seen_tags, namespace, tag);
      }
    }
  } else if (tagstype === perlCompat.refType([])) {
    //        #An array of key:value strings is our 'native' format, so we can go straight to chopping it up for processing
  
    logger.info("Parsing array-style tags");
    for (let tag of tags) {
      push_tag(parsed_tags, seen_tags, undefined, tag);
    }
  } else {
    let message = "Tags are in an unexpected structure, can't be parsed";
    logger.error(message);
    throw new PluginErrorException(message);
  }
  push_mapped_fields(parsed_tags, seen_tags, hash);
  //    # Add source and category tag if possible

  let source = hash["source"];
  let category = hash["category"];
  if (category) {
    push_tag(parsed_tags, seen_tags, "category", category);
  }
  if (source) {
    push_tag(parsed_tags, seen_tags, "source", source);
  }
  return [parsed_tags.join(', '), title];
}

function push_mapped_fields(...args: any[]) {
  let [parsed_tags, seen_tags, hash] = args.slice(0);
  let field_map = [["artist", "artist"], ["group", "group"], ["parody", "parody"], ["character", "character"], ["characters", "character"], ["language", "language"], ["type", "type"]];
  for (let mapping of field_map) {
    let [field, namespace] = mapping;
    if (field === "language") {
      if ((hash["language"] !== undefined)) {
        push_tag(parsed_tags, seen_tags, "language", hash["language"]);
      } else if ((hash["lang"] !== undefined)) {
        push_tag(parsed_tags, seen_tags, "language", hash["lang"]);
      }
    } else {
      if (!((hash[field] !== undefined))) { continue; }
      push_tag(parsed_tags, seen_tags, namespace, hash[field]);
    }
  }
}

function push_tag(...args: any[]) {
  let [parsed_tags, seen_tags, namespace, value] = args.slice(0);
  if (!((value !== undefined && value !== null))) { return; }
  if (Array.isArray(value)) {
    for (let member of value) {
      push_tag(parsed_tags, seen_tags, namespace, member);
    }
    return;
  }
  if (perlCompat.refType(value)) { return; }
  let tag = perlCompat.trim(value);
  if (tag === "") { return; }
  tag = namespace ? `${namespace}:${tag}` : tag;
  let dedupe_key = tag.toLowerCase();
  if (seen_tags[dedupe_key]) { return; }
  parsed_tags.push(tag);
  seen_tags[dedupe_key] = 1;
}
