// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/HDoujin.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Hand-cleaned since regeneration: `trim_url` (`~/LANraragi/lib/LANraragi/Utils/String.pm:51-65`)
// has no JS equivalent in scope, so it's reimplemented below rather than left as a dangling
// reference; every helper below was also given real parameter/return types (replacing the
// converter's blanket `(...args: any[])` + manual `args[0]`/`args[1]` unpacking) and the
// namespace-matching regex was pulled out to a single shared constant instead of being
// duplicated between the TXT and JSON parsers.

export function pluginInfo() {
  return {
    namespace: "Hdoujinplugin",
    type: "metadata" as const,
    parameters: [],
    declared_permissions: { net: [], read: false, write: true },
    name: "HDoujin",
    author: "thelastfantasy",
    description: "Collects metadata embedded into your archives by HDoujin Downloader's JSON or TXT files.",
    version: "0.1",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABmJLR0QA/wD/AP+gvaeTAAAACXBI\nWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4wYDFB0m9797jwAAAB1pVFh0Q29tbWVudAAAAAAAQ3Jl\nYXRlZCB3aXRoIEdJTVBkLmUHAAAEbklEQVQ4y1WUPW/TUBSGn3uvHdv5cBqSOrQJgQ4ghqhCAgQM\nIIRAjF2Y2JhA/Q0g8R9YmJAqNoZKTAwMSAwdQEQUypeQEBEkTdtUbdzYiW1sM1RY4m5Hunp1znmf\n94jnz5+nAGmakiQJu7u7KKWwbRspJWma0m63+fHjB9PpFM/z6Ha7FAoFDMNga2uLx48fkyQJ29vb\nyCRJSNMUz/PY2dnBtm0qlQpKKZIkIQgCer0eW1tbDIdDJpMJc3NzuK5Lt9tF13WWl5dJkoRyuYyU\nUrK3t0ccx9TrdQzD4F/HSilM08Q0TWzbplqtUqvVKBaLKKVoNpt8/vyZKIq4fv064/EY2ev1KBQK\n2LadCQkhEEJkteu6+L6P7/tMJhOm0ylKKarVKjdu3GA6nXL+/HmSJEHWajV0Xf9P7N8TQhDHMWEY\nIoRgOBzieR4At2/f5uTJk0RRRLFYZHZ2liNHjqBFUcRoNKJarSKlRAiRmfPr1y/SNMVxHI4dO8aF\nCxfI5/O4rotSirdv33L16lV+//7Nly9fUEqh5XI5dF0nTdPMaSEEtm3TaDSwLAvLstB1nd3dXUql\nEqZpYlkW6+vrdLtdHjx4wPb2NmEYHgpalkUQBBwcHLC2tsbx48cpFos4jkMQBIRhyGQyYTgcsrGx\nQavVot1uc+LECcbjMcPhkFKpRC6XQ0vTlDAMieOYQqGA4zhcu3YNwzDQdR3DMA4/ahpCCPL5fEbC\nvXv3WFlZ4c+fP7TbbZaWlpBRFGXjpmnK/Pw8QRAwnU6RUqJpGp7nMRqNcF0XwzCQUqKUolwus7y8\njO/7lMtlFhcX0YQQeJ6XMXfq1Cn29/epVCrouk4QBNi2TalUIoqizLg0TQEYjUbU63VmZmYOsdE0\nDd/3s5HH4zG6rtNsNrEsi0qlQqFQYH19nVevXjEej/8Tm0wmlMtlhBAMBgOkaZo0Gg329vbY2dkh\nCIJsZ0oplFK8efOGp0+fcvHiRfL5PAAHBweEYcj8/HxGydevX5FxHDMajajVanz69Ik4jkmSBF3X\n0TSNzc1N7t69S6vV4vXr10gp8X2f4XBIpVLJghDHMRsbG2jT6TRLxuLiIr1eDwBN09A0jYcPHyKE\n4OjRo8RxTBRF9Pt95ubmMud93+f79+80m03k/v4+UspDKDWNRqPBu3fvSNOUtbU16vU6ly5dwnEc\ncrkcrutimib5fD4zxzRNVldXWVpaQqysrKSdTofLly8zmUwoFAoIIfjXuW3bnD17NkuJlBLHcdA0\nDYAgCHj27BmO47C6uopM05RyucyLFy/QNA3XdRFCYBgGQRCwubnJhw8fGAwGANRqNTRNI0kSXr58\nyc2bN6nX64RhyP379xFPnjxJlVJIKTl37hydTocoiuh0OszOzmJZFv1+n8FgwJ07d7hy5Qrj8ZiP\nHz/S7/c5ffo0CwsL9Ho9ZmZmEI8ePUoNwyBJEs6cOcPCwgLfvn3j/fv35PN5bNtGKZUdjp8/f3Lr\n1q3svLVaLTzPI4oiLMviL7opJdyaltNwAAAAAElFTkSuQmCC",
    sidecar_files: ["info.json", "info.txt"],
  };
}

/** Every namespace/tag line this plugin's TXT/JSON parsers recognize, matched case-insensitively
 * against the start of a line (`"artist: John Doe"`) or a JSON object key. Shared as one constant
 * instead of duplicated between the two parsers (`~/LANraragi/lib/LANraragi/Plugin/Metadata/
 * HDoujin.pm`'s own `get_tags_from_hdoujin_txt_file`/`get_tags_from_hdoujin_json_file_hash` each
 * had their own copy of an equivalent regex). */
const RECOGNIZED_NAMESPACE_PATTERN = /^(artist|author|circle|characters?|description|language|parody|series|tags|title|url)/i;
const TXT_LINE_PATTERN = new RegExp(`${RECOGNIZED_NAMESPACE_PATTERN.source}: (.*)`, "i");

interface ParsedMetadata {
  title: string;
  tags: string;
  summary: string;
}

export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = legacyCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  interface ExecMetadataInfo extends Required<Pick<MetadataHostArgs, "file_path">> {
    user_agent: LegacyUserAgent;
    user_agent_cookies?: LegacyCookie[];
  }
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as unknown as ExecMetadataInfo;
  let logger = legacyCompat.getLogger("HDoujin", "plugins");
  let archive_file_path = lrr_info["file_path"];
  const sidecarFiles = hostArgs.sidecar_files as Record<string, string> | undefined;

  let path_in_archive = sidecarFiles?.["info.json"];
  if (path_in_archive) {
    return get_tags_from_hdoujin_json_file(archive_file_path, path_in_archive);
  }
  path_in_archive = sidecarFiles?.["info.txt"];
  if (path_in_archive) {
    return get_tags_from_hdoujin_txt_file(archive_file_path, path_in_archive);
  }
  throw new PluginErrorException("No HDoujin metadata files found in this archive!");
}

function get_tags_from_hdoujin_txt_file(_archive_file_path: string, file_contents: string): ParsedMetadata {
  let match: RegExpMatchArray | null;
  let logger = legacyCompat.getLogger("HDoujin", "plugins");
  let title = "";
  let tags = "";
  let summary = "";
  for (let line of file_contents.split(/\r?\n/)) {
    if ((match = line.match(TXT_LINE_PATTERN))) {
      let namespace = normalize_namespace(match[1]);
      let value = match[2].trim();
      if (value === "") {
        continue;
      }
      if (namespace.toLowerCase() === "source") {
        value = trim_url(value);
      }
      if (namespace.toLowerCase() === "description") {
        summary = value;
      } else if (namespace.toLowerCase() === "title") {
        title = value;
      } else {
        tags = append_tags(tags, namespace, value);
      }
    }
  }
  if (tags === "") {
    throw new PluginErrorException("No tags were found in info.txt!");
  }
  logger.info(`Sending the following tags to LRR: ${tags}`);
  return { title, tags: remove_duplicates(tags), summary };
}

function get_tags_from_hdoujin_json_file(_archive_file_path: string, file_contents: string): ParsedMetadata {
  let logger = legacyCompat.getLogger("HDoujin", "plugins");
  let json_str = "";
  for (let row of file_contents.split(/\r?\n/)) {
    json_str += legacyCompat.chomp(row);
  }
  let json_hash = JSON.parse(json_str);
  logger.debug(`Found and loaded the following JSON: ${json_str}`);
  // Note that fields may be encapsulated in an outer "manga_info" object if the user has enabled
  // this. Each field can contain either a single tag or an array of tags.
  if (json_hash["manga_info"] !== undefined) {
    json_hash = json_hash["manga_info"];
  }
  let title = json_hash["title"];
  let tags = get_tags_from_hdoujin_json_file_hash(json_hash);
  let summary = json_hash["description"];
  if (tags === "") {
    throw new PluginErrorException("No tags were found in info.json!");
  }
  logger.info(`Sending the following tags to LRR: ${tags}`);
  return { title, tags: remove_duplicates(tags), summary };
}

function get_tags_from_hdoujin_json_file_hash(json_obj: Record<string, unknown>): string {
  let tags = "";
  let filtered_keys = Object.keys(json_obj).filter((it) => RECOGNIZED_NAMESPACE_PATTERN.test(it));
  for (let key of filtered_keys) {
    let namespace = normalize_namespace(key);
    let values: unknown = json_obj[key];
    if (namespace.toLowerCase() === "source" && typeof values === "string") {
      values = trim_url(values);
    }
    if (Array.isArray(values)) {
      // We have an array of values (e.g. author, artist, language, and character fields).
      for (let tag of values) {
        tags = append_tags(tags, namespace, String(tag));
      }
    } else if (typeof values === "object" && values !== null) {
      // We have a map of keyed values (e.g. tags with namespace arrays enabled).
      const nestedMap = values as Record<string, unknown[]>;
      for (let nestedNamespace of Object.keys(nestedMap)) {
        for (let tag of nestedMap[nestedNamespace]) {
          tags = append_tags(tags, normalize_namespace(nestedNamespace), String(tag));
        }
      }
    } else {
      // We have a basic string value (e.g. series).
      tags = append_tags(tags, namespace, String(values));
    }
  }
  return tags;
}

function append_tags(tags: string, namespace: string, append: string): string {
  for (let tag of append.split(",")) {
    tag = tag.trim();
    if (tag === "") {
      continue;
    }
    if (namespace !== "") {
      tag = `${namespace.toLowerCase()}:${tag}`;
    }
    if (tags !== "") {
      tags += ", ";
    }
    tags += tag;
  }
  return tags;
}

function remove_duplicates(tags: string): string {
  // The tags list may contain tags duplicated in fields, so it's likely to encounter duplicates.
  const seenTags = new Set<string>();
  const uniqueTags: string[] = [];
  for (let tag of tags.split(",")) {
    tag = tag.trim();
    const key = tag.toLowerCase();
    if (seenTags.has(key)) {
      continue;
    }
    seenTags.add(key);
    uniqueTags.push(tag);
  }
  return uniqueTags.join(", ");
}

function normalize_namespace(rawNamespace: string): string {
  const namespace = rawNamespace.toLowerCase();
  if (namespace === "characters") {
    return "character";
  } else if (namespace === "misc") {
    return "other";
  } else if (namespace === "tags") {
    return "";
  } else if (namespace === "url") {
    return "source";
  }
  return namespace;
}

/** `~/LANraragi/lib/LANraragi/Utils/String.pm:51-65` — strips whitespace, `https?://`, an
 * optional leading `www.`, and any query string, then normalizes the result to have no trailing
 * slash (Perl's `chop`-then-conditionally-restore idiom: remove the last character, put it back
 * only if it wasn't a `/`). */
function trim_url(url: string): string {
  url = url.trim();
  const match = url.match(/^https?:\/\/(?:www\.)?([^?]*)\??.*/);
  if (match) {
    url = match[1];
  }
  return url.endsWith("/") ? url.slice(0, -1) : url;
}
