// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/HDoujin.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-09.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - =~ with /g in list context 
//     (/^(artist|author|circle|characters?|description|language|parody|series|tags|title|url): 
//     (.*)/i) — Perl returns every captured group across all matches; JS .match() with /g returns 
//     only full-match strings, not captures. Verify this call site by hand.

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

export function pluginInfo() {
  return {
    namespace: "Hdoujinplugin",
    type: "metadata" as const,
    parameters: [
    ],
    declared_permissions: { net: [], read: false, write: false },
    name: "HDoujin",
    author: "Pao, Squidy (ported)",
    description: "Collects metadata embedded into your archives by HDoujin Downloader's JSON or TXT files.",
    version: "0.7",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABmJLR0QA/wD/AP+gvaeTAAAACXBI\nWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4wYDFB0m9797jwAAAB1pVFh0Q29tbWVudAAAAAAAQ3Jl\nYXRlZCB3aXRoIEdJTVBkLmUHAAAEbklEQVQ4y1WUPW/TUBSGn3uvHdv5cBqSOrQJgQ4ghqhCAgQM\nIIRAjF2Y2JhA/Q0g8R9YmJAqNoZKTAwMSAwdQEQUypeQEBEkTdtUbdzYiW1sM1RY4m5Hunp1znmf\n94jnz5+nAGmakiQJu7u7KKWwbRspJWma0m63+fHjB9PpFM/z6Ha7FAoFDMNga2uLx48fkyQJ29vb\nyCRJSNMUz/PY2dnBtm0qlQpKKZIkIQgCer0eW1tbDIdDJpMJc3NzuK5Lt9tF13WWl5dJkoRyuYyU\nUrK3t0ccx9TrdQzD4F/HSilM08Q0TWzbplqtUqvVKBaLKKVoNpt8/vyZKIq4fv064/EY2ev1KBQK\n2LadCQkhEEJkteu6+L6P7/tMJhOm0ylKKarVKjdu3GA6nXL+/HmSJEHWajV0Xf9P7N8TQhDHMWEY\nIoRgOBzieR4At2/f5uTJk0RRRLFYZHZ2liNHjqBFUcRoNKJarSKlRAiRmfPr1y/SNMVxHI4dO8aF\nCxfI5/O4rotSirdv33L16lV+//7Nly9fUEqh5XI5dF0nTdPMaSEEtm3TaDSwLAvLstB1nd3dXUql\nEqZpYlkW6+vrdLtdHjx4wPb2NmEYHgpalkUQBBwcHLC2tsbx48cpFos4jkMQBIRhyGQyYTgcsrGx\nQavVot1uc+LECcbjMcPhkFKpRC6XQ0vTlDAMieOYQqGA4zhcu3YNwzDQdR3DMA4/ahpCCPL5fEbC\nvXv3WFlZ4c+fP7TbbZaWlpBRFGXjpmnK/Pw8QRAwnU6RUqJpGp7nMRqNcF0XwzCQUqKUolwus7y8\njO/7lMtlFhcX0YQQeJ6XMXfq1Cn29/epVCrouk4QBNi2TalUIoqizLg0TQEYjUbU63VmZmYOsdE0\nDd/3s5HH4zG6rtNsNrEsi0qlQqFQYH19nVevXjEej/8Tm0wmlMtlhBAMBgOkaZo0Gg329vbY2dkh\nCIJsZ0oplFK8efOGp0+fcvHiRfL5PAAHBweEYcj8/HxGydevX5FxHDMajajVanz69Ik4jkmSBF3X\n0TSNzc1N7t69S6vV4vXr10gp8X2f4XBIpVLJghDHMRsbG2jT6TRLxuLiIr1eDwBN09A0jYcPHyKE\n4OjRo8RxTBRF9Pt95ubmMud93+f79+80m03k/v4+UspDKDWNRqPBu3fvSNOUtbU16vU6ly5dwnEc\ncrkcrutimib5fD4zxzRNVldXWVpaQqysrKSdTofLly8zmUwoFAoIIfjXuW3bnD17NkuJlBLHcdA0\nDYAgCHj27BmO47C6uopM05RyucyLFy/QNA3XdRFCYBgGQRCwubnJhw8fGAwGANRqNTRNI0kSXr58\nyc2bN6nX64RhyP379xFPnjxJlVJIKTl37hydTocoiuh0OszOzmJZFv1+n8FgwJ07d7hy5Qrj8ZiP\nHz/S7/c5ffo0CwsL9Ho9ZmZmEI8ePUoNwyBJEs6cOcPCwgLfvn3j/fv35PN5bNtGKZUdjp8/f3Lr\n1q3svLVaLTzPI4oiLMviL7opJdyaltNwAAAAAElFTkSuQmCC",
    sidecar_files: ["info.json", "info.txt"],
  };
}


export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = perlCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as Record<string, any>;
  //# Global info hash
  let logger = perlCompat.getLogger("HDoujin", "plugins");
  let archive_file_path = lrr_info["file_path"];
  let path_in_archive = (hostArgs.sidecar_files as Record<string, string> | undefined)?.["info.json"];
  if (path_in_archive) {
    return get_tags_from_hdoujin_json_file(archive_file_path, path_in_archive);
  }
  path_in_archive = (hostArgs.sidecar_files as Record<string, string> | undefined)?.["info.txt"];
  if (path_in_archive) {
    return get_tags_from_hdoujin_txt_file(archive_file_path, path_in_archive);
  }
  throw new Error("No HDoujin metadata files found in this archive!\n");
}

function get_tags_from_hdoujin_txt_file(...args: any[]) {
  let match: RegExpMatchArray | null;
  let archive_file_path = args[0];
  let path_in_archive = args[1];
  let logger = perlCompat.getLogger("HDoujin", "plugins");
  let file_path = path_in_archive;
  let file_handle = file_path;
  if (file_handle === undefined) { throw new Error(`Could not open ${file_path}!\n`); }
  let title = "";
  let tags = "";
  let summary = "";
  for (let line of (file_handle ?? "").split(/\r?\n/)) {
    if ((match = line.match(/^(artist|author|circle|characters?|description|language|parody|series|tags|title|url): (.*)/i))) {
      let namespace = normalize_namespace(match[1]);
      let value = match[2];
      (value = value.replace(/^\s+|\s+$/g, ""));
      if (value === "") {
        continue;
      }
      if (namespace.toLowerCase() === "source") {
        value = trim_url(value);
      }
      if (namespace.toLowerCase() === "description") {
        summary = value;
      } else if (namespace.toLowerCase() === "title") {
        title = value;
      } else {
        tags = append_tags(tags, namespace, value);
      }
    }
  }
  ;
  if (tags === "") {
    throw new Error("No tags were found in info.txt!\n");
  }
  logger.info(`Sending the following tags to LRR: ${tags}`);
  return { title: title, tags: remove_duplicates(tags), summary: summary };
}

function get_tags_from_hdoujin_json_file(...args: any[]) {
  let archive_file_path = args[0];
  let path_in_archive = args[1];
  let logger = perlCompat.getLogger("HDoujin", "plugins");
  let file_path = path_in_archive;
  let json_str = "";
  let file_handle = file_path;
  if (file_handle === undefined) { throw new Error(`Could not open ${file_path}!\n`); }
  for (let row of (file_handle ?? "").split(/\r?\n/)) {
    row = perlCompat.chomp(row);
    json_str += row;
  }
  let json_hash = JSON.parse(json_str);
  logger.debug(`Found and loaded the following JSON: ${json_str}`);
  //    # Note that fields may be encapsulated in an outer "manga_info" object if the user has enabled this.

  //    # Each field can contain either a single tag or an array of tags.

  if ((json_hash["manga_info"] !== undefined)) {
    json_hash = json_hash["manga_info"];
  }
  let title = json_hash["title"];
  let tags = get_tags_from_hdoujin_json_file_hash(json_hash);
  let summary = json_hash["description"];
  ;
  if (tags === "") {
    throw new Error("No tags were found in info.json!\n");
  }
  logger.info(`Sending the following tags to LRR: ${tags}`);
  return { title: title, tags: remove_duplicates(tags), summary: summary };
}

function get_tags_from_hdoujin_json_file_hash(...args: any[]) {
  let json_obj = args[0];
  let tags = "";
  let logger = perlCompat.getLogger("HDoujin", "plugins");
  let filtered_keys = Object.keys(json_obj).filter((it) => (/^(?:artist|author|circle|characters?|language|parody|series|tags|url)/i.test(it)));
  for (let key of filtered_keys) {
    let namespace = normalize_namespace(key);
    let values = json_obj[key];
    if (namespace.toLowerCase() === "source") {
      values = trim_url(values);
    }
    if (perlCompat.refType(values) === 'ARRAY') {
      //            # We have an array of values (e.g. author, artist, language, and character fields).
    
      for (let tag of values) {
        tags = append_tags(tags, namespace, tag);
      }
    } else if (perlCompat.refType(values) === 'HASH') {
      //            # We have a map of keyed values (e.g. tags with namespace arrays enabled).
    
      for (let nestedNamespace of Object.keys(values)) {
        let nestedValues = values[nestedNamespace];
        for (let tag of nestedValues) {
          tags = append_tags(tags, normalize_namespace(nestedNamespace), tag);
        }
      }
    } else {
      //            # We have a basic string value (e.g. series).
    
      tags = append_tags(tags, namespace, values);
    }
  }
  return tags;
}

function append_tags(...args: any[]) {
  let tags = args[0];
  let namespace = args[1];
  let append = args[2];
  let split_tags = append.split(/,/);
  for (let tag of split_tags) {
    (tag = tag.replace(/^\s+|\s+$/g, ""));
    if (tag === "") {
      continue;
    }
    if (namespace !== "") {
      tag = namespace.toLowerCase() + ":" + tag;
    }
    if (!(tags === "")) { tags += ", "; }
    tags += tag;
  }
  return tags;
}

function remove_duplicates(...args: any[]) {
  //    # The tags list may contain tags duplicated in fields, so it's likely to encounter duplicates.

  let tags = args[0];
  let split_tags = tags.split(/,/);
  let seenTags = {} as Record<string, any>;
  let uniqueTags = [] as any[];
  for (let tag of split_tags) {
    (tag = tag.replace(/^\s+|\s+$/g, ""));
    if (seenTags[tag.toLowerCase()] ++) { continue; }
    uniqueTags.push(tag);
  }
  return uniqueTags.join(", ");
}

function normalize_namespace(...args: any[]) {
  let namespace = args[0].toLowerCase();
  if (namespace === "characters") {
    return "character";
  } else if (namespace === "misc") {
    return "other";
  } else if (namespace === "tags") {
    return "";
  } else if (namespace === "url") {
    return "source";
  }
  return namespace;
}
