// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/Hentag.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-09.

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

export function pluginInfo() {
  return {
    namespace: "hentagplugin",
    type: "metadata" as const,
    parameters: [
    ],
    declared_permissions: { net: [], read: false, write: false },
    name: "Hentag",
    author: "siliconfeces (ported)",
    description: "Parses Hentag info.json files embedded in archives. Achtung, no API calls!",
    version: "0.3",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAAPoAAAD6AG1e1JrAAAEzklEQVR4nO2Xa0xbZRjH6xe/0NKW0p7TQgul9GJpuQ0YbcFgXFx0M+NaoF0gY4mbkwLLxjYoMoiZMVGnDJZt2TT7plnGxmVCgXEdi859MGabH0xqNHFeBsxsETSGnL95314sWyuXrMYYP/zznHN6zvv83uft87zvw4tnzRYho/HGMmrEMmpOxGg5MWuAiNFBzOofE30uN0Ao0yJWkuKXBsL41LWIo5KkQijVeiVKo4XHlyV5GcUmqBKLllWJRYiXmyFg1AgHEbgXxKVAqjJDaS6A0mRDQtpmsMZsyNNyIDeuLoUpd1mqNiM2LsXLy9Xsw+H875eP5N9Fi+Vn7rWcL7hk5RYIZCshAjMXiNVItW7FKxcG0OCZgmtoAq6hcTj7PkRp77sou/QeynojiqMi71w8vmzYvg28g5u/4Tpsi2izLnBuyxz3ZiFQajqPGFki4thnHlsCgUSN8nd60HLjSzSNXcP+8es4MPEZXFfHYb/SA/uVbr+NKM4+2M1VjZxC8Udvczy/Y7gt81yr5R46bEtwZvQhlkmJsP56OM+cx8GpG2gcnfFBjM2iYXQS9oEeVAycWIu4iv4uEBCe2zJPZk8AQAA6bb/BkXE5PACrg0imQ9XJc2ie/RxNnhk0jc5i/9h1NIz8BWAf7A46C173d6Gin1jfNXlefvl9rAtALNdBJNbBuetjNM/cROP0FJqmZ9A0fQ0N0xOo9pwOOg2I3FcOnUT16GmQsFN5TsFx9Qzy6uvAa7P6AIhdFYDVQ8ikotY8gnbHPA7Vf43D+7xorf8OrrqbKDzUAPtQyDL0d1HHzx07AP22l5BWVgxjyQ5qtS9spUvK2xBA1jA6836HO2sBbVn30ZGzCFfqbRhfLEalp8cX5oETNMTOqXPIrnPg6acYCMQp4Mcmgy9IgkBIsky/QYBMDzoKFtFquwe3bQ5Hn30IV8YtpJdUrATo64Jz8ixy9tZSx5JEI+IUBiqS0hEBnBRAQ+vAoxIxWgrQaVui75MMOlrwEC7zLZh3lIcH2FODmBiVz/EjE+KFA6jO6EWMTAkho6EgJBo+q4FAloyazKHoAXTYlugM5Yo8JCRY/bIErSIhH7uzJ0GKVyutH08QwB1MyTlSniPoLv09kLpPFKDNPyixr1t/iajQ96IUgXk6cGTNRzsC99FufRBR5PeoRqDF8iMa8+5E0FdosfwUnQi0+tNwZ+Yg3Yql8nTEU5mDVsKasCtrzJ8FUaoDjoxLNN9J0SEi1S9wTWpCTeZwdAuRI1iKQz/wXf8jldCxhr3gf4DO/8wSuNdzJPv3AAz/PcBAGAB+xCVYWPOxPJiGWR502H4NArQXPIDLfBvpJXbYh7tXHskmziJ3b+3KCDB6zjeWnltnY2IAX6ZCVfoFHCvkghvTG4V/YI/5U2iKttBTb+UnvgaFQOyc/gDpjgrw+UkBAOKcEzFkPB23vtaMNUAgS4JW9TIac+/QPeFI/g9ozv8WWSm7ESNVwtb8Ko1A6cXj9FT8/FvNiE8yQSTTUuciRkedi1jdMrFhmlPTKs0pgUim+wR5n4hRZEPAJNOmRShNBWsINKqb6DdCKXUeOt6ymNFBxOq9vA2156wBQrov0G/oHzO0bNNWnLTg8WQPCY1gIPw6cu8Vs3rLnwIWEm0oy+KXAAAAAElFTkSuQmCC",
    sidecar_files: ["info.json"],
  };
}


export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = perlCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as Record<string, any>;
  //# Global info hash
  let logger = perlCompat.getLogger("Hentag", "plugins");
  let file = lrr_info["file_path"];
  let path_in_archive = (hostArgs.sidecar_files as Record<string, string> | undefined)?.["info.json"];
  if ((! path_in_archive)) { throw new Error("No hentag info.json file found in this archive!\n"); }
  //    #Extract info.json

  let filepath = path_in_archive;
  //    #Open it

  let stringjson = "";
  let fh = filepath;
  if (fh === undefined) { throw new Error(`Could not open ${filepath}!\n`); }
  for (let row of (fh ?? "").split(/\r?\n/)) {
    row = perlCompat.chomp(row);
    stringjson += row;
  }
  //    #Use Mojo::JSON to decode the string into a hash

  let hashjson = JSON.parse(stringjson);
  logger.debug(`Found and loaded the following JSON: ${stringjson}`);
  //    #Parse it

  let [tags, title] = tags_from_hentag_json(hashjson);
  //    #Delete it

  ;
  //    #Return tags

  logger.info(`Sending the following tags to LRR: ${tags}`);
  if (title) {
    logger.info(`Parsed title is ${title}`);
    return { tags: tags, title: title };
  } else if (tags !== "") {
    return { tags: tags };
  }
}

function tags_from_hentag_json(...args: any[]) {
  let [hash] = args.slice(0);
  let found_tags = [] as any[];
  let title = hash["title"];
  let parodies = hash["parodies"];
  let groups = hash["circles"];
  let artists = hash["artists"];
  let characters = hash["characters"];
  let maleTags = hash["maleTags"];
  let femaleTags = hash["femaleTags"];
  let otherTags = hash["otherTags"];
  let language = language_from_hentag_json(hash);
  let urls = hash["locations"];
  //    # not handled yet: category, createdAt

  //    # tons of different shit creates different kinds of info.json file, so validate the shit out of the data

  found_tags = try_add_tags(found_tags, "series:", parodies);
  found_tags = try_add_tags(found_tags, "group:", groups);
  found_tags = try_add_tags(found_tags, "artist:", artists);
  found_tags = try_add_tags(found_tags, "character:", characters);
  found_tags = try_add_tags(found_tags, "male:", maleTags);
  found_tags = try_add_tags(found_tags, "female:", femaleTags);
  found_tags = try_add_tags(found_tags, "other:", otherTags);
  if (!(! (language !== undefined && language !== null))) { found_tags.push("language:" + language); }
  found_tags = try_add_tags(found_tags, "source:", urls);
  //    #Done-o

  let concat_tags = found_tags.join(", ");
  return [concat_tags, title];
}

function language_from_hentag_json(...args: any[]) {
  let [hash] = args.slice(0);
  let language = hash["language"];
  return language;
}

function try_add_tags(...args: any[]) {
  let found_tags = args[0];
  let prefix = args[1];
  let tags = args[2];
  let potential_tags = [] as any[];
  if (perlCompat.refType(tags) === 'ARRAY') {
    for (let tag of tags) {
      if (perlCompat.refType(tag) === 'HASH' || perlCompat.refType(tag) === 'ARRAY') {
        //                # Weird stuff in here, don't continue parsing to avoid garbage data
      
        return found_tags;
      }
      potential_tags.push(prefix + tag);
    }
  }
  found_tags.push(potential_tags);
  return found_tags;
}
