// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/Koromo.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

export function pluginInfo() {
  return {
    namespace: "koromoplugin",
    type: "metadata" as const,
    parameters: [
    ],
    declared_permissions: { net: [], read: false, write: true },
    name: "koromo",
    author: "thelastfantasy",
    description: "Collects metadata embedded into your archives as Koromo-style Info.json files. ( {'Tags': [xxx] } syntax)",
    version: "2.2",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABhGlDQ1BJQ0MgcHJvZmlsZQAAKJF9kT1Iw1AUhU9TpVoqDmYQcchQnSyIijhKFYtgobQVWnUweekfNDEkKS6OgmvBwZ/FqoOLs64OroIg+APi4uqk6CIl3pcUWsR44fE+zrvn8N59gNCoMs3qGgc03TbTibiUy69IoVeE0QsRAYgys4xkZiEL3/q6pz6quxjP8u/7s/rUgsWAgEQ8ywzTJl4nnt60Dc77xCIryyrxOfGYSRckfuS64vEb55LLAs8UzWx6jlgklkodrHQwK5sa8RRxVNV0yhdyHquctzhr1Rpr3ZO/MFLQlzNcpzWMBBaRRAoSFNRQQRU2YrTrpFhI03ncxz/k+lPkUshVASPHPDagQXb94H/we7ZWcXLCS4rEge4Xx/kYAUK7QLPuON/HjtM8AYLPwJXe9m80gJlP0uttLXoE9G8DF9dtTdkDLneAwSdDNmVXCtISikXg/Yy+KQ8M3ALhVW9urXOcPgBZmtXSDXBwCIyWKHvN5909nXP7t6c1vx8dzXKFeWpUawAAAAZiS0dEAOwAEABqpSa6lwAAAAlwSFlzAAAuIwAALiMBeKU/dgAAAAd0SU1FB+MKCRQBJSKMeg0AAAGVSURBVDjLpZMxa9tQFIXPeaiyhxiZzKFjBme1JFfYgYAe9Bd0yA8JIaQhkJLBP6T/wh3qpZYzm2I8dyilJJMTW7yTIVGRFasE8uAt93K+d+5991IS8Ybj1SVIer24ty8Jk2wyl5S/GkDSi+O4s9PaOYOQh91wSHK2DeLViVut1pmkTwAQtAPUQcz/xCRBEpKOg3ZwEnbDDklvK6AQ+77fds4tSJbBcM7Nm83GbhXiVcXj8fiHpO/WWgfgHAAkXYxGoy8k/UG/nzxDnsqRxF7cO0iS5AhAQxKLm6bpVZqmn8sxAI3kQ2KjKDqQ9GRFEqDNfpQcukrMkDRF3ADAJJvM1+v1n0G/n5D0AcBaew3gFMCFtfbyuVT/cHCYrFarX1mWLQCgsAWSXtgNO81mY/ed7380xpyUn3XOXefr/Ntyufw9vZn+LL7zn21J+fRmOru/f/hrjNmThFLOGWPeV8UvBklSTnIWdsNh0A4g6RiAI/n17vZuWBVvncQNSBAYEK5OvNGDbSMdRdE+AJdl2aJumfjWdX4EIwDvDt7UjSEAAAAASUVORK5CYII=",
    sidecar_files: ["Info.json", "info.json"],
  };
}


export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = perlCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  interface ExecMetadataInfo {
    user_agent: PerlUserAgent;
    user_agent_cookies?: { name: string; value: string; domain: string; path: string }[];
    file_path: string;
  }
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as unknown as ExecMetadataInfo;
  //# Global info hash
  let logger = perlCompat.getLogger("koromo", "plugins");
  let file = lrr_info["file_path"];
  let path_in_archive = (hostArgs.sidecar_files as Record<string, string> | undefined)?.["Info.json"];
  if (!(path_in_archive)) {
    //        # Try for the lowercase variant as well
  
    path_in_archive = (hostArgs.sidecar_files as Record<string, string> | undefined)?.["info.json"];
  }
  if (! path_in_archive) {
    throw new Error("No koromo info.json file found in this archive!\n");
  }
  //    #Extract info.json

  let filepath = path_in_archive;
  //    #Open it

  let stringjson = "";
  let fh = filepath;
  if (fh === undefined) { throw new Error(`Could not open ${filepath}!\n`); }
  for (let row of (fh ?? "").split(/\r?\n/)) {
    row = perlCompat.chomp(row);
    stringjson += row;
  }
  //    #Use Mojo::JSON to decode the string into a hash

  let hashjson = JSON.parse(stringjson);
  logger.debug(`Found and loaded the following JSON: ${stringjson}`);
  //    #Parse it

  let [tags, title] = tags_from_koromo_json(hashjson);
  //    #Delete it

  ;
  //    #Return tags

  logger.info(`Sending the following tags to LRR: ${tags}`);
  if (title) {
    logger.info(`Parsed title is ${title}`);
    return { tags: tags, title: title };
  } else {
    return { tags: tags };
  }
}

function tags_from_koromo_json(...args: any[]) {
  let hash = args[0];
  let found_tags = [] as any[];
  let title = hash["Title"];
  let tags = hash["Tags"];
  let characters = hash["Characters"];
  let series = hash["Series"];
  let magazine = hash["Magazine"];
  let parody = hash["Parody"];
  let groups = hash["Groups"];
  let artist = hash["Artist"];
  let artists = hash["Artists"];
  let language = hash["Language"];
  let type = hash["Types"];
  let url = hash["URL"];
  handle_tag_yaml("", tags, found_tags);
  handle_tag_yaml("character:", characters, found_tags);
  handle_tag_yaml("series:", series, found_tags);
  handle_tag_yaml("group:", groups);
  handle_tag_yaml("artist:", artists, found_tags);
  handle_tag_yaml("series:", parody, found_tags);
  handle_tag_yaml("artist:", artist, found_tags);
  handle_tag_yaml("magazine:", magazine, found_tags);
  handle_tag_yaml("language:", language, found_tags);
  handle_tag_yaml("category:", type, found_tags);
  handle_tag_yaml("source:", url, found_tags);
  //    #Done-o

  let concat_tags = found_tags.join(", ");
  return [concat_tags, title];
}

function handle_tag_yaml(...args: any[]) {
  let namespace = args[0];
  let yamldata = args[1];
  //    # Check if array or string, don't iterate if string

  if (Array.isArray(yamldata)) {
    for (let tag of yamldata) {
      args[2].push(`${namespace}${tag}`);
    }
  } else if ((yamldata !== undefined && yamldata !== null)) {
    args[2].push(`${namespace}${yamldata}`);
  }
}
