// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/Koromo.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.

export function pluginInfo() {
  return {
    namespace: "koromoplugin",
    type: "metadata" as const,
    parameters: [
    ],
    declared_permissions: { net: [], read: false, write: true },
    name: "koromo",
    author: "thelastfantasy",
    description: "Collects metadata embedded into your archives as Koromo-style Info.json files. ( {'Tags': [xxx] } syntax)",
    version: "0.1",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABhGlDQ1BJQ0MgcHJvZmlsZQAAKJF9kT1Iw1AUhU9TpVoqDmYQcchQnSyIijhKFYtgobQVWnUweekfNDEkKS6OgmvBwZ/FqoOLs64OroIg+APi4uqk6CIl3pcUWsR44fE+zrvn8N59gNCoMs3qGgc03TbTibiUy69IoVeE0QsRAYgys4xkZiEL3/q6pz6quxjP8u/7s/rUgsWAgEQ8ywzTJl4nnt60Dc77xCIryyrxOfGYSRckfuS64vEb55LLAs8UzWx6jlgklkodrHQwK5sa8RRxVNV0yhdyHquctzhr1Rpr3ZO/MFLQlzNcpzWMBBaRRAoSFNRQQRU2YrTrpFhI03ncxz/k+lPkUshVASPHPDagQXb94H/we7ZWcXLCS4rEge4Xx/kYAUK7QLPuON/HjtM8AYLPwJXe9m80gJlP0uttLXoE9G8DF9dtTdkDLneAwSdDNmVXCtISikXg/Yy+KQ8M3ALhVW9urXOcPgBZmtXSDXBwCIyWKHvN5909nXP7t6c1vx8dzXKFeWpUawAAAAZiS0dEAOwAEABqpSa6lwAAAAlwSFlzAAAuIwAALiMBeKU/dgAAAAd0SU1FB+MKCRQBJSKMeg0AAAGVSURBVDjLpZMxa9tQFIXPeaiyhxiZzKFjBme1JFfYgYAe9Bd0yA8JIaQhkJLBP6T/wh3qpZYzm2I8dyilJJMTW7yTIVGRFasE8uAt93K+d+5991IS8Ybj1SVIer24ty8Jk2wyl5S/GkDSi+O4s9PaOYOQh91wSHK2DeLViVut1pmkTwAQtAPUQcz/xCRBEpKOg3ZwEnbDDklvK6AQ+77fds4tSJbBcM7Nm83GbhXiVcXj8fiHpO/WWgfgHAAkXYxGoy8k/UG/nzxDnsqRxF7cO0iS5AhAQxKLm6bpVZqmn8sxAI3kQ2KjKDqQ9GRFEqDNfpQcukrMkDRF3ADAJJvM1+v1n0G/n5D0AcBaew3gFMCFtfbyuVT/cHCYrFarX1mWLQCgsAWSXtgNO81mY/ed7380xpyUn3XOXefr/Ntyufw9vZn+LL7zn21J+fRmOru/f/hrjNmThFLOGWPeV8UvBklSTnIWdsNh0A4g6RiAI/n17vZuWBVvncQNSBAYEK5OvNGDbSMdRdE+AJdl2aJumfjWdX4EIwDvDt7UjSEAAAAASUVORK5CYII=",
    sidecar_files: ["Info.json", "info.json"],
  };
}


export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = legacyCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  interface ExecMetadataInfo extends Required<Pick<MetadataHostArgs, "file_path">> {
    user_agent: LegacyUserAgent;
    user_agent_cookies?: LegacyCookie[];
  }
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as unknown as ExecMetadataInfo;
  let logger = legacyCompat.getLogger("koromo", "plugins");
  let file = lrr_info["file_path"];
  let path_in_archive = (hostArgs.sidecar_files as Record<string, string> | undefined)?.["Info.json"];
  if (!(path_in_archive)) {
    path_in_archive = (hostArgs.sidecar_files as Record<string, string> | undefined)?.["info.json"];
  }
  if (! path_in_archive) {
    throw new PluginErrorException("No koromo info.json file found in this archive!");
  }
  let filepath = path_in_archive;
  let stringjson = "";
  let fh = filepath;
  if (fh === undefined) { throw new PluginErrorException("Could not open file", { filepath }); }
  for (let row of (fh ?? "").split(/\r?\n/)) {
    row = legacyCompat.chomp(row);
    stringjson += row;
  }
  let hashjson = JSON.parse(stringjson);
  logger.debug(`Found and loaded the following JSON: ${stringjson}`);
  let [tags, title] = tags_from_koromo_json(hashjson);
  ;
  logger.info(`Sending the following tags to LRR: ${tags}`);
  if (title) {
    logger.info(`Parsed title is ${title}`);
    return { tags: tags, title: title };
  } else {
    return { tags: tags };
  }
}

function tags_from_koromo_json(...args: any[]) {
  let hash = args[0];
  let found_tags = [] as any[];
  let title = hash["Title"];
  let tags = hash["Tags"];
  let characters = hash["Characters"];
  let series = hash["Series"];
  let magazine = hash["Magazine"];
  let parody = hash["Parody"];
  let groups = hash["Groups"];
  let artist = hash["Artist"];
  let artists = hash["Artists"];
  let language = hash["Language"];
  let type = hash["Types"];
  let url = hash["URL"];
  handle_tag_yaml("", tags, found_tags);
  handle_tag_yaml("character:", characters, found_tags);
  handle_tag_yaml("series:", series, found_tags);
  handle_tag_yaml("group:", groups);
  handle_tag_yaml("artist:", artists, found_tags);
  handle_tag_yaml("series:", parody, found_tags);
  handle_tag_yaml("artist:", artist, found_tags);
  handle_tag_yaml("magazine:", magazine, found_tags);
  handle_tag_yaml("language:", language, found_tags);
  handle_tag_yaml("category:", type, found_tags);
  handle_tag_yaml("source:", url, found_tags);
  let concat_tags = found_tags.join(", ");
  return [concat_tags, title];
}

function handle_tag_yaml(...args: any[]) {
  let namespace = args[0];
  let yamldata = args[1];
  if (Array.isArray(yamldata)) {
    for (let tag of yamldata) {
      args[2].push(`${namespace}${tag}`);
    }
  } else if ((yamldata !== undefined && yamldata !== null)) {
    args[2].push(`${namespace}${yamldata}`);
  }
}
