// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/Ksk.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//
// Hand-fixed: the converter originally bound all 2 declared parameters to the same single
// `hostArgs.arg` value (a since-fixed host-side limitation) — now reads the real per-parameter
// values from `hostArgs.customargs`, positionally matching `pluginInfo().parameters`.

export function pluginInfo() {
  return {
    namespace: "kskyamlmeta",
    type: "metadata" as const,
    parameters: [
      { name: "param1", description: "Assume english", required: false, type: "bool" },
      { name: "param2", description: "Add 'Released' tag", required: false, type: "bool" },
    ],
    declared_permissions: { net: [], read: false, write: true },
    name: "Koushoku/Koharu.yaml",
    author: "thelastfantasy",
    description: "Collects metadata embedded into your archives as koushoku.yaml/info.yaml files.",
    version: "0.1",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAFiUAABYlAUlSJPAAAANkSURBVDhPJZJpU5NXGIbf/9Ev0g+MM7Udp9WWDsVOsRYQKEVZQ4BsZnt9sy9shgShBbTYaTVCKY1B1pBEQggGFOogKEvYdOoXfszVQ/rhmTkz59zXc9/PeaRO12163DZCbgc+8y06HTJ+h5UOp4xLvoXdoOFBf5Auu4LS3obc0oJDp8VhNtLlcyN1uRWcZj13vS5cBi1+mwWPYiLY6cYjG+lxKoR8LgHpw9BQz+OBAbS1tch6DR1uO1Kox4dWVcfdDg9uswGnVSc66wn47QJmwtreTEPFVZxCoKosJ3hbRmlpRt8kNEIrdfscNN+o4tfeHhz6VhHBgqG1nsHeDpxGDV6zDkWjIvxLH25tK2+WUkzcG8JrNdJ/x4803NuJrr4G7Y/X8+UWIl1TDUGfgsfUjl2nwm/WMjrUh72tEXXFNYoKP+b74ks4FQOStuEnVNVlWBtv8kBYcmhVBJwWLOo6vKY2fvbaSD0ZxdnWxKWCj1CVXiEyPIBVuAz6bUiySc0dj0zAbsZtaM1fRH4fwm/RMDYYYCP2lNnfBsn89ZghxcIjMfmxng5GQ92ExIwkj6Kn5UYF6uofhMUG2mvLycYi7GaTnKwvk0vH+XctzXE6weupCFvRCP9MjLMx+Tfdulak4s8KqSr5kppvLmNT3WRQWN5Oz7ObibObnmMnMSXECxwtxdidi7L+Z5jlP0bYnJnEKX5PUpeVshqdINzl475dZnN+kqPsIocrApCa5fVchP3kDAeLc3nQ1vQTNqcjbCZncbQ3It1XZLLhR7wUtTMZZWd2Ugj+f3yYjpFLzbC/OM1BZoHcygJ7KeFEuHu7lsJmViN5G+o4jsd5+fAhKyMjecDJUoK9xDTH4uG753E+bCxxtJpkX5xzmQS5FyniU2MYNCKCsbo8b/84GWf7aZSt2Wi+81kdPU+wPj1OOOAhIHbi3Yu0GGqS07evqCv7llCXA+n6VxcpKTzHwsgwH1bTvBf0g7NOwu7J6jPGQn4iQ4H8XPZErNPNdYIWPZfPn6OvUwDUlVe59vknfHe+gLGAn9PtNQ7XnpHLJjgUdQZ6vy4iCMDxaiq/D8WFBXx9oZCA+DFJI3agougiVV9cyEOqij6l32UkFr6Xz7yfibG3PM/eSoLs1Di2+loaS0uovFIkFlDhPxYUixj0Cgg3AAAAAElFTkSuQmCC",
    sidecar_files: ["koushoku.yaml", "info.yaml"],
  };
}


export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = legacyCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  interface ExecMetadataInfo extends Required<Pick<MetadataHostArgs, "file_path" | "customargs">> {
    user_agent: LegacyUserAgent;
    user_agent_cookies?: LegacyCookie[];
  }
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as unknown as ExecMetadataInfo;
  let [assume_english, add_released] = lrr_info.customargs;
  let logger = legacyCompat.getLogger("Koushoku/Koharu.yaml", "plugins");
  let file = lrr_info["file_path"];
  let path_in_archive = (hostArgs.sidecar_files as Record<string, string> | undefined)?.["koushoku.yaml"];
  if (! path_in_archive) {
    path_in_archive = (hostArgs.sidecar_files as Record<string, string> | undefined)?.["info.yaml"];
  }
  if (! path_in_archive) {
    throw new PluginErrorException("No KSK metadata file found in archive");
  }
  let filepath = path_in_archive;
  let parsed_data = LoadFile(filepath);
  let [tags, title] = tags_from_ksk_yaml(parsed_data, assume_english, add_released);
  ;
  logger.info(`Sending the following tags to LRR: ${tags}`);
  if (title) {
    logger.info(`Parsed title is ${title}`);
    return { tags: tags, title: title };
  } else {
    return { tags: tags };
  }
}

function tags_from_ksk_yaml(...args: any[]) {
  let hash = args[0];
  let assume_english = args[1];
  let add_released = args[2];
  let found_tags = [] as any[];
  let logger = legacyCompat.getLogger("Koushoku/Koharu.yaml", "plugins");
  let title = hash["Title"];
  let tags = hash["Tags"];
  let parody = hash["Parody"];
  let artists = hash["Artist"];
  let magazine = hash["Magazine"];
  let url = hash["URL"];
  let released = hash["Released"];
  handle_tag_yaml("", tags, found_tags);
  handle_tag_yaml("artist:", artists, found_tags);
  handle_tag_yaml("series:", parody, found_tags);
  handle_tag_yaml("magazine:", magazine, found_tags);
  if (! (title !== undefined && title !== null)) {
    title = hash["title"];
  }
  handle_tag_yaml("", hash["general"], found_tags);
  handle_tag_yaml("male:", hash["male"], found_tags);
  handle_tag_yaml("female:", hash["female"], found_tags);
  handle_tag_yaml("mixed:", hash["mixed"], found_tags);
  handle_tag_yaml("other:", hash["other"], found_tags);
  handle_tag_yaml("artist:", hash["artist"], found_tags);
  handle_tag_yaml("circle:", hash["circle"], found_tags);
  handle_tag_yaml("parody:", hash["parody"], found_tags);
  handle_tag_yaml("magazine:", hash["magazine"], found_tags);
  handle_tag_yaml("language:", hash["language"], found_tags);
  handle_tag_yaml("source:", hash["source"], found_tags);
  if (assume_english) {
    found_tags.push("language:english");
  }
  if (add_released && released !== "") {
    found_tags.push("date_released:" + released);
  }
  if (!(! url)) { found_tags.push("source:" + url); }
  let concat_tags = found_tags.join(", ");
  return [concat_tags, title];
}

function handle_tag_yaml(...args: any[]) {
  let namespace = args[0];
  let yamldata = args[1];
  if (Array.isArray(yamldata)) {
    for (let tag of yamldata) {
      args[2].push(`${namespace}${tag}`);
    }
  } else if ((yamldata !== undefined && yamldata !== null)) {
    args[2].push(`${namespace}${yamldata}`);
  }
}
