// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/MEMS.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-09.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - =~ with /g in list context (/e(?:x|-)hentai\.org\/g\/(\d+)\/([0-9a-z]+)/i) — Perl returns 
//     every captured group across all matches; JS .match() with /g returns only full-match strings, 
//     not captures. Verify this call site by hand.
//   - =~ with /g in list context (/source:e(?:x|-)hentai\.org\/g\/(\d+)\/([0-9a-z]+)/i) — Perl 
//     returns every captured group across all matches; JS .match() with /g returns only full-match 
//     strings, not captures. Verify this call site by hand.
//   - external Perl module reference has no JS equivalent: 
//     LANraragi::Plugin::Metadata::EHentai::get_tags_from_EH
//   - this plugin declares 3 custom parameters, but the host currently passes only one generic 
//     `arg` value per call — only `param1` was mapped to it; the rest were also bound to that same 
//     value and need manual attention before this plugin can work correctly

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

export function pluginInfo() {
  return {
    namespace: "memsplugin",
    type: "metadata" as const,
    parameters: [
      { name: "param1", description: "Save the original Japanese title when available instead of the English or ", required: false },
      { name: "param2", description: "Save additional timestamp (time posted) and uploader metadata", required: false },
      { name: "param3", description: "Use ExHentai link for source instead of E-Hentai link", required: false },
    ],
    declared_permissions: { net: [], read: false, write: false },
    name: "Mayriad's EH Master Script",
    author: "Mayriad (ported)",
    description: "Accurately retrieves metadata from e-hentai.org using the identifiers appeneded to the ",
    version: "1.2",
    icon: "data:image/png;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAA",
    oneshot_arg: "Enter a valid EH gallery URL to copy metadata from this EH gallery to this LANraragi archive",
    login_from: "ehlogin",
  };
}


export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = perlCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  let match: RegExpMatchArray | null;
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as Record<string, any>;
  let ua = lrr_info["user_agent"];
  let logger = perlCompat.getLogger("Mayriad's EH Master Script", "plugins");
  let gallery_id = '';
  let gallery_token = '';
  let save_jpn_title = hostArgs.arg as string;
  let save_additional_metadata = hostArgs.arg as string;
  let use_exhentai = hostArgs.arg as string;
  //    # Use the URL from oneshot parameters or source tag first when applicable.

  if ((match = lrr_info["oneshot_param"].match(/e(?:x|-)hentai\.org\/g\/(\d+)\/([0-9a-z]+)/i))) {
    gallery_id = match[1];
    gallery_token = match[2];
    logger.debug(`Directly using gallery ID ${gallery_id} and token ${gallery_token} from oneshot parameters.`);
  } else if ((match = lrr_info["existing_tags"].match(/source:e(?:x|-)hentai\.org\/g\/(\d+)\/([0-9a-z]+)/i))) {
    gallery_id = match[1];
    gallery_token = match[2];
    logger.debug(`Directly using gallery ID ${gallery_id} and token ${gallery_token} from source tag.`);
  } else {
    (gallery_id, gallery_token) = ((match = lrr_info["archive_title"].match(/.+? \[GID (\d+) GT ([0-9a-z]+)\]/)));
    if (gallery_id === '' || gallery_token === '') {
      let file_error = 'Skipping archive without connecting to EH, because the archive title does not have valid ' + 'gallery identifiers from Mayriad\'s EH Master Script.';
      logger.error(file_error);
      throw new Error(`${file_error}\n`);
    }
  }
  //    # Retrieve metadata directly using EH API.

  logger.info('Source identified. Calling E-Hentai metadata plugin to retrieve metadata from EH API.');
  let [eh_all_tags, eh_title] = LANraragi_Plugin_Metadata_EHentai_get_tags_from_EH(ua, gallery_id, gallery_token, save_jpn_title, save_additional_metadata);
  //    # Add source URL and title if possible.

  if (eh_all_tags !== "") {
    //        # Title is always updated to hide the identifiers and also to reflect title changes due to rename petitions.
  
    let metadata: Record<string, any> = { tags: eh_all_tags, title: eh_title };
    //        # Add the source tag outside get_tags_from_EH(), so that this tag is only added when metadata has been
  
    //        # successfully retrieved; otherwise $metadata{tags} may only contain this source tag and truly untagged
  
    //        # galleries may be incorrectly hidden.
  
    let host = (use_exhentai ? 'exhentai.org' : 'e-hentai.org');
    metadata["tags"] += `, source:${host}/g/${gallery_id}/${gallery_token}`;
    //        # Return a hash containing the new metadata to be added to LRR.
  
    return metadata;
  } else {
    let source_error = 'No matching EH gallery found. The archive title may have incorrect gallery identifiers.';
    logger.error(source_error);
    throw new Error(`${source_error}\n`);
  }
}
