// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/MEMS.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Hand-fixed since the last regeneration (the converter's own "known limitations" warnings for
// this file — a stale `/g`-flag false alarm against regexes that were never `/g` to begin with,
// plus a genuine one below — no longer apply, both resolved):
//   - the converter originally bound all 3 declared parameters to the same single `hostArgs.arg`
//     value (a since-fixed host-side limitation) — now reads the real per-parameter values from
//     `hostArgs.customargs`, positionally matching `pluginInfo().parameters`.
//   - `(gallery_id, gallery_token) = (match = ...)` was a literal, non-compiling transliteration
//     of Perl's list-assignment-from-a-regex-match idiom (`($a, $b) = ($str =~ /regex/)`) — no
//     such JS syntax exists; rewritten to explicitly destructure `match[1]`/`match[2]`.
//   - `LANraragi::Plugin::Metadata::EHentai::get_tags_from_EH` (a direct call into a *different*
//     Perl package by its fully qualified name — legacy plugins can do this freely) has no JS
//     equivalent, since each converted plugin here is its own standalone Deno subprocess with no
//     shared module graph — `get_tags_from_EH`/`get_json_from_EH` are inlined at the bottom of
//     this file (copied from `plugins/metadata/ehentai.ts`'s own identical private helpers)
//     instead of attempting a cross-plugin import the runtime has no mechanism for.

export function pluginInfo() {
  return {
    namespace: "memsplugin",
    type: "metadata" as const,
    parameters: [
      { name: "param1", description: "Save the original Japanese title when available instead of the English or romanised title", required: false, type: "bool" },
      { name: "param2", description: "Save additional timestamp (time posted) and uploader metadata", required: false, type: "bool" },
      { name: "param3", description: "Use ExHentai link for source instead of E-Hentai link", required: false, type: "bool" },
    ],
    // This plugin's own inlined `get_tags_from_EH`/`get_json_from_EH` (see their own docs below)
    // call the same E-Hentai JSON API `plugins/metadata/ehentai.ts` does.
    declared_permissions: { net: ["api.e-hentai.org"], read: false, write: false },
    name: "Mayriad's EH Master Script",
    author: "thelastfantasy",
    description:
      "Accurately retrieves metadata from e-hentai.org using the identifiers appeneded to the " +
      "filenames of archives downloaded by Mayriad's EH Master Script.",
    version: "0.1",
    icon: "data:image/png;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wARBmb/EQZm/xEGZv8RBmb/EQZm/////wD///8A////ABEGZv8RBmb/////AP///wARBmb/EQZm/////wD///8AEQZm/xEGZv8RBmb/EQZm/xEGZv////8A////AP///wARBmb/EQZm/////wD///8AEQZm/xEGZv////8A////ABEGZv8RBmb/////AP///wD///8A////AP///wD///8AEQZm/xEGZv////8A////ABEGZv8RBmb/////AP///wARBmb/EQZm/////wD///8A////AP///wD///8A////ABEGZv8RBmb/////AP///wARBmb/EQZm/////wD///8AEQZm/xEGZv////8A////AP///wD///8A////AP///wARBmb/EQZm/////wD///8AEQZm/xEGZv////8A////ABEGZv8RBmb/EQZm/xEGZv////8AEQZm/xEGZv////8AEQZm/xEGZv8RBmb/EQZm/xEGZv8RBmb/////AP///wARBmb/EQZm/xEGZv8RBmb/////ABEGZv8RBmb/////ABEGZv8RBmb/EQZm/xEGZv8RBmb/EQZm/////wD///8AEQZm/xEGZv////8A////AP///wD///8A////AP///wARBmb/EQZm/////wD///8AEQZm/xEGZv////8A////ABEGZv8RBmb/////AP///wD///8A////AP///wD///8AEQZm/xEGZv////8A////ABEGZv8RBmb/////AP///wARBmb/EQZm/////wD///8A////AP///wD///8A////ABEGZv8RBmb/////AP///wARBmb/EQZm/////wD///8AEQZm/xEGZv8RBmb/EQZm/xEGZv////8A////AP///wARBmb/EQZm/////wD///8AEQZm/xEGZv////8A////ABEGZv8RBmb/EQZm/xEGZv8RBmb/////AP///wD///8AEQZm/xEGZv////8A////ABEGZv8RBmb/////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A//8AAP//AACDmQAAg5kAAJ+ZAACfmQAAn5kAAISBAACEgQAAn5kAAJ+ZAACfmQAAg5kAAIOZAAD//wAA//8AAA==",
    oneshot_arg: "Enter a valid EH gallery URL to copy metadata from this EH gallery to this LANraragi archive",
    login_from: "ehlogin",
    // Same real pattern as `plugins/metadata/ehentai.ts` — this plugin is just as much an
    // E-Hentai/ExHentai-URL-based metadata source (see `oneshot_arg` above), but had no
    // `url_pattern` at all, so the frontend's priority-ordered `findMatchingPlugin` skipped past
    // it (a plugin with no pattern never matches) straight to `ehentai.ts` even when this plugin
    // was configured as the higher-priority match for the same URL.
    url_pattern: "e-?hentai\\.org|exhentai\\.org",
  };
}


export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = legacyCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  interface ExecMetadataInfo extends Required<Pick<MetadataHostArgs, "arg" | "existing_tags" | "archive_title" | "customargs">> {
    user_agent: LegacyUserAgent;
    user_agent_cookies?: LegacyCookie[];
  }
  let match: RegExpMatchArray | null;
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as unknown as ExecMetadataInfo;
  let ua = lrr_info["user_agent"];
  let logger = legacyCompat.getLogger("Mayriad's EH Master Script", "plugins");
  let gallery_id = '';
  let gallery_token = '';
  let [save_jpn_title, save_additional_metadata, use_exhentai] = lrr_info.customargs;
  if ((match = (lrr_info["arg"] ?? "").match(/e(?:x|-)hentai\.org\/g\/(\d+)\/([0-9a-z]+)/i))) {
    gallery_id = match[1];
    gallery_token = match[2];
    logger.debug(`Directly using gallery ID ${gallery_id} and token ${gallery_token} from oneshot parameters.`);
  } else if ((match = lrr_info["existing_tags"].match(/source:e(?:x|-)hentai\.org\/g\/(\d+)\/([0-9a-z]+)/i))) {
    gallery_id = match[1];
    gallery_token = match[2];
    logger.debug(`Directly using gallery ID ${gallery_id} and token ${gallery_token} from source tag.`);
  } else {
    match = lrr_info["archive_title"].match(/.+? \[GID (\d+) GT ([0-9a-z]+)\]/);
    gallery_id = match?.[1] ?? '';
    gallery_token = match?.[2] ?? '';
    if (gallery_id === '' || gallery_token === '') {
      let file_error = 'Skipping archive without connecting to EH, because the archive title does not have valid ' + 'gallery identifiers from Mayriad\'s EH Master Script.';
      logger.error(file_error);
      throw new PluginErrorException(file_error);
    }
  }
  logger.info('Source identified. Calling E-Hentai metadata plugin to retrieve metadata from EH API.');
  let [eh_all_tags, eh_title] = await get_tags_from_EH(ua, gallery_id, gallery_token, save_jpn_title, save_additional_metadata);
  if (eh_all_tags !== "") {
    let metadata: Record<string, any> = { tags: eh_all_tags, title: eh_title };
    let host = (use_exhentai ? 'exhentai.org' : 'e-hentai.org');
    metadata["tags"] += `, source:${host}/g/${gallery_id}/${gallery_token}`;
    return metadata;
  } else {
    let source_error = 'No matching EH gallery found. The archive title may have incorrect gallery identifiers.';
    logger.error(source_error);
    throw new PluginErrorException(source_error);
  }
}

// Inlined from `plugins/metadata/ehentai.ts`'s own identically-named private helpers — legacy's
// `MEMS.pm` calls `LANraragi::Plugin::Metadata::EHentai::get_tags_from_EH` directly by its fully
// qualified Perl package name (`~/LANraragi/lib/LANraragi/Plugin/Metadata/MEMS.pm:84-85`), which
// has no equivalent here: each converted plugin is its own standalone Deno subprocess entry
// point with no shared module graph between them (constitution Principle IV), so this plugin
// carries its own copy rather than attempting a cross-plugin import that the runtime has no
// mechanism for.
async function get_tags_from_EH(ua: any, gID: any, gToken: any, jpntitle: any, additionaltags: any) {
  let logger = legacyCompat.getLogger("Mayriad's EH Master Script", "plugins");
  let jsonresponse = await get_json_from_EH(ua, gID, gToken);
  let data = jsonresponse["gmetadata"];
  let tags = data[0]["tags"];
  let ehtitle = data[0][(jpntitle ? "title_jpn" : "title")];
  if (ehtitle === "" && jpntitle) {
    ehtitle = data[0]["title"];
  }
  let ehcat = data[0]["category"].toLowerCase();
  tags.push(`category:${ehcat}`);
  if (additionaltags) {
    let ehuploader = data[0]["uploader"];
    let ehtimestamp = data[0]["posted"];
    tags.push(`uploader:${ehuploader}`);
    tags.push(`timestamp:${ehtimestamp}`);
  }
  ehtitle = legacyCompat.htmlUnescape(ehtitle);
  let ehtags = tags.join(', ');
  logger.info(`Sending the following tags to LRR: ${ehtags}`);
  return [ehtags, ehtitle];
}

async function get_json_from_EH(ua: any, gID: any, gToken: any) {
  let uri = 'https://api.e-hentai.org/api.php';
  let logger = legacyCompat.getLogger("Mayriad's EH Master Script", "plugins");
  let rep = (await ua.post(uri, "json", {method: "gdata", gidlist: [[gID, gToken]], namespace: 1})).result;
  let textrep = rep.body;
  logger.debug(`E-H API returned this JSON: ${textrep}`);
  let jsonresponse = rep.json;
  if ((jsonresponse["error"] !== undefined)) {
    logger.error(jsonresponse["error"]);
    throw new PluginErrorException("E-H API returned an error.");
  }
  return jsonresponse;
}
