// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/nHentai.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - =~ with /g in list context (/\{(\d*)\}.*$/gm) — Perl returns every captured group across all 
//     matches; JS .match() with /g returns only full-match strings, not captures. Verify this call 
//     site by hand.
//   - =~ with /g in list context (/.*\/g\/([0-9]+).*/) — Perl returns every captured group across 
//     all matches; JS .match() with /g returns only full-match strings, not captures. Verify this 
//     call site by hand.
//   - =~ with /g in list context (/.*source:\s*(?:https?:\/\/)?nhentai\.net\/g\/([0-9]*).*/gi) — 
//     Perl returns every captured group across all matches; JS .match() with /g returns only 
//     full-match strings, not captures. Verify this call site by hand.
//
export function pluginInfo() {
  return {
    namespace: "nhplugin",
    type: "metadata" as const,
    url_pattern: "nhentai\\.net",
    domain_match: ["nhentai.net"],
    parameters: [
      { name: "param1", description: "Fetch date uploaded and set timestamp tag", required: false, type: "bool" },
      // Only `title` has a japanese variant on the real API response — tags/artists/groups are
      // romanized-only, no japanese field exists for them.
      { name: "param2", description: "Prefer the Japanese title over the romanized one, when available", required: false, type: "bool" },
    ],
    declared_permissions: { net: ["nhentai.net"], read: false, write: false },
    name: "nHentai",
    author: "thelastfantasy",
    description: "Searches nHentai for tags matching your archive.\n          <br>Supports reading the ID from files formatted as \"{Id} Title\" and if not, tries to search for a matching gallery.\n          <br><i class='fa fa-exclamation-circle'></i> This plugin will use the source: tag of the archive if it exists.",
    version: "0.1",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA\nB3RJTUUH4wYCFA8s1yKFJwAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUH\nAAACL0lEQVQ4y6XTz0tUURQH8O+59773nLFcaGWTk4UUVCBFiJs27VxEQRH0AyRo4x8Q/Qtt2rhr\nU6soaCG0KYKSwIhMa9Ah+yEhZM/5oZMG88N59717T4sxM8eZCM/ycD6Xwznn0pWhG34mh/+PA8mk\n8jO5heziP0sFYwfgMDFQJg4IUjmquSFGG+OIlb1G9li5kykgTgvzSoUCaIYlo8/Igcjpj5wOkARp\n8AupP0uzJLijCY4zzoXOxdBLshAgABr8VOp7bpAXDEI7IBrhdksnjNr3WzI4LaIRV9fk2iAaYV/y\nA1dPiYjBAALgpQxnhV2XzTCAGWGeq7ACBvCdzKQyTH+voAm2hGlpcmQt2Bc2K+ymAhWPxTzPDQLt\nOKo1FiNBQaArq9WNRQwEgKl7XQ1duzSRSn/88vX0qf7DPQddx1nI5UfHxt+m0sLYPiP3shRAG8MD\nok1XEEXR/EI2ly94nrNYWG6Nx0/2Hp2b94dv34mlZge1e4hVCJ4jc6tl9ZP803n3/i4lpdyzq2N0\n7M3DkSeF5ZVYS8v1qxcGz5+5eey4nPDbmGdE9FpGeWErVNe2tTabX3r0+Nk3PwOgXFkdfz99+exA\nMtFZITEt9F23mpLG0hYTVQCKpfKPlZ/rqWKpYoAPcTmpginW76QBbb0OBaBaDdjaDbNlJmQE3/d0\nMYoaybU9126oPkrEhpr+U2wjtoVVGBowkslEsVSupRKdu0Mduq7q7kqExjSS3V2dvwDLavx0eczM\neAAAAABJRU5ErkJggg==",
    oneshot_arg: "nHentai Gallery URL (Will attach tags matching this exact gallery to your archive)",
    login_from: "nhapiauth",
  };
}


export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = legacyCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
    const headers = (info.user_agent_headers ?? {}) as Record<string, string>;
    if (Object.keys(headers).length > 0) {
      info.user_agent.on("start", (_ua: any, tx: any) => {
        for (const [name, value] of Object.entries(headers)) tx.req.headers.header(name, value);
      });
    }
  }
  interface ExecMetadataInfo extends Required<Pick<MetadataHostArgs, "arg" | "existing_tags" | "file_path" | "customargs">> {
    user_agent: LegacyUserAgent;
    user_agent_cookies?: LegacyCookie[];
  }
  let match: RegExpMatchArray | null;
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as unknown as ExecMetadataInfo;
  let ua = lrr_info["user_agent"];
  // Was `hostArgs.arg` — that's the oneshot gallery URL, not param1's persisted value.
  // customargs[0]/[1] are the real settings-page values for param1/param2.
  let add_uploaded = (lrr_info.customargs?.[0] as boolean | undefined) ?? false;
  let prefer_japanese_title = (lrr_info.customargs?.[1] as boolean | undefined) ?? false;
  let logger = legacyCompat.getLogger("nHentai", "plugins");
  let galleryID = "";
  if ((match = (lrr_info["arg"] ?? "").match(/.*\/g\/([0-9]+).*/))) {
    galleryID = match[1];
    logger.debug(`Skipping search and using gallery ${galleryID} from oneshot args`);
  } else if ((match = lrr_info["existing_tags"].match(/.*source:\s*(?:https?:\/\/)?nhentai\.net\/g\/([0-9]*).*/gi))) {
    galleryID = match[1];
    logger.debug(`Skipping search and using gallery ${galleryID} from source tag`);
  } else {
    logger.debug("Searching gallery by title (filename)");
    let file_path = legacyCompat.redis_decode(lrr_info["file_path"]);
    galleryID = await get_gallery_id_from_title(file_path, ua);
  }
  if (! galleryID) {
    let message = "No matching nHentai Gallery Found!";
    logger.info(message);
    throw new PluginErrorException(message);
  }
  logger.debug(`Detected nHentai gallery ID is ${galleryID}`);
  let hashdata = await get_tags_from_nh(galleryID, ua, add_uploaded, prefer_japanese_title);
  logger.info("Sending the following tags to LRR: " + hashdata["tags"]);
  return hashdata;
}

async function get_search_json(...args: any[]) {
  let [title, ua] = args.slice(0);
  let logger = legacyCompat.getLogger("nHentai", "plugins");
  let URL = "https://nhentai.net/api/v2/search?query=" + encodeURIComponent(title);
  let res = (await ua.get(URL)).result;
  if (res.is_error) {
    let code = res.code;
    throw new PluginErrorException("Search gallery by title failed", { code });
  }
  logger.debug("Tentative JSON: " + res.body);
  // Was `JSON.parse(res).body` — `res` is the LegacyHttpResult object, not a string. `res.json`
  // (same idiom as chaika.ts) is correct.
  return res.json;
}

async function get_gallery_id_from_title(...args: any[]) {
  let match: RegExpMatchArray | null;
  let [file, ua] = args.slice(0);
  let [title, filepath, suffix] = legacyCompat.fileparse(file);
  let logger = legacyCompat.getLogger("nHentai", "plugins");
  if ((match = title.match(/\{(\d*)\}.*$/gm))) {
    logger.debug(`Got ${1} from file.`);
    return match[1];
  }
  let json = await get_search_json(title, ua);
  let results = json["result"];
  if (results.length > 0) {
    return results[0]["id"];
  }
  return;
}

async function get_json_from_nh(...args: any[]) {
  let [gID, ua] = args.slice(0);
  let logger = legacyCompat.getLogger("nHentai", "plugins");
  let URL = `https://nhentai.net/api/v2/galleries/${gID}`;
  let res = (await ua.get(URL)).result;
  if (res.is_error) {
    let code = res.code;
    throw new PluginErrorException("Error retrieving gallery from nHentai", { code });
  }
  logger.debug("Tentative JSON: " + res.body);
  // Same fix as `get_search_json` above — see that function's own comment.
  return res.json;
}

function get_tags_from_json(...args: any[]) {
  let [json] = args.slice(0);
  let json_tags = json["tags"];
  let tags = [];
  for (let tag of json_tags) {
    let namespace = tag["type"];
    let name = tag["name"];
    if (namespace === "tag") {
      tags.push(name);
    } else {
      tags.push(`${namespace}:${name}`);
    }
  }
  return tags;
}

function get_title_from_json(...args: any[]) {
  let [json, prefer_japanese] = args.slice(0);
  let title = json["title"];
  if (prefer_japanese && title["japanese"]) return title["japanese"];
  return title["pretty"];
}

function get_upload_from_json(...args: any[]) {
  let [json] = args.slice(0);
  return json["upload_date"];
}

async function get_tags_from_nh(...args: any[]) {
  let [gID, ua, add_uploaded, prefer_japanese_title] = args.slice(0);
  let hashdata: Record<string, any> = { tags: "" };
  let json = await get_json_from_nh(gID, ua);
  if (json) {
    let tags = get_tags_from_json(json);
    if (add_uploaded) {
      // Was `upload.join(", ")` — `upload_date` is a single number on the real API, not an array.
      let upload = get_upload_from_json(json);
      tags.push(`timestamp:${upload}`);
    }
    if ((tags.length > 0)) { tags.push(`source:nhentai.net/g/${gID}`); }
    hashdata["tags"] = tags.join(', ');
    hashdata["title"] = get_title_from_json(json, prefer_japanese_title);
  }
  return hashdata;
}
