// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/Pixiv.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Hand-fixed since regeneration:
//   - `Time::Piece->strptime(...)->epoch` reimplemented via `Date.UTC` (the one format Pixiv's
//     AJAX API ever produces: `YYYY-MM-DDTHH:MM:SS[+HH:MM]`, timezone offset already stripped by
//     the plugin itself before this call).
//   - Perl's `push(@array, @otherArray)` flattens; the converter's literal `array.push(otherArray)`
//     instead nested one array inside another — fixed to `array.push(...otherArray)` everywhere
//     this pattern occurs (`get_manga_data_from_dto`'s 3-tag push, and every `lrr_tags.push(...)`
//     call in `get_hash_metadata_from_json`).
//   - `Dumper(json)` (Perl's `Data::Dumper`) replaced with `JSON.stringify(json)`.
//   - `declared_permissions.net`: this plugin only ever calls `www.pixiv.net` (AJAX + HTML
//     fallback), verified against every URL literal in `execMetadata`'s call graph.
//
// NOT part of this pass: migrating this plugin's metadata-side HTTP flow to a new
// `download`-side contract — that's specs/005-download-plugin-progress's own separate,
// not-yet-implemented plan for `plugins/download/pixiv.ts`, a different file.

export function pluginInfo() {
  return {
    namespace: "pixivmetadata",
    type: "metadata" as const,
    parameters: [
      { name: "param1", description: "Comma-separated list of languages to support. Options: jp, en. Empty string defaults to original tags (jp) only.", required: false, type: "string" },
    ],
    declared_permissions: { net: ["www.pixiv.net"], read: false, write: false },
    name: "Pixiv",
    author: "thelastfantasy",
    description: "Retrieve metadata of a Pixiv artwork by its artwork ID.\n            <br>Supports ID extraction from these file formats: \"{{pixiv_id}} Title\", \"pixiv_{pixiv_id}\" or \"{pixiv_id} Title\".\n            <br>\n            <br><i class='fa fa-exclamation-circle'></i> Pixiv enforces a rate limit on API requests, and may suspend/ban your account for overuse.\n        ",
    version: "0.1",
    icon: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAAUABQDAREAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAwYABAUH/8QAJBAAAgICAgICAgMAAAAAAAAAAQIDBAUGABESIQcxImETQVH/xAAZAQACAwEAAAAAAAAAAAAAAAADBgACCAX/xAAoEQABBAEDAgYDAQAAAAAAAAABAgMEEQAFITESUQYTFEFhkTJxocH/2gAMAwEAAhEDEQA/ANfRvi3MbpRvZxrlfG4jHQT2J7U35PIsKB5FhjHuRgpHf0B5DsjvmrNV15nTHERwkrcWQABwOo0Co8AE/smjQzIWkeHn9VbXIKghpAUSTyekWQkckgV2G4s4fXNI1LeMkuuarsuQizVgEUYsnTSKG5IB2Iw6SN/GzdevIEE+uxwc3VJmlteqltJLQ/IoUSUjvRAsD3rf4wkHSYOru+khOqDp/ELSAFHtYUaJ9rFfOJFmtPTsy07UTRTQO0ciMOirKeiD+wRzvIWl1IWg2DuP1i642ppZbWKINEfIzpnwOHt5LaaE14QVzqeV/OTyMcRaNQXIUE/0O+gT64q+LKbajuJTZ85virNE7b/6cbvB9uPSWlKpPkO83QsDfa/4MFoFHVNE2jH7tsm54u5Dhplu16OLaSaxbmT2ie0VY18gO2Yj19A8Jq7szVYi4EVhSS4OkqXQSkHk8kk1wB95XRmYWjzG9QlyEqDZ6glFlSiNwOAAL5JPHtiHn8vNsGdyOesoqS5G3LbdV+laRyxA/XvjBEjJhx0R07hAA+hWLU2SqbJckrFFair7N4ClksjjWkbHX7NUzRmKQwyshdD9qej7B/w8u6y09QdSDW4sXR74Np91iy0opsUaJFjtt7ZX4XBZOTJn/9k=",
    oneshot_arg: "Pixiv artwork URL or illustration ID (e.g. pixiv.net/en/artworks/123456 or 123456.)",
    login_from: "pixivlogin",
    url_pattern: "pixiv\\.net",
  };
}


const ILLUST_ID_ONLY_PATTERN = /^\d+$/;
const ILLUST_ID_FROM_URL_PATTERN = /.*pixiv\.net\/.*artworks\/(\d+)/;
const ILLUST_ID_FROM_TITLE_STRONG_PATTERN = /pixiv_\{(\d*)\}.*$/;
const ILLUST_ID_FROM_TITLE_NO_BRACKETS_PATTERN = /pixiv_(\d+).*$/;
const ILLUST_ID_FROM_TITLE_WEAK_PATTERN = /^\{(\d*)\}.*$/;
const TRAILING_TZ_OFFSET_PATTERN = /(\+\d{2}:\d{2})$/;
const SANITIZE_STRIPPED_CHARS_PATTERN = /["?*%$:]/g;
const SANITIZE_UNDERSCORE_PATTERN = /_/g;
const SANITIZE_SPACE_DASH_PATTERN = / -/g;
const HTML_ERROR_MARKER_PATTERN = /^error/;

interface ExecMetadataInfo extends Required<Pick<MetadataHostArgs, "arg" | "archive_title">> {
  user_agent: LegacyUserAgent;
  user_agent_cookies?: LegacyCookie[];
}

export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = legacyCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
    const headers = (info.user_agent_headers ?? {}) as Record<string, string>;
    if (Object.keys(headers).length > 0) {
      info.user_agent.on("start", (_ua: any, tx: any) => {
        for (const [name, value] of Object.entries(headers)) tx.req.headers.header(name, value);
      });
    }
  }
  const lrr_info = hostArgs as unknown as ExecMetadataInfo;
  const ua = lrr_info.user_agent;
  const logger = legacyCompat.getLogger("Pixiv", "plugins");
  const tag_languages_str = (hostArgs.arg as string | undefined) ?? "";
  const illust_id = find_illust_id(lrr_info);
  if (!illust_id) {
    const message = "Failed to extract Pixiv ID!";
    logger.error(message);
    throw new PluginErrorException(message);
  }
  logger.debug(`Retrieved Pixiv illustration ID = ${illust_id}`);

  const metadata = await get_metadata_from_illust_id(illust_id, ua, tag_languages_str);
  logger.info("Sending the following tags to LRR: " + metadata.tags);
  return metadata;
}

/** Convert Pixiv's `YYYY-MM-DDTHH:MM:SS[+HH:MM]` timestamp format to a Unix epoch (seconds) —
 * a `Date.UTC`-based equivalent of `Time::Piece->strptime(...)->epoch` (the timezone offset
 * suffix, if present, is stripped first, matching the real Perl's own behavior exactly). */
function _convert_epoch_seconds(formattedDate: string): number | undefined {
  formattedDate = formattedDate.replace(TRAILING_TZ_OFFSET_PATTERN, "");
  const match = formattedDate.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})$/);
  if (!match) return undefined;
  const [, year, month, day, hour, minute, second] = match;
  return Date.UTC(Number(year), Number(month) - 1, Number(day), Number(hour), Number(minute), Number(second)) / 1000;
}

/** Sanitizes text per LRR's own search syntax rules
 * (https://sugoi.gitbook.io/lanraragi/basic-operations/searching). */
function sanitize(text: string): string {
  let sanitized_text = text;
  // replace nonseparator characters with empty str.
  sanitized_text = sanitized_text.replace(SANITIZE_STRIPPED_CHARS_PATTERN, "");
  // replace underscore with space.
  sanitized_text = sanitized_text.replace(SANITIZE_UNDERSCORE_PATTERN, " ");
  // if a dash is preceded by space, remove; otherwise keep.
  sanitized_text = sanitized_text.replace(SANITIZE_SPACE_DASH_PATTERN, " ");
  if (sanitized_text !== text) {
    const logger = legacyCompat.getLogger("Pixiv", "plugins");
    logger.info(`"${text}" was sanitized.`);
  }
  return sanitized_text;
}

function find_illust_id(lrr_info: ExecMetadataInfo): string {
  const oneshot_param = lrr_info.arg;
  const archive_title = lrr_info.archive_title;

  if (oneshot_param !== undefined) {
    // case 1: "$illust_id" i.e. string of digits.
    if (ILLUST_ID_ONLY_PATTERN.test(oneshot_param)) {
      return oneshot_param;
    }
    // case 2: URL-based embedding
    const urlMatch = oneshot_param.match(ILLUST_ID_FROM_URL_PATTERN);
    if (urlMatch) return urlMatch[1];
  }

  if (archive_title !== undefined) {
    // case 3: archive title extraction (strong pattern matching) — use strong pattern matching
    // if using multiple metadata plugins and archive title needs to exclusively call this one.
    let match = archive_title.match(ILLUST_ID_FROM_TITLE_STRONG_PATTERN);
    if (match) return match[1];
    // case 3.1: archive title extraction without brackets (for pixivdl compatibility)
    match = archive_title.match(ILLUST_ID_FROM_TITLE_NO_BRACKETS_PATTERN);
    if (match) return match[1];
    // case 4: archive title extraction (weak pattern matching)
    match = archive_title.match(ILLUST_ID_FROM_TITLE_WEAK_PATTERN);
    if (match) return match[1];
  }

  return "";
}

interface PixivTagEntry {
  tag: string;
  translation?: Record<string, string>;
}

interface PixivSeriesNavData {
  seriesId?: string | number;
  title?: string;
  order?: string | number;
}

interface PixivIllustDto {
  illustId: unknown;
  illustTitle?: string;
  userId?: string | number;
  userName?: string;
  illustComment: string;
  createDate: string;
  uploadDate: string;
  tags: { tags: PixivTagEntry[] };
  seriesNavData?: PixivSeriesNavData;
}

interface PixivFormattedJson {
  illust: Record<string, PixivIllustDto>;
}

function get_illustration_dto_from_json(json: PixivFormattedJson, illust_id: string): PixivIllustDto {
  // retrieve relevant data obj from json obj
  return json.illust[illust_id];
}

function get_manga_data_from_dto(dto: PixivIllustDto): string[] {
  // get manga-based data and return as an array.
  const manga_data: string[] = [];
  const series_nav_data = dto.seriesNavData;
  if (series_nav_data) {
    const series_id = series_nav_data.seriesId;
    let series_title = series_nav_data.title;
    const series_order = series_nav_data.order;
    if (series_id !== undefined && series_title !== undefined && series_order !== undefined) {
      series_title = sanitize(series_title);
      manga_data.push(`pixiv_series_id:${series_id}`, `pixiv_series_title:${series_title}`, `pixiv_series_order:${series_order}`);
    }
  }
  return manga_data;
}

function get_pixiv_tags_from_dto(dto: PixivIllustDto, tag_languages_str: string): string[] {
  const tags: string[] = [];
  // extract tag languages.
  let tag_languages: string[];
  if (tag_languages_str === "") {
    tag_languages = ["jp"];
  } else {
    tag_languages = tag_languages_str.split(",").map((lang) => lang.trim());
  }

  for (const item of dto.tags.tags) {
    // iterate over tagging language.
    for (const tag_language of tag_languages) {
      if (tag_language === "jp") {
        // add original/jp tags.
        if (item.tag !== undefined) {
          tags.push(sanitize(item.tag));
        }
      } else {
        // add translated tags.
        const translated_tag = item.translation?.[tag_language];
        if (translated_tag !== undefined) {
          tags.push(sanitize(translated_tag));
        }
      }
    }
  }
  return tags;
}

function get_user_id_from_dto(dto: PixivIllustDto): string[] {
  const tags: string[] = [];
  if (dto.userId !== undefined) {
    tags.push(`pixiv_user_id:${dto.userId}`);
  }
  return tags;
}

function get_artist_from_dto(dto: PixivIllustDto): string[] {
  const tags: string[] = [];
  if (dto.userName !== undefined) {
    tags.push(`artist:${sanitize(dto.userName)}`);
  }
  return tags;
}

function get_create_date_from_dto(dto: PixivIllustDto): string[] {
  const tags: string[] = [];
  const epoch_seconds = _convert_epoch_seconds(dto.createDate);
  if (epoch_seconds !== undefined) {
    tags.push(`date_created:${epoch_seconds}`);
  }
  return tags;
}

function get_upload_date_from_dto(dto: PixivIllustDto): string[] {
  const tags: string[] = [];
  const epoch_seconds = _convert_epoch_seconds(dto.uploadDate);
  if (epoch_seconds !== undefined) {
    tags.push(`date_uploaded:${epoch_seconds}`);
  }
  return tags;
}

function sanitize_summary(html_summary: string): string {
  const dom = legacyCompat.parseHtml(html_summary);
  dom.find("script").each((node) => node.toString());
  return dom.toString();
}

function get_summary_from_dto(dto: PixivIllustDto): string {
  // summary is html escaped by default and requires unescape to render.
  const summary = legacyCompat.htmlUnescape(dto.illustComment);
  return sanitize_summary(summary);
}

interface PixivHashData {
  tags: string;
  title?: string;
  summary?: string;
}

function get_hash_metadata_from_json(json: PixivFormattedJson, illust_id: string, tag_languages_str: string): PixivHashData {
  const logger = legacyCompat.getLogger("Pixiv", "plugins");
  const hashdata: PixivHashData = { tags: "" };

  // get illustration metadata.
  const illust_dto = get_illustration_dto_from_json(json, illust_id);
  const lrr_tags: string[] = [];
  lrr_tags.push(...get_manga_data_from_dto(illust_dto));
  lrr_tags.push(...get_pixiv_tags_from_dto(illust_dto, tag_languages_str));

  // add source
  const source = `https://pixiv.net/artworks/${illust_id}`;
  lrr_tags.push(`source:${source}`);

  // add general metadata.
  lrr_tags.push(...get_user_id_from_dto(illust_dto));
  lrr_tags.push(...get_artist_from_dto(illust_dto));

  // add time-based metadata.
  lrr_tags.push(...get_create_date_from_dto(illust_dto));
  lrr_tags.push(...get_upload_date_from_dto(illust_dto));
  hashdata.tags = lrr_tags.join(", ");

  // change title.
  if (illust_dto.illustTitle !== undefined) {
    hashdata.title = sanitize(illust_dto.illustTitle);
  } else {
    logger.error("Failed to extract illustration title from json file: " + JSON.stringify(json));
  }

  // add summary.
  const summary = get_summary_from_dto(illust_dto);
  if (summary !== undefined) {
    hashdata.summary = summary;
  }
  return hashdata;
}

function get_json_from_html(html: string): PixivFormattedJson {
  const logger = legacyCompat.getLogger("Pixiv", "plugins");
  // get 'content' body.
  const dom = legacyCompat.parseHtml(html);
  const jsonstring = dom.at("meta#meta-preload-data")?.attr("content") ?? "{}";
  logger.debug(`Tentative JSON: ${jsonstring}`);
  return JSON.parse(jsonstring);
}

interface PixivAjaxBody {
  illustId: unknown;
  title?: string;
  userId?: string | number;
  userName?: string;
  description: string;
  createDate: string;
  uploadDate: string;
  tags: { tags: PixivTagEntry[] };
  seriesNavData?: PixivSeriesNavData;
}

interface PixivAjaxJson {
  error?: boolean;
  message?: string;
  body?: PixivAjaxBody;
}

async function get_json_from_ajax(illust_id: string, ua: LegacyUserAgent): Promise<PixivFormattedJson | undefined> {
  const logger = legacyCompat.getLogger("Pixiv", "plugins");
  const ajax_url = `https://www.pixiv.net/ajax/illust/${illust_id}`;
  logger.debug(`Attempting to fetch JSON from AJAX endpoint: ${ajax_url}`);
  const res = (await ua.get(ajax_url, { Referer: "https://www.pixiv.net" })).result;
  if (res.is_error) {
    logger.debug(`Failed to fetch from AJAX endpoint: error (${res.code})`);
    return undefined;
  }
  logger.debug("AJAX response received, processing JSON");
  let json: PixivAjaxJson;
  try {
    json = JSON.parse(res.body);
  } catch (caughtError) {
    logger.error(`Failed to decode JSON from AJAX response: ${caughtError}`);
    return undefined;
  }
  if (json.error) {
    logger.error("Pixiv AJAX API returned an error: " + json.message);
    return undefined;
  }
  return format_ajax_json(json, illust_id);
}

function format_ajax_json(ajax_json: PixivAjaxJson, illust_id: string): PixivFormattedJson | undefined {
  const logger = legacyCompat.getLogger("Pixiv", "plugins");
  const body = ajax_json.body;
  if (!body) {
    logger.error("Unexpected AJAX response format, missing 'body' key");
    return undefined;
  }
  const dto: PixivIllustDto = {
    illustId: body.illustId,
    illustTitle: body.title,
    userId: body.userId,
    userName: body.userName,
    illustComment: body.description,
    createDate: body.createDate,
    uploadDate: body.uploadDate,
    tags: { tags: body.tags.tags },
  };
  if (body.seriesNavData) {
    dto.seriesNavData = body.seriesNavData;
  }
  return { illust: { [illust_id]: dto } };
}

async function get_html_from_illust_id(illust_id: string, ua: LegacyUserAgent): Promise<string> {
  const logger = legacyCompat.getLogger("Pixiv", "plugins");
  // illustration ID to URL.
  let URL = `https://www.pixiv.net/en/artworks/${illust_id}/`;
  for (;;) {
    const res = (await ua.get(URL, { Referer: "https://www.pixiv.net" })).result;
    const code = res.code;
    logger.debug(`Received code ${code}.`);

    // handle 3xx.
    if (code === 301 && res.headers.location) {
      URL = res.headers.location;
      logger.debug(`Redirecting to ${URL}`);
      continue;
    }
    if (code === 302 && res.headers.location) {
      URL = `pixiv.net${res.headers.location}`;
      logger.debug(`Redirecting to ${URL}`);
      continue;
    }

    // handle 4xx.
    if (res.is_error) {
      return `error (${res.code}) `;
    }

    // handle 2xx.
    return res.body;
  }
}

async function get_metadata_from_illust_id(illust_id: string, ua: LegacyUserAgent, tag_languages_str: string): Promise<PixivHashData> {
  const logger = legacyCompat.getLogger("Pixiv", "plugins");
  let hashdata: PixivHashData = { tags: "" };

  // Try nextjs ajax endpoint with server-side rendering fallback
  logger.debug(`Attempting to get metadata using Next.js AJAX endpoint for illustration ID: ${illust_id}`);
  let json = await get_json_from_ajax(illust_id, ua);
  if (!json) {
    logger.debug(`Next.js method failed, falling back to HTML parsing for illustration ID: ${illust_id}`);
    const html = await get_html_from_illust_id(illust_id, ua);
    if (HTML_ERROR_MARKER_PATTERN.test(html)) {
      throw new PluginErrorException("Error retrieving HTML from Pixiv Illustration", { html });
    }
    json = get_json_from_html(html);
  }
  if (json) {
    hashdata = get_hash_metadata_from_json(json, illust_id, tag_languages_str);
  } else {
    logger.error(`Failed to retrieve metadata for illustration ID: ${illust_id}`);
  }
  return hashdata;
}
