// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/Pixiv.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-09.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - external Perl module reference has no JS equivalent: Mojo::DOM
//   - external Perl module reference has no JS equivalent: Time::Piece
//

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

export function pluginInfo() {
  return {
    namespace: "pixivmetadata",
    type: "metadata" as const,
    parameters: [
      { name: "param1", description: "Comma-separated list of languages to support. Options: jp, en. Empty string defaults to original tags (jp) only.", required: false },
    ],
    // TODO(perl-convert): source used an HTTP client (Mojo::UserAgent/LWP/etc.) — 
    // fill in the actual host(s) this plugin needs so Deno's --allow-net grant 
    // stays as narrow as possible (constitution Principle IV).
    // Hosts verified against every URL literal in the original Perl source
    // (~/LANraragi/lib/LANraragi/Plugin/Metadata/Pixiv.pm): the ajax illust-info API and artwork
    // pages both live under www.pixiv.net; the bare pixiv.net host also appears (source tag URL,
    // and as a redirect-location prefix).
    declared_permissions: { net: ["www.pixiv.net", "pixiv.net"], read: false, write: false },
    name: "Pixiv",
    author: "psilabs-dev (ported)",
    description: "Retrieve metadata of a Pixiv artwork by its artwork ID.\n            <br>Supports ID extraction from these file formats: \"{{pixiv_id}} Title\", \"pixiv_{pixiv_id}\" or \"{pixiv_id} Title\".\n            <br>\n            <br><i class='fa fa-exclamation-circle'></i> Pixiv enforces a rate limit on API requests, and may suspend/ban your account for overuse.\n        ",
    version: "0.4",
    icon: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAAUABQDAREAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAwYABAUH/8QAJBAAAgICAgICAgMAAAAAAAAAAQIDBAUGABESIQcxImETQVH/xAAZAQACAwEAAAAAAAAAAAAAAAADBgACCAX/xAAoEQABBAEDAgYDAQAAAAAAAAABAgMEEQAFITESUQYTFEFhkTJxocH/2gAMAwEAAhEDEQA/ANfRvi3MbpRvZxrlfG4jHQT2J7U35PIsKB5FhjHuRgpHf0B5DsjvmrNV15nTHERwkrcWQABwOo0Co8AE/smjQzIWkeHn9VbXIKghpAUSTyekWQkckgV2G4s4fXNI1LeMkuuarsuQizVgEUYsnTSKG5IB2Iw6SN/GzdevIEE+uxwc3VJmlteqltJLQ/IoUSUjvRAsD3rf4wkHSYOru+khOqDp/ELSAFHtYUaJ9rFfOJFmtPTsy07UTRTQO0ciMOirKeiD+wRzvIWl1IWg2DuP1i642ppZbWKINEfIzpnwOHt5LaaE14QVzqeV/OTyMcRaNQXIUE/0O+gT64q+LKbajuJTZ85virNE7b/6cbvB9uPSWlKpPkO83QsDfa/4MFoFHVNE2jH7tsm54u5Dhplu16OLaSaxbmT2ie0VY18gO2Yj19A8Jq7szVYi4EVhSS4OkqXQSkHk8kk1wB95XRmYWjzG9QlyEqDZ6glFlSiNwOAAL5JPHtiHn8vNsGdyOesoqS5G3LbdV+laRyxA/XvjBEjJhx0R07hAA+hWLU2SqbJckrFFair7N4ClksjjWkbHX7NUzRmKQwyshdD9qej7B/w8u6y09QdSDW4sXR74Np91iy0opsUaJFjtt7ZX4XBZOTJn/9k=",
    oneshot_arg: "Pixiv artwork URL or illustration ID (e.g. pixiv.net/en/artworks/123456 or 123456.)",
    login_from: "pixivlogin",
  };
}


export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = perlCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as Record<string, any>;
  //# Global info hash, contains various metadata provided by LRR
  let ua = lrr_info["user_agent"];
  let logger = perlCompat.getLogger("Pixiv", "plugins");
  let tag_languages_str = hostArgs.arg as string;
  let illust_id = find_illust_id(lrr_info);
  if (! illust_id) {
    let message = "Failed to extract Pixiv ID!";
    logger.error(message);
    throw new Error(`${message}\n`);
  }
  logger.debug(`Retrieved Pixiv illustration ID = ${illust_id}`);
  //    #Work your magic here - You can create subroutines below to organize the code better

  let metadata = await get_metadata_from_illust_id(illust_id, ua, tag_languages_str);
  //    #Otherwise, return the tags you've harvested.

  logger.info("Sending the following tags to LRR: " + metadata["tags"]);
  return metadata;
}

function _convert_epoch_seconds(...args: any[]) {
  let [formattedDate] = args.slice(0);
  (formattedDate = formattedDate.replace(/(\+\d{2}:\d{2})$/, ""));
  let epoch_seconds = Time_Piece.strptime(formattedDate, "%Y-%m-%dT%H:%M:%S").epoch;
  return epoch_seconds;
}

function sanitize(...args: any[]) {
  let [text] = args.slice(0);
  let sanitized_text = text;
  //    # replace nonseparator characters with empty str.

  (sanitized_text = sanitized_text.replace(/["?*%\$:]/g, ""));
  //    # replace underscore with space.

  (sanitized_text = sanitized_text.replace(/[_]/g, " "));
  //    # if a dash is preceded by space, remove; otherwise keep.

  (sanitized_text = sanitized_text.replace(/ -/g, " "));
  if (sanitized_text !== text) {
    let logger = perlCompat.getLogger("Pixiv", "plugins");
    logger.info(`\"${text}\" was sanitized.`);
  }
  return sanitized_text;
}

function find_illust_id(...args: any[]) {
  let match: RegExpMatchArray | null;
  let [lrr_info] = args.slice(0);
  let oneshot_param = lrr_info["oneshot_param"];
  let archive_title = lrr_info["archive_title"];
  let logger = perlCompat.getLogger("Pixiv", "plugins");
  if ((oneshot_param !== undefined && oneshot_param !== null)) {
    //        # case 1: "$illust_id" i.e. string of digits.
  
    if ((match = oneshot_param.match(/^\d+$/))) {
      return oneshot_param;
    }
    //        # case 2: URL-based embedding
  
    if ((match = oneshot_param.match(/.*pixiv\.net\/.*artworks\/(\d+)/))) {
      return match[1];
    }
  }
  if ((archive_title !== undefined && archive_title !== null)) {
    //        # case 3: archive title extraction (strong pattern matching)
  
    //        # use strong pattern matching if using multiple metadata plugins and archive title needs to exclusively call the pixiv plugin.
  
    if ((match = archive_title.match(/pixiv_\{(\d*)\}.*$/))) {
      return match[1];
    }
    //        # case 3.1: archive title extraction without brackets (for pixivdl compatibility)
  
    if ((match = archive_title.match(/pixiv_(\d+).*$/))) {
      return match[1];
    }
    //        # case 4: archive title extraction (weak pattern matching)
  
    if ((match = archive_title.match(/^\{(\d*)\}.*$/))) {
      return match[1];
    }
  }
  return "";
}

function get_illustration_dto_from_json(...args: any[]) {
  //    # retrieve relevant data obj from json obj

  let [json, illust_id] = args.slice(0);
  return json['illust'][illust_id];
}

function get_manga_data_from_dto(...args: any[]) {
  //    # get manga-based data and return as an array.

  let [dto] = args.slice(0);
  let manga_data = [] as any[];
  if ((dto["seriesNavData"] !== undefined) && (dto !== undefined && dto !== null)["seriesNavData"]) {
    let series_nav_data = dto["seriesNavData"];
    let series_id = series_nav_data["seriesId"];
    let series_title = series_nav_data["title"];
    let series_order = series_nav_data["order"];
    if ((series_id !== undefined && series_id !== null) && (series_title !== undefined && series_title !== null) && (series_order !== undefined && series_order !== null)) {
      series_title = sanitize(series_title);
      manga_data.push((`pixiv_series_id:${series_id}`, `pixiv_series_title:${series_title}`, `pixiv_series_order:${series_order}`,));
    }
  }
  return manga_data;
}

function get_pixiv_tags_from_dto(...args: any[]) {
  let [dto, tag_languages_str] = args.slice(0);
  let tags = [] as any[];
  //    # extract tag languages.

  let tag_languages = [] as any[];
  if (tag_languages_str === "") {
    tag_languages.push("jp");
  } else {
    tag_languages = tag_languages_str.split(/,/);
    for (const it of tag_languages) {
      (it = it.replace(/^\s+/, ""));
      (it = it.replace(/\s+$/, ""));
    }
  }
  for (let item of dto["tags"]["tags"]) {
    //        # iterate over tagging language.
  
    for (let tag_language of tag_languages) {
      if (tag_language === 'jp') {
        //                # add original/jp tags.
      
        let orig_tag = item["tag"];
        if ((orig_tag !== undefined && orig_tag !== null)) {
          orig_tag = sanitize(orig_tag);
          tags.push(orig_tag);
        }
      } else {
        //                # add translated tags.
      
        let translated_tag = item["translation"][tag_language];
        if ((translated_tag !== undefined && translated_tag !== null)) {
          translated_tag = sanitize(translated_tag);
          tags.push(translated_tag);
        }
      }
    }
  }
  return tags;
}

function get_user_id_from_dto(...args: any[]) {
  let [dto] = args.slice(0);
  let tags = [] as any[];
  let user_id = dto["userId"];
  if ((user_id !== undefined && user_id !== null)) {
    tags.push(`pixiv_user_id:${user_id}`);
  }
  return tags;
}

function get_artist_from_dto(...args: any[]) {
  let [dto] = args.slice(0);
  let tags = [] as any[];
  let user_name = dto["userName"];
  if ((user_name !== undefined && user_name !== null)) {
    user_name = sanitize(user_name);
    tags.push(`artist:${user_name}`);
  }
  return tags;
}

function get_create_date_from_dto(...args: any[]) {
  let [dto] = args.slice(0);
  let tags = [] as any[];
  let formattedDate = dto["createDate"];
  let epoch_seconds = _convert_epoch_seconds(formattedDate);
  if ((epoch_seconds !== undefined && epoch_seconds !== null)) {
    tags.push(`date_created:${epoch_seconds}`);
  }
  return tags;
}

function get_upload_date_from_dto(...args: any[]) {
  let [dto] = args.slice(0);
  let tags = [] as any[];
  let formattedDate = dto["uploadDate"];
  let epoch_seconds = _convert_epoch_seconds(formattedDate);
  if ((epoch_seconds !== undefined && epoch_seconds !== null)) {
    tags.push(`date_uploaded:${epoch_seconds}`);
  }
  return tags;
}

function sanitize_summary(...args: any[]) {
  let [html_summary] = args.slice(0);
  let [dom] = perlCompat.parseHtml(html_summary);
  dom.find('script').each((...args: any[]) => {args.shift().remove;});
  let summary = dom .toString();
  return summary;
}

function get_summary_from_dto(...args: any[]) {
  let [dto] = args.slice(0);
  let summary = dto["illustComment"];
  summary = perlCompat.htmlUnescape(summary);
  //# summary is html escaped by default and requires unescape to render.
  summary = sanitize_summary(summary);
  return summary;
}

function get_hash_metadata_from_json(...args: any[]) {
  let [json, illust_id, tag_languages_str] = args.slice(0);
  let logger = perlCompat.getLogger("Pixiv", "plugins");
  let hashdata = {} as Record<string, any>;
  //    # get illustration metadata.

  let illust_dto = get_illustration_dto_from_json(json, illust_id);
  let lrr_tags = [] as any[];
  let manga_data = get_manga_data_from_dto(illust_dto);
  let pixiv_tags = get_pixiv_tags_from_dto(illust_dto, tag_languages_str);
  lrr_tags.push(manga_data);
  lrr_tags.push(pixiv_tags);
  //    # add source

  let source = `https://pixiv.net/artworks/${illust_id}`;
  lrr_tags.push(`source:${source}`);
  //    # add general metadata.

  let user_id_data = get_user_id_from_dto(illust_dto);
  let user_name_data = get_artist_from_dto(illust_dto);
  lrr_tags.push(user_id_data);
  lrr_tags.push(user_name_data);
  //    # add time-based metadata.

  let create_date_epoch_data = get_create_date_from_dto(illust_dto);
  let upload_date_epoch_data = get_upload_date_from_dto(illust_dto);
  lrr_tags.push(create_date_epoch_data);
  lrr_tags.push(upload_date_epoch_data);
  hashdata["tags"] = lrr_tags.join(', ');
  //    # change title.

  let illust_title = illust_dto["illustTitle"];
  if ((illust_title !== undefined && illust_title !== null)) {
    illust_title = sanitize(illust_title);
    hashdata["title"] = illust_title;
  } else {
    logger.error("Failed to extract illustration title from json file: " + Dumper(json));
  }
  //    # add summary.

  let summary = get_summary_from_dto(illust_dto);
  if ((summary !== undefined && summary !== null)) {
    hashdata["summary"] = summary;
  }
  return hashdata;
}

function get_json_from_html(...args: any[]) {
  let [html] = args.slice(0);
  let logger = perlCompat.getLogger("Pixiv", "plugins");
  //    # get 'content' body.

  let dom = perlCompat.parseHtml(html);
  let jsonstring = dom.at('meta#meta-preload-data').attr('content');
  logger.debug(`Tentative JSON: ${jsonstring}`);
  let json = JSON.parse(jsonstring);
  return json;
}

async function get_json_from_ajax(...args: any[]) {
  let [illust_id, ua] = args.slice(0);
  let logger = perlCompat.getLogger("Pixiv", "plugins");
  let ajax_url = `https://www.pixiv.net/ajax/illust/${illust_id}`;
  logger.debug(`Attempting to fetch JSON from AJAX endpoint: ${ajax_url}`);
  let res = (await ua.get(ajax_url, {Referer: "https://www.pixiv.net"})).result;
  if (res.is_error) {
    let code = res.code;
    logger.debug(`Failed to fetch from AJAX endpoint: error (${code})`);
    return;
  }
  let content = res.body;
  logger.debug("AJAX response received, processing JSON");
  let json = undefined;
  let perlError;
  try {
    json = JSON.parse(content);
  } catch (caughtError) {
    perlError = caughtError;
  }
  if (perlError) {
    logger.error(`Failed to decode JSON from AJAX response: $@`);
    return;
  }
  if (json["error"]) {
    logger.error("Pixiv AJAX API returned an error: " + json["message"]);
    return;
  }
  let formatted_json = format_ajax_json(json, illust_id);
  return formatted_json;
}

function format_ajax_json(...args: any[]) {
  let [ajax_json, illust_id] = args.slice(0);
  let logger = perlCompat.getLogger("Pixiv", "plugins");
  let body = ajax_json["body"];
  if (! (body !== undefined && body !== null)) {
    logger.error("Unexpected AJAX response format, missing 'body' key");
    return;
  }
  let formatted_json = {illust: {$illust_id: {illustId: body["illustId"], illustTitle: body["title"], userId: body["userId"], userName: body["userName"], illustComment: body["description"], createDate: body["createDate"], uploadDate: body["uploadDate"], tags: {tags: body["tags"]["tags"]}}}};
  if ((body["seriesNavData"] !== undefined) && (body !== undefined && body !== null)["seriesNavData"]) {
    formatted_json["illust"][illust_id]["seriesNavData"] = body["seriesNavData"];
  }
  return formatted_json;
}

async function get_html_from_illust_id(...args: any[]) {
  let [illust_id, ua] = args.slice(0);
  let logger = perlCompat.getLogger("Pixiv", "plugins");
  //    # illustration ID to URL.

  let URL = `https://www.pixiv.net/en/artworks/${illust_id}/`;
  while (1) {
    let res = (await ua.get(URL, {Referer: "https://www.pixiv.net"})).result;
    let code = res.code;
    logger.debug(`Received code ${code}.`);
    //        # handle 3xx.
  
    if (code == 301) {
      URL = res.headers.location;
      logger.debug(`Redirecting to ${URL}`);
      continue;
    }
    if (code == 302) {
      let location = res.headers.location;
      URL = `pixiv.net${location}`;
      logger.debug(`Redirecting to ${URL}`);
      continue;
    }
    //        # handle 4xx.
  
    if (res.is_error) {
      let code = res.code;
      return `error (${code}) `;
    }
    //        # handle 2xx.
  
    return res.body;
  }
}

async function get_metadata_from_illust_id(...args: any[]) {
  let match: RegExpMatchArray | null;
  let [illust_id, ua, tag_languages_str] = args.slice(0);
  let logger = perlCompat.getLogger("Pixiv", "plugins");
  //    # initialize hash.

  let hashdata: Record<string, any> = { tags: "" };
  //    # Try nextjs ajax endpoint with server-side rendering fallback

  logger.debug(`Attempting to get metadata using Next.js AJAX endpoint for illustration ID: ${illust_id}`);
  let json = await get_json_from_ajax(illust_id, ua);
  if (! json) {
    logger.debug(`Next.js method failed, falling back to HTML parsing for illustration ID: ${illust_id}`);
    let html = await get_html_from_illust_id(illust_id, ua);
    if ((match = html.match(/^error/))) {
      throw new Error(`Error retrieving HTML from Pixiv Illustration: ${html}\n`);
    }
    json = get_json_from_html(html);
  }
  if (json) {
    hashdata = get_hash_metadata_from_json(json, illust_id, tag_languages_str);
  } else {
    logger.error(`Failed to retrieve metadata for illustration ID: ${illust_id}`);
  }
  return hashdata;
}
