// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/RegexParse.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Hand-fixed since regeneration:
//   - `Mojo::File->new(...)->basename('.' . $file->extname)` (strip the extension from a path's
//     final component) — reimplemented with plain string ops (`get_filename_without_extension`).
//   - `qr/$params->{regex_string}/` (build a `Regexp` from a user-supplied pattern string,
//     including any named capture groups like `(?<artist>...)`) — JS's own `RegExp` constructor
//     and `match.groups` support named groups natively, so this is a direct `new RegExp(...)`.
//   - `my @items = ($tail =~ /\(...\)|\{...\}|\[...\]/g)` — Perl's list-context match with
//     alternation yields one 3-element slot (only one ever defined) per match, flattened across
//     all matches; JS's `matchAll` + filtering out `undefined` capture slots reproduces this.
//   - every `push(@tags, sub_call(...))` site — Perl's `push` flattens the callee's returned list;
//     the converter's literal `tags.push(sub_call(...))` instead nested one array as a single
//     element (same class of bug fixed in `hitomi.ts`/`pixiv.ts` this session) — fixed to
//     `tags.push(...sub_call(...))` throughout.
//   - `looks_like_number` (`Scalar::Util`) reimplemented as a numeric-string regex test.
//   - `m/^\Q$PLUGIN_TAG_NS/` (`\Q...\E` regex-metacharacter quoting) — `PLUGIN_TAG_NS` itself
//     (`"parsed:"`) contains no metacharacters, but the check is still expressed as a proper
//     prefix test (`String.prototype.startsWith`) rather than a hand-rolled regex, for the same
//     "quote whatever the constant happens to contain" safety `\Q...\E` provides.
//   - the converter had bound all 3 declared parameters to the same single `hostArgs.arg` value
//     (a since-fixed host-side limitation) — now reads the real per-parameter values from
//     `hostArgs.customargs`, positionally matching `pluginInfo().parameters`.
//
// Known, not fixed here: the real Perl declares a `default_value` for the 3rd ("Regex to use for
// parsing") parameter — this SDK's `PluginParameter` type (`crates/lanrurugi-plugin/dispatcher/
// plugin-sdk.ts`) has no `default_value` field at all yet, so there's no per-plugin fix available;
// a user must currently paste the default regex themselves the first time. Fixing this properly
// means extending the SDK contract (Rust `PluginInfo` struct + the settings-page parameter form
// too), out of scope for this pass.

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

/** Legacy's own `${PLUGIN_TAG_NS}` namespace (`"parsed:"`) for non-standard captured tags —
 * hoisted above `pluginInfo()` (unlike the converter's original ordering, which put it after and
 * left the two parameter descriptions below referencing it as a dead, non-interpolating
 * `"${PLUGIN_TAG_NS}"` literal string instead of a real template literal). */
const PLUGIN_TAG_NS = "parsed:";

export function pluginInfo() {
  return {
    namespace: "regexplugin",
    type: "metadata" as const,
    parameters: [
      { name: "param1", description: `If the filename ends with a pair of curly braces, return the contents inside them as a list of simple tags, without the "${PLUGIN_TAG_NS}" namespace`, required: false, type: "bool" },
      { name: "param2", description: `Capture everything you find between a pair of parentheses and make it available under the "${PLUGIN_TAG_NS}" namespace<BR />(use this in conjunction with Tag Rules)`, required: false, type: "bool" },
      { name: "param3", description: "Regex to use for parsing", required: false, type: "string" },
    ],
    declared_permissions: { net: [], read: false, write: false },
    name: "Filename Parsing",
    author: "thelastfantasy",
    // Verified verbatim against `~/LANraragi/lib/LANraragi/Plugin/Metadata/RegexParse.pm`'s own
    // `description =>` string-concatenation chain — the converter had originally only kept the
    // first fragment ("Derive tags..."), silently dropping the naming-convention explanation, the
    // full default regex breakdown, each capture group's meaning, the custom-named-capture-group
    // rules, and the non-standard-tag/Tag-Rules guidance that follow it in the real source.
    description:
      "Derive tags from the filename of the given archive.<br><br>" +
      'By default it follows the doujinshi naming standard "(Event) [Artist] TITLE (Series) [Language]".<br><br>' +
      "The default regex is:<br>" +
      "<code>(\\((?&lt;event&gt;[^([]+)\\))?\\s*(\\[(?&lt;artist&gt;[^]]+)\\])?\\s*(?&lt;title&gt;[^([]+)\\s*(\\((?&lt;series&gt;[^([)]+)\\))?\\s*(\\[(?&lt;language&gt;[^]]+)\\])?(?&lt;tail&gt;.*)?</code><br><br>" +
      "<code>()?</code> indicates the field is optional<br>" +
      "<code>(\\((?&lt;event&gt;[^([]+)\\))?</code> returns the content of (Event). Optional.<br>" +
      "<code>(\\[(?&lt;artist&gt;[^]]+)\\])?</code> returns the content of [Artist]. Optional.<br>" +
      "<code>(?&lt;title&gt;[^([]+)</code> returns the title. Mandatory.<br>" +
      "<code>(\\((?&lt;series&gt;[^([)]+)\\))?</code> returns the content of (Series). Optional.<br>" +
      "<code>(\\[(?&lt;language&gt;[^]]+)\\])?</code> returns the content of [Language]. Optional.<br>" +
      "<code>(?&lt;tail&gt;.*)?</code> returns everything that is out of E-Hentai standard for further processing. Optional.<br>" +
      "<code>\\s*</code> indicates zero or more whitespaces.<br><br>" +
      "You can provide a custom regex using named capture groups. The group name determines the tag namespace:<br>" +
      '&bull; <code>(?&lt;artist&gt;...)</code> &rarr; <code>artist:</code> (also extracts <code>group:</code> from "Circle (Artist)" format)<br>' +
      "&bull; <code>(?&lt;series&gt;...)</code> &rarr; <code>series:</code><br>" +
      "&bull; <code>(?&lt;tag&gt;...)</code> &rarr; simple tag (no namespace)<br>" +
      "&bull; <code>(?&lt;anyname&gt;...)</code> &rarr; <code>anyname:</code><br>" +
      "Use numbered suffixes for multiple groups of the same type: <code>(?&lt;artist2&gt;...)</code>, <code>(?&lt;tag3&gt;...)</code>, etc.<br>" +
      "Special groups: <code>title</code> sets the archive title, <code>tail</code> is used for trailing tag processing.<br><br>" +
      "By activating the plugin settings below, you can extend the capture to the content of each bracket in" +
      " the filename, even if it does not belong to the standard naming format.<br>" +
      `Non-standard tags will be made available to you associated with the "<i>${PLUGIN_TAG_NS}</i>" namespace so` +
      " you can manage them as you please by creating your own set of Tag Rules.<br>" +
      `My only suggestion is that you should place the rule "<i>-${PLUGIN_TAG_NS}*</i>" as your last rule to cleanup all the unnecessary elements.`,
    version: "0.1",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAAXNSR0IArs4c6QAAAL1JREFUOI1jZMABpNbH/sclx8DAwPAscDEjNnEMQUIGETIYhUOqYdgMhTPINQzdUEZqGIZsKBM1DEIGTOiuexqwCKdidDl0vtT62P9kuZCJEWuKYWBgYGBgRHbh04BFDNIb4jAUbbSrZTARUkURg6lD10OUC/0PNaMYgs1Skgwk1jCSDCQWoBg46dYmhite0+D8pwGLCMY6uotRDOy8toZBkI2HIhcO/pxCm8KBUkOxFl/kGoq3gCXFYFxVAACeoU/8xSNybwAAAABJRU5ErkJggg==",
  };
}
const COMMON_EXTRANEOUS_VALUES = new Set([
  "uncensored", "decensored", "ongoing", "pixiv", "twitter", "fanbox", "cosplay", "digital",
]);
const TRAILING_DIGITS_PATTERN = /\d+$/;
const NUMERIC_STRING_PATTERN = /^-?\d+(\.\d+)?$/;
const TRAILING_BRACE_TAGS_PATTERN = /(?<head>.*)(\{(?<ttags>[^}]*)\})$/;
const BRACKETED_RUN_PATTERN = /\(([^)]+)\)|\{([^}]+)\}|\[([^\]]+)\]/g;
const CIRCLE_ARTIST_PATTERN = /(.*) \((.*)\)/;

interface ParseFilenameParams {
  check_trailing_tags: boolean;
  keep_all_captures: boolean;
  regex_string: string;
}

export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = perlCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  interface ExecMetadataInfo {
    user_agent: PerlUserAgent;
    user_agent_cookies?: { name: string; value: string; domain: string; path: string }[];
    file_path: string;
    customargs: string[];
  }
  const lrr_info = hostArgs as unknown as ExecMetadataInfo;
  const [check_trailing_tags, keep_all_captures, regex_string] = lrr_info.customargs;

  // lrr_info's file_path is taken straight from the filesystem, which might not be proper UTF-8.
  // Run a decode to make sure we can derive tags with the proper encoding.
  const decoded_path = perlCompat.redis_decode(lrr_info.file_path);
  const filename = get_filename_without_extension(decoded_path);
  const [tags, title] = parse_filename(filename, {
    check_trailing_tags: !!check_trailing_tags,
    keep_all_captures: !!keep_all_captures,
    regex_string: regex_string ?? "",
  });
  const logger = perlCompat.getLogger("Filename Parsing", "plugins");
  if (tags === "" && title === "") {
    logger.info("Regex match failed, no changes");
    return { tags: "" };
  }
  logger.info(`Sending the following tags to LRR: ${tags}`);
  logger.info(`Parsed title is ${title}`);
  return { tags, title };
}

/** `Mojo::File->new(path)->basename('.' . $file->extname)` — the path's final component with its
 * extension (if any) stripped. */
function get_filename_without_extension(path: string): string {
  const basename = path.split(/[\\/]/).pop() ?? path;
  const dot = basename.lastIndexOf(".");
  return dot > 0 ? basename.slice(0, dot) : basename;
}

function parse_filename(filename: string, params: ParseFilenameParams): [string, string] {
  let title: string | undefined;
  let trailing_tags: string | undefined;
  let other_captures: string | undefined;

  // Replace underscores with spaces
  filename = filename.replace(/_/g, " ");

  const regex = new RegExp(params.regex_string);
  const match = filename.match(regex);
  if (!match) {
    return ["", ""];
  }

  // Capture all named groups immediately (before any subsequent regex operations overwrite them)
  const captures: Record<string, string> = match.groups ?? {};

  // Extract special cases
  if (captures.title) title = perlCompat.trim(captures.title);
  let tail = captures.tail ? perlCompat.trim(captures.tail) : "";

  if (tail) {
    // match trailing_tags (...{Tags}.ext)
    if (params.check_trailing_tags) {
      const tailMatch = tail.match(TRAILING_BRACE_TAGS_PATTERN);
      trailing_tags = tailMatch?.groups?.ttags;
      if (trailing_tags) tail = tailMatch?.groups?.head ?? tail;
    }

    // match any remaining parenthesis
    if (tail && params.keep_all_captures) {
      const items: string[] = [];
      for (const bracketMatch of tail.matchAll(BRACKETED_RUN_PATTERN)) {
        const captured = bracketMatch[1] ?? bracketMatch[2] ?? bracketMatch[3];
        if (captured !== undefined) items.push(captured);
      }
      other_captures = items.filter((it) => perlCompat.trim(it)).join(",");
    }
  }

  let tags: string[] = [];
  // Process all named capture groups dynamically
  for (const name of Object.keys(captures)) {
    if (name === "title" || name === "tail") continue;
    const value = perlCompat.trim(captures[name]);
    if (!value) continue;

    // Strip trailing digits to get the namespace (e.g., artist2 -> artist)
    const namespace = name.replace(TRAILING_DIGITS_PATTERN, "");
    if (namespace === "tag") {
      // Simple tags - no namespace, skip _classify_item
      tags.push(...value.split(",").map((it) => perlCompat.trim(it)));
    } else if (namespace === "artist") {
      tags.push(...parse_artist_value(value));
    } else if (namespace === "event") {
      // Direct assignment - no filtering
      tags.push(`event:${value}`);
    } else {
      tags.push(...parse_captured_value_for_namespace(value, `${namespace}:`));
    }
  }
  if (other_captures) tags.push(...parse_captured_value_for_namespace(other_captures, PLUGIN_TAG_NS));
  if (trailing_tags) tags.push(...parse_captured_value_for_namespace(trailing_tags, ""));
  if (!params.keep_all_captures) {
    tags = tags.filter((it) => !it.startsWith(PLUGIN_TAG_NS));
  }
  return [[...tags].sort().join(", "), title ?? ""];
}

function parse_artist_value(artist: string): string[] {
  const tags: string[] = [];
  // Special case for circle/artist sets: if the string contains parenthesis, what's inside those
  // is the artist name, the rest is the circle.
  const match = artist.match(CIRCLE_ARTIST_PATTERN);
  if (match) {
    tags.push("group:" + perlCompat.trim(match[1]));
    artist = perlCompat.trim(match[2]);
  }
  tags.push(...parse_captured_value_for_namespace(artist, "artist:"));
  return tags;
}

function parse_captured_value_for_namespace(capture: string, namespace: string): string[] {
  return capture.split(",").map((it) => _classify_item(perlCompat.trim(it), namespace));
}

function _classify_item(item: string, namespace: string): string {
  // if the namespace is specified, we are able to exclude some common words,
  // otherwise we are dealing with simple tags
  if ((namespace && COMMON_EXTRANEOUS_VALUES.has(item.toLowerCase())) || looks_like_number(item)) {
    return PLUGIN_TAG_NS + item;
  }
  return `${namespace}${item}`;
}

/** `Scalar::Util::looks_like_number` — a plain numeric-string test (integer or decimal, optional
 * leading sign); real Perl also accepts scientific notation and Inf/NaN, none of which occur in
 * this plugin's real inputs (bracketed filename fragments), so this narrower check is sufficient. */
function looks_like_number(item: string): boolean {
  return NUMERIC_STRING_PATTERN.test(item.trim());
}
