// Converted from LANraragi/lib/LANraragi/Plugin/Metadata/RegexParse.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-09.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - =~ with /g in list context (/\(([^\)]+)\)|\{([^}]+)\}|\[([^\]]+)\]/g) — Perl returns every 
//     captured group across all matches; JS .match() with /g returns only full-match strings, not 
//     captures. Verify this call site by hand.
//   - =~ with /g in list context (/(?<head>.*)(\{(?<ttags>[^\}]*)\})$/) — Perl returns every 
//     captured group across all matches; JS .match() with /g returns only full-match strings, not 
//     captures. Verify this call site by hand.
//   - external Perl module reference has no JS equivalent: Mojo::File
//   - this plugin declares 3 custom parameters, but the host currently passes only one generic 
//     `arg` value per call — only `param1` was mapped to it; the rest were also bound to that same 
//     value and need manual attention before this plugin can work correctly
//   - unsupported regex delimiter or /x flag: m/^\Q$PLUGIN_TAG_NS/
//   - unsupported regex delimiter or /x flag: qr/$params->{'regex_string'}/

declare global {
  interface PerlTransaction {
    req: { headers: { header(name: string, value: string): void } };
  }
  interface PerlUserAgent {
    cookie_jar: { add(cookie: { name: string; value: string; domain: string; path: string }): void };
    max_redirects(n: number): PerlUserAgent;
    transactor: { name(value: string): void };
    on(event: "start", handler: (ua: PerlUserAgent, tx: PerlTransaction) => void): void;
    get(url: string): Promise<{ result: PerlHttpResult }>;
    post(url: string, kind: "form" | "json", data: Record<string, string> | Record<string, unknown>): Promise<{ result: PerlHttpResult }>;
    cookies: { name: string; value: string; domain: string; path: string }[];
  }
  interface PerlHttpResult {
    body: string;
    code: number;
    readonly dom: PerlDomNode;
    readonly json: unknown;
  }
  interface PerlLogger {
    debug(msg: string): void;
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
  }
  interface PerlDomNode {
    text: string;
    attr(name: string): string | undefined;
    parent: PerlDomNode | undefined;
    at(selector: string): PerlDomNode | undefined;
    find(selector: string): PerlDomNode[] & { each<T>(fn: (node: PerlDomNode, index: number) => T): T[] };
    toString(): string;
  }
  // deno-lint-ignore no-var
  var perlCompat: {
    reverse<T>(list: readonly T[]): T[];
    chomp(s: string): string;
    sprintf(format: string, ...args: unknown[]): string;
    userAgent(): PerlUserAgent;
    getLogger(name: string, category: string): PerlLogger;
    htmlUnescape(s: string): string;
    parseHtml(markup: string, xml?: boolean): PerlDomNode;
    sleep(seconds: number): Promise<void>;
    getVersion(): { version: string; homepage: string };
    refType(x: unknown): string;
    trim(s: string | null | undefined): string;
    fileparse(path: string, suffixPattern?: unknown): [string, string, string];
    redis_decode(s: string): string;
  };
}

export function pluginInfo() {
  return {
    namespace: "regexplugin",
    type: "metadata" as const,
    parameters: [
      { name: "param1", description: "If the filename ends with a pair of curly braces, return the contents inside them as a list of simple tags, without the \"${PLUGIN_TAG_NS}\" namespace", required: false },
      { name: "param2", description: "Capture everything you find between a pair of parentheses and make it available under the \"${PLUGIN_TAG_NS}\" namespace<BR />", required: false },
      { name: "param3", description: "Regex to use for parsing", required: false },
    ],
    declared_permissions: { net: [], read: false, write: false },
    name: "Filename Parsing",
    author: "Difegue (ported)",
    description: "Derive tags from the filename of the given archive.<br><br>",
    version: "1.2",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAAXNSR0IArs4c6QAAAL1JREFUOI1jZMABpNbH/sclx8DAwPAscDEjNnEMQUIGETIYhUOqYdgMhTPINQzdUEZqGIZsKBM1DEIGTOiuexqwCKdidDl0vtT62P9kuZCJEWuKYWBgYGBgRHbh04BFDNIb4jAUbbSrZTARUkURg6lD10OUC/0PNaMYgs1Skgwk1jCSDCQWoBg46dYmhite0+D8pwGLCMY6uotRDOy8toZBkI2HIhcO/pxCm8KBUkOxFl/kGoq3gCXFYFxVAACeoU/8xSNybwAAAABJRU5ErkJggg==",
  };
}

let PLUGIN_TAG_NS = 'parsed:';
let COMMON_EXTRANEOUS_VALUES: Record<string, any> = { uncensored: 1, decensored: 1, ongoing: 1, pixiv: 1, twitter: 1, fanbox: 1, cosplay: 1, digital: 1 };

export async function execMetadata(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = perlCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
  }
  let lrr_info = hostArgs as Record<string, any>;
  let check_trailing_tags = hostArgs.arg as string;
  let keep_all_captures = hostArgs.arg as string;
  let regex_string = hostArgs.arg as string;
  //    # lrr_info's file_path is taken straight from the filesystem, which might not be proper UTF-8.

  //    # Run a decode to make sure we can derive tags with the proper encoding.

  let file = Mojo_File.new(perlCompat.redis_decode(lrr_info['file_path']));
  let filename = file.basename('.' + file.extname);
  let [tags, title] = parse_filename(filename, {check_trailing_tags: check_trailing_tags, keep_all_captures: keep_all_captures, regex_string: regex_string});
  let logger = perlCompat.getLogger("Filename Parsing", "plugins");
  if (tags === "" && title === "") {
    logger.info("Regex match failed, no changes");
    return { tags: "" };
  }
  logger.info(`Sending the following tags to LRR: ${tags}`);
  logger.info(`Parsed title is ${title}`);
  return { tags: tags, title: title };
}

function parse_filename(...args: any[]) {
  let match: RegExpMatchArray | null;
  let [filename, params] = args.slice(0);
  let title = undefined;
  let trailing_tags = undefined;
  let other_captures = undefined;
  //    #Replace underscores with spaces

  (filename = filename.replace(/_/g, " "));
  let regex = (undefined /* TODO(perl-convert): qr/$params->{'regex_string'}/ */);
  if (! (regex.test(filename))) {
    return ["", ""];
  }
  //    # Capture all named groups immediately (before any subsequent regex operations overwrite %+)

  let captures = (match?.groups ?? {});
  //    # Extract special cases

  if ((captures !== undefined && captures !== null)['title']) { title = perlCompat.trim(captures['title']); }
  let tail = (captures !== undefined && captures !== null)['tail'] ? perlCompat.trim(captures['tail']) : '';
  if (tail) {
    //        # match trailing_tags (...{Tags}.ext)
  
    if (params['check_trailing_tags']) {
      (match = tail.match(/(?<head>.*)(\{(?<ttags>[^\}]*)\})$/));
      trailing_tags = (match?.groups ?? {})['ttags'];
      if ((trailing_tags)) { tail = (match?.groups ?? {})['head']; }
    }
    //        # match any remaining parenthesis
  
    if (tail && params['keep_all_captures']) {
      let items = [(match = tail.match(/\(([^\)]+)\)|\{([^}]+)\}|\[([^\]]+)\]/g))];
      other_captures = (items.filter((it) => (perlCompat.trim(it)))).join(',');
    }
  }
  let tags = [] as any[];
  //    # Process all named capture groups dynamically

  for (let name of Object.keys(captures)) {
    if (name === 'title' || name === 'tail') { continue; }
    let value = perlCompat.trim(captures[name]);
    if (!(value)) { continue; }
    //        # Strip trailing digits to get the namespace (e.g., artist2 -> artist)
  
    let namespace = name.replace(/\d+$/, "");
    if (namespace === 'tag') {
      //            # Simple tags - no namespace, skip _classify_item
    
      tags.push(value.split(/,/).map((it) => (perlCompat.trim(it))));
    } else if (namespace === 'artist') {
      tags.push(parse_artist_value(value));
    } else if (namespace === 'event') {
      //            # Direct assignment - no filtering
    
      tags.push(`event:${value}`);
    } else {
      tags.push(parse_captured_value_for_namespace(value, `${namespace}:`));
    }
  }
  if ((other_captures)) { tags.push(parse_captured_value_for_namespace(other_captures, PLUGIN_TAG_NS)); }
  if ((trailing_tags)) { tags.push(parse_captured_value_for_namespace(trailing_tags, '')); }
  if (! params['keep_all_captures']) {
    tags = tags.filter((it) => (! (undefined /* TODO(perl-convert): m/^\Q$PLUGIN_TAG_NS/ */)));
  }
  return [[...tags].sort().join(", "), title ?? ''];
}

function parse_artist_value(...args: any[]) {
  let match: RegExpMatchArray | null;
  let [artist] = args.slice(0);
  let tags = [] as any[];
  //    #Special case for circle/artist sets:

  //    #If the string contains parenthesis, what's inside those is the artist name

  //    #the rest is the circle.

  if ((match = artist.match(/(.*) \((.*)\)/))) {
    tags.push("group:" + perlCompat.trim(match[1]));
    artist = perlCompat.trim(match[2]);
  }
  tags.push(parse_captured_value_for_namespace(artist, 'artist:'));
  return tags;
}

function parse_captured_value_for_namespace(...args: any[]) {
  let [capture, namespace] = args.slice(0);
  return capture.split(/,/).map((it) => (_classify_item(perlCompat.trim(it), namespace)));
}

function _classify_item(...args: any[]) {
  let [item, namespace] = args.slice(0);
  //    # if the namespace is specified, we are able to exclude some common words,

  //    # otherwise we are dealing with simple tags

  if (namespace && COMMON_EXTRANEOUS_VALUES[item.toLowerCase()] || looks_like_number(item)) {
    return PLUGIN_TAG_NS + item;
  }
  return `${namespace}${item}`;
}
