[request_definition]
r = sub_role, sub_id, obj_role, obj_id

[policy_definition]
p = sub_role, target, eft

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = r.sub_role == p.sub_role && ((p.target == "all") || (p.target == "self" && r.sub_id == r.obj_id && r.sub_role == r.obj_role) || (p.target == "guest" && r.obj_role == "token_guest"))
