// Converted from LANraragi/lib/LANraragi/Plugin/Download/EHentai.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - =~ with /g in list context (/.*document.location = "(.*)".*/gim) — Perl returns every 
//     captured group across all matches; JS .match() with /g returns only full-match strings, not 
//     captures. Verify this call site by hand.
//   - =~ with /g in list context (/.*exhentai\.org/gi) — Perl returns every captured group across 
//     all matches; JS .match() with /g returns only full-match strings, not captures. Verify this 
//     call site by hand.
//   - =~ with /g in list context (/.*\/g\/([0-9]*)\/([0-z]*)\/*.*/) — Perl returns every captured 
//     group across all matches; JS .match() with /g returns only full-match strings, not captures. 
//     Verify this call site by hand.
//   - =~ with /g in list context (/.*Insufficient funds.*/gim) — Perl returns every captured group 
//     across all matches; JS .match() with /g returns only full-match strings, not captures. Verify 
//     this call site by hand.
//
// NOTE: this plugin makes HTTP calls but declared_permissions.net is still the
// converter's placeholder — fill in the real host(s), verified against the URL
// literals in the original Perl source, before this plugin can actually reach them
// (Deno's --allow-net grant is scoped to exactly this list).

export function pluginInfo() {
  return {
    namespace: "ehdl",
    type: "download" as const,
    parameters: [
      { name: "forceresampled", description: "Force resampled archive download", required: false, type: "bool" },
    ],
    // Verified against every URL literal this plugin's own execDownload actually calls
    // (archiver.php on either domain, chosen based on the input URL) — this plugin still talks to
    // E-Hentai/ExHentai itself (to resolve the real archive-download URL via the archiver form)
    // before handing the resulting URL off to Rust for the real byte-level fetch, unlike chaika.ts
    // (which needs no net permission at all since it does zero HTTP itself).
    // `api.e-hentai.org` is the JSON `gdata` endpoint the version-history walk below uses; the
    // other two are the archiver.php form this plugin has always talked to.
    declared_permissions: { net: ["e-hentai.org", "exhentai.org", "api.e-hentai.org"], read: false, write: false },
    name: "E*Hentai Downloader",
    author: "thelastfantasy",
    description: "Downloads the given e*hentai URL and adds it to LANraragi. This uses GP to call the archiver, so make sure you have enough!",
    version: "0.1",
    login_from: "ehlogin",
    url_pattern: "e-?hentai\\.org|exhentai\\.org",
    domain_match: ["e-hentai.org", "exhentai.org"],
  };
}

/** Folds every E-Hentai domain alias and URL shape onto one `e-hentai.org/g/{gid}/{token}` string,
 * so the host can compare a freshly-resolved URL against a `source:` tag written by any past
 * version of this plugin by plain string equality (SDK contract: same resource must always produce
 * the same output, whichever historical shape it arrived in).
 *
 * `gid` is the identifier E-Hentai guarantees stable, so normalizing toward it — rather than toward
 * whatever host/path a given URL happened to use — is what makes that contract hold. A URL this
 * plugin doesn't recognize as a gallery falls back to the host's own generic trimming rather than
 * being mangled into something that would never match anything. */
export function canonicalizeSource(url: string): string {
  const generic = String(url ?? "")
    .trim()
    .replace(/^https?:\/\//i, "")
    .replace(/^www\./i, "")
    .split("?")[0]
    .split("#")[0]
    .replace(/\/+$/, "");
  const match = generic.match(
    /^(?:g\.|forums\.)?(?:ex|e-)hentai\.org\/g\/([0-9]+)\/([0-9a-f]+)/i,
  );
  return match ? `e-hentai.org/g/${match[1]}/${match[2]}` : generic;
}

export function pluginOptions() {
  return {
    domain_rules: [
      // The real archive download itself is served by an H@H (Hentai@Home) client node, not
      // e-hentai.org/exhentai.org (those only negotiate the final URL via archiver.php) — the
      // `downloads[]` URL this plugin returns always points here.
      {
        pattern: "*.hath.network",
        max_concurrent: 10,
        description: "Limit simultaneous downloads from H@H client nodes",
      },
    ],
    overwrite_on_duplicate: {
      default: false,
      description: "Overwrite an existing archive with the same content or filename when re-downloading (e.g. after a gallery was revised).",
    },
  };
}


/** One `gdata` response entry, limited to the fields this plugin reads. */
interface GalleryData {
  gid: number;
  token: string;
  posted: string;
  parent_gid?: string;
  parent_key?: string;
  /** Present ONLY when the queried gallery is not itself the newest revision — its absence is how
   * E-Hentai says "this one is current". */
  current_gid?: string;
  current_key?: string;
}

/** One `gdata` call. `namespace: 0` is load-bearing: the newer `namespace: 1` format omits
 * `current_gid` entirely, which is the only field that identifies the series' newest revision.
 *
 * Safe here, but NOT a change to copy into `plugins/metadata/ehentai.ts`: `namespace: 0` also
 * returns tags stripped of their namespace prefixes (a bare value, not `artist:<value>` — verified
 * live against a real gallery),
 * which would collapse every E-Hentai tag into the bare-tag "Other" bucket. This function reads
 * only gid/token/posted/parent/current and never looks at `tags`, so the stripping costs nothing. */
async function fetchGalleryData(
  pairs: [number, string][],
): Promise<GalleryData[]> {
  const response = await fetch("https://api.e-hentai.org/api.php", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ method: "gdata", gidlist: pairs, namespace: 0 }),
  });
  if (!response.ok) return [];
  const body = await response.json() as { gmetadata?: GalleryData[] };
  return body.gmetadata ?? [];
}

/** Collects every revision of a gallery's series, walking `parent_gid` back to the chain's root and
 * `current_gid` forward to its tip.
 *
 * Returns `[]` rather than throwing on any failure: version history is optional enrichment, and a
 * download must never fail because this lookup did. The host treats an empty list as "no version
 * relationship known" and catalogues the download normally. */
async function collectVersionHistory(
  gID: string,
  gToken: string,
  logger: ReturnType<typeof legacyCompat.getLogger>,
): Promise<VersionHistoryEntryResult[]> {
  const MAX_HOPS = 50;
  const byGid = new Map<number, GalleryData>();

  const record = (entry: GalleryData) => {
    if (entry && typeof entry.gid === "number") byGid.set(entry.gid, entry);
    return entry;
  };

  try {
    const [seed] = await fetchGalleryData([[Number(gID), gToken]]);
    if (!seed) return [];
    record(seed);

    // Backward: each gallery names at most one direct parent, so this is a plain chain walk.
    let cursor: GalleryData | undefined = seed;
    for (let hop = 0; hop < MAX_HOPS; hop++) {
      const parentGid = Number(cursor?.parent_gid ?? 0);
      const parentKey = cursor?.parent_key;
      if (!parentGid || !parentKey || byGid.has(parentGid)) break;
      const [parent] = await fetchGalleryData([[parentGid, parentKey]]);
      if (!parent) break;
      cursor = record(parent);
    }

    // Forward: `current_gid` jumps straight to the newest revision, so this normally runs once.
    // Looping guards the case where the tip has itself since been superseded.
    cursor = seed;
    for (let hop = 0; hop < MAX_HOPS; hop++) {
      const currentGid = Number(cursor?.current_gid ?? 0);
      const currentKey = cursor?.current_key;
      if (!currentGid || !currentKey || byGid.has(currentGid)) break;
      const [current] = await fetchGalleryData([[currentGid, currentKey]]);
      if (!current) break;
      cursor = record(current);
    }
  } catch (e) {
    logger.warn(`version history lookup failed, continuing without it: ${e}`);
    return [];
  }

  return [...byGid.values()].map((entry) => ({
    source: canonicalizeSource(`e-hentai.org/g/${entry.gid}/${entry.token}`),
    // `posted` is unix seconds as a string; the SDK contract wants ISO 8601.
    posted_at: new Date(Number(entry.posted) * 1000).toISOString(),
  }));
}

export async function execDownload(
  hostArgs: Record<string, unknown>,
): Promise<DownloadResultShape> {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = legacyCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
    const headers = (info.user_agent_headers ?? {}) as Record<string, string>;
    if (Object.keys(headers).length > 0) {
      info.user_agent.on("start", (_ua: any, tx: any) => {
        for (const [name, value] of Object.entries(headers)) tx.req.headers.header(name, value);
      });
    }
  }
  interface ExecDownloadInfo extends Required<Pick<DownloadHostArgs, "url" | "customargs">> {
    user_agent: LegacyUserAgent;
    user_agent_cookies?: LegacyCookie[];
  }
  let match: RegExpMatchArray | null;
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as unknown as ExecDownloadInfo;
  let params = { forceresampled: lrr_info.customargs[0] as boolean };
  let logger = legacyCompat.getLogger("EH Downloader", "plugins");
  let url = lrr_info["url"];
  let gID = "";
  let gToken = "";
  let archKey = "";
  let domain = ((match = url.match(/.*exhentai\.org/gi))) ? 'https://exhentai.org' : 'https://e-hentai.org';
  logger.debug(url);
  if ((match = url.match(/.*\/g\/([0-9]*)\/([0-z]*)\/*.*/))) {
    gID = match[1];
    gToken = match[2];
  } else {
    return { error: { error_code: "Not a valid E-H URL!" } };
  }
  logger.debug(`gID: ${gID}, gToken: ${gToken}`);
  let archiverurl = `${domain}\/archiver.php?gid=${gID}&token=${gToken}`;
  logger.info(`Archiver URL: ${archiverurl}`);
  let archiverHtml = (await lrr_info["user_agent"].max_redirects(5).get(archiverurl)).result.body;
  if (archiverHtml.indexOf("Invalid archiver key") != -1) {
    return { error: { error_code: "Invalid archiver key", data: { archiverurl } } };
  }
  if (archiverHtml.indexOf("This page requires you to log on.") != -1) {
    return { error: { error_code: "Invalid E*Hentai login credentials. Please make sure the login plugin has proper settings set." } };
  }
  let dltype = undefined;
  let dlcheck = undefined;
  if (params["forceresampled"]) {
    dltype = 'res';
    dlcheck = 'Download+Resample+Archive';
  } else {
    dltype = 'org';
    dlcheck = 'Download+Original+Archive';
  }
  let response = (await lrr_info["user_agent"].max_redirects(5).post(archiverurl, "form", {dltype: dltype, dlcheck: dlcheck})).result;
  let content = response.body;
  logger.debug(`/archiver.php result: ${content}`);
  if ((match = content.match(/.*Insufficient funds.*/gim))) {
    logger.debug("Not enough GP, aborting download.");
    return { error: { error_code: "You do not have enough GP to download this URL." } };
  }
  let finalURL = undefined;
  let parseError;
  try {
    // No `/g` flag: with it, `.match()` returns every full-match string instead of the one
    // capture group this code actually needs (`match[1]` would be `undefined` — the converter's
    // own warning on this exact line; verified with a real Deno repro before fixing).
    if ((match = content.match(/.*document\.location = "(.*)".*/im))) {
      finalURL = new URL(match[1]);
      logger.info(`Final URL obtained: ${finalURL}`);
    }
  } catch (caughtError) {
    parseError = caughtError;
  }
  let archivesize = params["forceresampled"] ? "a resampled" : "an original size";
  if (parseError || finalURL === undefined) {
    return { error: { error_code: "Couldn't proceed with download", data: { archivesize, content } } };
  }
  finalURL.search = "start=1";
  // `filename_hint` matters here: the H@H archive-serving URL's own last path segment isn't a
  // real filename (confirmed via a real download landing on the literal string `"2"`, no
  // extension at all, since neither a `Content-Disposition` header nor this hint was available for
  // Rust's `resolve_filename` fallback chain to use) — E-Hentai galleries are always packaged as a
  // real `.zip` by the archiver, so `{gID}_{gToken}.zip` gives every download here a stable,
  // sensible, uniquely-named `.zip` file instead of a URL-derived guess.
  // Reported, never judged: the host compares this against its own catalogue to decide whether
  // this download supersedes (or is superseded by) an existing archive.
  const version_history = await collectVersionHistory(gID, gToken, logger);
  return {
    downloads: [{ url: finalURL.href, filename_hint: `${gID}_${gToken}.zip` }],
    version_history,
  };
}
