// Converted from LANraragi/lib/LANraragi/Plugin/Download/EHentai.pm via
// `lanrurugi-plugin-converter` (`cargo run -p lanrurugi-plugin-converter -- convert ...`),
// regenerated by `scripts/convert-plugins.sh` on 2026-07-19.
//
// Known limitations (from the converter's own warnings — review, don't blindly trust):
//   - =~ with /g in list context (/.*document.location = "(.*)".*/gim) — Perl returns every 
//     captured group across all matches; JS .match() with /g returns only full-match strings, not 
//     captures. Verify this call site by hand.
//   - =~ with /g in list context (/.*exhentai\.org/gi) — Perl returns every captured group across 
//     all matches; JS .match() with /g returns only full-match strings, not captures. Verify this 
//     call site by hand.
//   - =~ with /g in list context (/.*\/g\/([0-9]*)\/([0-z]*)\/*.*/) — Perl returns every captured 
//     group across all matches; JS .match() with /g returns only full-match strings, not captures. 
//     Verify this call site by hand.
//   - =~ with /g in list context (/.*Insufficient funds.*/gim) — Perl returns every captured group 
//     across all matches; JS .match() with /g returns only full-match strings, not captures. Verify 
//     this call site by hand.
//
// NOTE: this plugin makes HTTP calls but declared_permissions.net is still the
// converter's placeholder — fill in the real host(s), verified against the URL
// literals in the original Perl source, before this plugin can actually reach them
// (Deno's --allow-net grant is scoped to exactly this list).

export function pluginInfo() {
  return {
    namespace: "ehdl",
    type: "download" as const,
    parameters: [
      { name: "forceresampled", description: "Force resampled archive download", required: false, type: "bool" },
    ],
    // Verified against every URL literal this plugin's own execDownload actually calls
    // (archiver.php on either domain, chosen based on the input URL) — this plugin still talks to
    // E-Hentai/ExHentai itself (to resolve the real archive-download URL via the archiver form)
    // before handing the resulting URL off to Rust for the real byte-level fetch, unlike chaika.ts
    // (which needs no net permission at all since it does zero HTTP itself).
    declared_permissions: { net: ["e-hentai.org", "exhentai.org"], read: false, write: false },
    name: "E*Hentai Downloader",
    author: "thelastfantasy",
    description: "Downloads the given e*hentai URL and adds it to LANraragi. This uses GP to call the archiver, so make sure you have enough!",
    version: "0.1",
    login_from: "ehlogin",
    url_pattern: "e-?hentai\\.org|exhentai\\.org",
    domain_match: ["e-hentai.org", "exhentai.org"],
  };
}

export function pluginOptions() {
  return {
    domain_rules: [
      // The real archive download itself is served by an H@H (Hentai@Home) client node, not
      // e-hentai.org/exhentai.org (those only negotiate the final URL via archiver.php) — the
      // `downloads[]` URL this plugin returns always points here.
      {
        pattern: "*.hath.network",
        max_concurrent: 10,
        description: "Limit simultaneous downloads from H@H client nodes",
      },
    ],
    overwrite_on_duplicate: {
      default: false,
      description: "Overwrite an existing archive with the same content or filename when re-downloading (e.g. after a gallery was revised).",
    },
  };
}


export async function execDownload(hostArgs: Record<string, unknown>) {
  {
    const info = hostArgs as Record<string, any>;
    info.user_agent = legacyCompat.userAgent();
    for (const c of (info.user_agent_cookies ?? []) as { name: string; value: string; domain: string; path: string }[]) {
      info.user_agent.cookie_jar.add(c);
    }
    const headers = (info.user_agent_headers ?? {}) as Record<string, string>;
    if (Object.keys(headers).length > 0) {
      info.user_agent.on("start", (_ua: any, tx: any) => {
        for (const [name, value] of Object.entries(headers)) tx.req.headers.header(name, value);
      });
    }
  }
  interface ExecDownloadInfo extends Required<Pick<DownloadHostArgs, "url" | "customargs">> {
    user_agent: LegacyUserAgent;
    user_agent_cookies?: LegacyCookie[];
  }
  let match: RegExpMatchArray | null;
  // (shift) discarded positional arg — legacy Perl-OOP invocant/first @_ slot
  let lrr_info = hostArgs as unknown as ExecDownloadInfo;
  let params = { forceresampled: lrr_info.customargs[0] as boolean };
  let logger = legacyCompat.getLogger("EH Downloader", "plugins");
  let url = lrr_info["url"];
  let gID = "";
  let gToken = "";
  let archKey = "";
  let domain = ((match = url.match(/.*exhentai\.org/gi))) ? 'https://exhentai.org' : 'https://e-hentai.org';
  logger.debug(url);
  if ((match = url.match(/.*\/g\/([0-9]*)\/([0-z]*)\/*.*/))) {
    gID = match[1];
    gToken = match[2];
  } else {
    return { error: { error_code: "Not a valid E-H URL!" } };
  }
  logger.debug(`gID: ${gID}, gToken: ${gToken}`);
  let archiverurl = `${domain}\/archiver.php?gid=${gID}&token=${gToken}`;
  logger.info(`Archiver URL: ${archiverurl}`);
  let archiverHtml = (await lrr_info["user_agent"].max_redirects(5).get(archiverurl)).result.body;
  if (archiverHtml.indexOf("Invalid archiver key") != -1) {
    return { error: { error_code: "Invalid archiver key", data: { archiverurl } } };
  }
  if (archiverHtml.indexOf("This page requires you to log on.") != -1) {
    return { error: { error_code: "Invalid E*Hentai login credentials. Please make sure the login plugin has proper settings set." } };
  }
  let dltype = undefined;
  let dlcheck = undefined;
  if (params["forceresampled"]) {
    dltype = 'res';
    dlcheck = 'Download+Resample+Archive';
  } else {
    dltype = 'org';
    dlcheck = 'Download+Original+Archive';
  }
  let response = (await lrr_info["user_agent"].max_redirects(5).post(archiverurl, "form", {dltype: dltype, dlcheck: dlcheck})).result;
  let content = response.body;
  logger.debug(`/archiver.php result: ${content}`);
  if ((match = content.match(/.*Insufficient funds.*/gim))) {
    logger.debug("Not enough GP, aborting download.");
    return { error: { error_code: "You do not have enough GP to download this URL." } };
  }
  let finalURL = undefined;
  let parseError;
  try {
    // No `/g` flag: with it, `.match()` returns every full-match string instead of the one
    // capture group this code actually needs (`match[1]` would be `undefined` — the converter's
    // own warning on this exact line; verified with a real Deno repro before fixing).
    if ((match = content.match(/.*document\.location = "(.*)".*/im))) {
      finalURL = new URL(match[1]);
      logger.info(`Final URL obtained: ${finalURL}`);
    }
  } catch (caughtError) {
    parseError = caughtError;
  }
  let archivesize = params["forceresampled"] ? "a resampled" : "an original size";
  if (parseError || finalURL === undefined) {
    return { error: { error_code: "Couldn't proceed with download", data: { archivesize, content } } };
  }
  finalURL.search = "start=1";
  // `filename_hint` matters here: the H@H archive-serving URL's own last path segment isn't a
  // real filename (confirmed via a real download landing on the literal string `"2"`, no
  // extension at all, since neither a `Content-Disposition` header nor this hint was available for
  // Rust's `resolve_filename` fallback chain to use) — E-Hentai galleries are always packaged as a
  // real `.zip` by the archiver, so `{gID}_{gToken}.zip` gives every download here a stable,
  // sensible, uniquely-named `.zip` file instead of a URL-derived guess.
  return { downloads: [{ url: finalURL.href, filename_hint: `${gID}_${gToken}.zip` }] };
}
